query GetSubmission($id: ID!) {
  submission(id: $id) {
    id
    status
    title(language: "en")
    abstract(language: "en")
    elevatorPitch(language: "en")
    shortSocialSummary
    doNotRecord
    multilingualTitle {
      it
      en
    }
    multilingualAbstract {
      it
      en
    }
    multilingualElevatorPitch {
      it
      en
    }
    type {
      id
      name
    }
    notes
    canEdit
    speakerLevel
    previousTalkVideo
    topic {
      id
      name
    }
    duration {
      id
      name
    }
    audienceLevel {
      id
      name
    }
    languages {
      id
      code
      name
    }
    tags {
      id
      name
    }
    materials {
      id
      name
      url
      fileId
      fileUrl
      fileMimeType
    }
  }
}
