"""Unique user id for Customer

Revision ID: 0f119d128982
Revises: 940cac07a439
Create Date: 2021-04-10 15:29:26.252534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f119d128982'
down_revision = '940cac07a439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'customers', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'user_id')
    # ### end Alembic commands ###
