"""Nullable

Revision ID: 243010e54039
Revises: 9fb052a68c32
Create Date: 2021-04-17 20:02:40.372444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243010e54039'
down_revision = '9fb052a68c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'customer',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'customer',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
