"""Nullable

Revision ID: 548ab1b66c18
Revises: 87bf42f38e64
Create Date: 2021-04-17 20:05:25.826134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548ab1b66c18'
down_revision = '87bf42f38e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_invoices', 'subscription',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_invoices', 'subscription',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
