"""Nullable

Revision ID: 87bf42f38e64
Revises: 243010e54039
Create Date: 2021-04-17 20:03:09.577925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bf42f38e64'
down_revision = '243010e54039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
