"""new_structure

Revision ID: 8e84ee88057c
Revises: 
Create Date: 2021-12-12 20:10:20.962782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e84ee88057c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pretix_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['payment'], ['payments.id'], name='fk_pretix_payments_payments_id_payment'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_code')
    )
    op.create_table('stripe_subscription_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=256), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=256), nullable=False),
    sa.Column('invoice_pdf', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['payment'], ['payments.id'], name='fk_stripe_subscription_payments_payments_id_payment'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_invoice_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_subscription_payments')
    op.drop_table('pretix_payments')
    op.drop_table('subscriptions')
    op.drop_table('stripe_customers')
    op.drop_table('payments')
    # ### end Alembic commands ###
