"""timezone

Revision ID: 925566102b0c
Revises: 548ab1b66c18
Create Date: 2021-04-17 23:17:14.892288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925566102b0c'
down_revision = '548ab1b66c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
