"""Invoices

Revision ID: 9fb052a68c32
Revises: 64ffd22153f1
Create Date: 2021-04-11 18:32:47.449534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fb052a68c32'
down_revision = '64ffd22153f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=True),
    sa.Column('subscription', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=256), nullable=False),
    sa.Column('invoice_pdf', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['subscription'], ['subscriptions.id'], name='fk_subscription_invoices_subscriptions_id_subscription'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('subscription_payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=True),
    sa.Column('subscription', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('stripe_invoice_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('invoice_pdf', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscription'], ['subscriptions.id'], name='fk_subscription_payments_subscriptions_id_subscription'),
    sa.PrimaryKeyConstraint('id', name='subscription_payments_pkey')
    )
    op.drop_table('subscription_invoices')
    # ### end Alembic commands ###
