"""Subscriptions

Revision ID: e75ce4fdfcb5
Revises: 
Create Date: 2021-04-11 16:34:51.542355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75ce4fdfcb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['customer'], ['customers.id'], name='fk_subscriptions_customers_id_customer'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=True),
    sa.Column('subscription', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=256), nullable=False),
    sa.Column('invoice_pdf', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['subscription'], ['subscriptions.id'], name='fk_subscription_payments_subscriptions_id_subscription'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_payments')
    op.drop_table('subscriptions')
    op.drop_table('customers')
    # ### end Alembic commands ###
