# Generated by Django 2.2.4 on 2019-08-31 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date upload'),
            preserve_default=False,
        ),
    ]
