# Generated by Django 2.2.4 on 2019-09-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_file_date_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Upload',
        ),
    ]
