# Generated by Django 2.2.5 on 2019-09-23 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import i18n.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0011_auto_20190921_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('map_link', models.URLField(blank=True, verbose_name='map link')),
                ('title', i18n.fields.I18nCharField(verbose_name='title')),
                ('slug', i18n.fields.I18nCharField(verbose_name='slug')),
                ('content', i18n.fields.I18nTextField(verbose_name='content')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='conferences.Conference', verbose_name='conference')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'unique_together': {('slug', 'conference')},
            },
        ),
    ]
