# Generated by Django 2.2.7 on 2019-11-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_merge_20190919_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlevel',
            name='highlight_color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('yellow', 'yellow'), ('orange', 'orange'), ('cindarella', 'cindarella'), ('violet', 'violet'), ('green', 'green')], max_length=15, verbose_name='highlight color'),
        ),
    ]
