# Generated by Django 3.2.9 on 2021-12-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0006_auto_20200116_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='level',
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='levels',
            field=models.ManyToManyField(related_name='levels', to='sponsors.Sponsor', verbose_name='levels'),
        ),
    ]
