# Generated by Django 4.2.7 on 2024-01-10 15:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("conferences", "0038_alter_speakervoucher_unique_together_and_more"),
        ("sponsors", "0007_auto_20211212_2058"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorLead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("fullname", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=254)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsor_leads",
                        to="conferences.conference",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
