# Generated by Django 4.2.7 on 2024-01-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0008_sponsorlead"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorlead",
            name="company",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
