# Generated by Django 4.2.7 on 2024-01-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsors", "0010_sponsorlead_brochure_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorlead",
            name="consent_to_contact_via_email",
            field=models.BooleanField(default=False),
        ),
    ]
