# Generated by Django 4.2.7 on 2024-03-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0011_sponsorlead_consent_to_contact_via_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlevel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
