# Generated by Django 5.0.8 on 2024-09-29 22:44

import django.db.models.deletion
import django.utils.timezone
import i18n.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0047_alter_conferencevoucher_options_and_more'),
        ('sponsors', '0012_alter_sponsorlevel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlevel',
            name='price',
            field=models.CharField(default='Ask us', max_length=10, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='slots',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 means unlimited'),
        ),
        migrations.AlterField(
            model_name='sponsorlevel',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='levels', to='sponsors.sponsor', verbose_name='sponsors'),
        ),
        migrations.CreateModel(
            name='SponsorBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', i18n.fields.I18nCharField(max_length=100, verbose_name='name')),
                ('category', models.CharField(choices=[('content', 'Sponsored Content'), ('booth', 'Booth'), ('passes', 'Conference Passes'), ('brand', 'Brand Visibility'), ('recruiting', 'Recruiting'), ('attendee_interaction', 'Attendee Interaction')], max_length=100, verbose_name='category')),
                ('description', i18n.fields.I18nTextField(blank=True, verbose_name='description')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_benefits', to='conferences.conference')),
            ],
            options={
                'verbose_name': 'sponsor benefit',
                'verbose_name_plural': 'sponsor benefits',
                'unique_together': {('name', 'conference')},
            },
        ),
        migrations.CreateModel(
            name='SponsorBrochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('stats_attendees', models.CharField(default='800+', max_length=100, verbose_name="Previous year's attendees")),
                ('stats_speakers', models.CharField(default='100+', max_length=100, verbose_name="Previous year's speakers")),
                ('stats_talks', models.CharField(default='110+', max_length=100, verbose_name="Previous year's talks")),
                ('stats_unique_online_visitors', models.CharField(default='10,000+', max_length=100, verbose_name='Unique online visitors')),
                ('stats_sponsors', models.CharField(default='40+', max_length=100, verbose_name="Previous year's sponsors & partners")),
                ('stats_grants_given', models.CharField(default='30+', max_length=100, verbose_name="Previous year's grants given")),
                ('stats_coffee', models.CharField(default='6,000+', max_length=100, verbose_name="Previous year's coffee consumed")),
                ('introduction', i18n.fields.I18nTextField(blank=True, verbose_name='introduction')),
                ('tags', models.TextField(blank=True, verbose_name='tags')),
                ('city_description', i18n.fields.I18nTextField(blank=True, verbose_name='city description')),
                ('country_description', i18n.fields.I18nTextField(blank=True, verbose_name='country description')),
                ('community', i18n.fields.I18nTextField(blank=True, verbose_name='community')),
                ('why_sponsor_intro', i18n.fields.I18nTextField(blank=True, verbose_name='why sponsor intro')),
                ('why_sponsor', i18n.fields.I18nTextField(blank=True, verbose_name='why sponsor')),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_brochure', to='conferences.conference', verbose_name='conference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorLevelBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', i18n.fields.I18nCharField(default='✓', help_text='Value of the benefit, e.g. number of passes')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.sponsorbenefit', verbose_name='benefit')),
                ('sponsor_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.sponsorlevel', verbose_name='sponsor level')),
            ],
            options={
                'verbose_name': 'sponsor level benefit',
                'verbose_name_plural': 'sponsor level benefits',
                'unique_together': {('sponsor_level', 'benefit')},
            },
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='benefits',
            field=models.ManyToManyField(blank=True, limit_choices_to={'conference': models.F('conference')}, through='sponsors.SponsorLevelBenefit', to='sponsors.sponsorbenefit', verbose_name='benefits'),
        ),
        migrations.CreateModel(
            name='SponsorSpecialOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.CharField(max_length=10, verbose_name='price')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_special_options', to='conferences.conference')),
            ],
            options={
                'verbose_name': 'special option',
                'verbose_name_plural': 'special options',
                'unique_together': {('name', 'conference')},
            },
        ),
    ]
