# Generated by Django 5.0.8 on 2024-09-29 15:14

import django.db.models.deletion
import django.utils.timezone
import i18n.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0049_remove_conferencesponsorshippackage_conference_and_more'),
        ('sponsors', '0012_alter_sponsorlevel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorLevelBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('map_link', models.URLField(blank=True, verbose_name='map link')),
                ('name', i18n.fields.I18nCharField(max_length=100, verbose_name='name')),
                ('category', i18n.fields.I18nCharField(max_length=100, verbose_name='category')),
                ('value', i18n.fields.I18nTextField(blank=True, verbose_name='value')),
                ('description', i18n.fields.I18nTextField(blank=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorBrochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('map_link', models.URLField(blank=True, verbose_name='map link')),
                ('stats_attendees', models.CharField(default='800+', max_length=100, verbose_name="Previous year's attendees")),
                ('stats_speakers', models.CharField(default='100+', max_length=100, verbose_name="Previous year's speakers")),
                ('stats_talks', models.CharField(default='110+', max_length=100, verbose_name="Previous year's talks")),
                ('stats_unique_online_visitors', models.CharField(default='10,000+', max_length=100, verbose_name='Unique online visitors')),
                ('stats_sponsors', models.CharField(default='40+', max_length=100, verbose_name="Previous year's sponsors & partners")),
                ('stats_grants_given', models.CharField(default='30+', max_length=100, verbose_name="Previous year's grants given")),
                ('stats_coffee', models.CharField(default='6,000+', max_length=100, verbose_name="Previous year's coffee consumed")),
                ('introduction', i18n.fields.I18nTextField(blank=True, verbose_name='introduction')),
                ('tags', models.TextField(blank=True, verbose_name='tags')),
                ('city_description', i18n.fields.I18nTextField(blank=True, verbose_name='city description')),
                ('country_description', i18n.fields.I18nTextField(blank=True, verbose_name='country description')),
                ('community', i18n.fields.I18nTextField(blank=True, verbose_name='community')),
                ('why_sponsor_intro', i18n.fields.I18nTextField(blank=True, verbose_name='why sponsor intro')),
                ('why_sponsor', models.TextField(blank=True, verbose_name='why sponsor')),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_brochure', to='conferences.conference', verbose_name='conference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='sponsors.sponsorlevelbenefits', verbose_name='package options'),
        ),
    ]
