# Generated by Django 5.1.1 on 2024-11-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0013_sponsorlevel_price_sponsorlevel_slots_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorbenefit',
            options={'ordering': ('order',), 'verbose_name': 'sponsor benefit', 'verbose_name_plural': 'sponsor benefits'},
        ),
        migrations.AlterModelOptions(
            name='sponsorspecialoption',
            options={'ordering': ('order',), 'verbose_name': 'special option', 'verbose_name_plural': 'special options'},
        ),
        migrations.AddField(
            model_name='sponsorbenefit',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorspecialoption',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
