# Generated by Django 5.0.8 on 2024-09-29 15:20

import django.db.models.deletion
import django.utils.timezone
import i18n.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0013_sponsorlevelbenefits_sponsorbrochure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorlevel',
            name='benefits',
        ),
        migrations.CreateModel(
            name='SponsorLevelBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('map_link', models.URLField(blank=True, verbose_name='map link')),
                ('name', i18n.fields.I18nCharField(max_length=100, verbose_name='name')),
                ('category', i18n.fields.I18nCharField(max_length=100, verbose_name='category')),
                ('value', i18n.fields.I18nTextField(blank=True, verbose_name='value')),
                ('description', i18n.fields.I18nTextField(blank=True, verbose_name='description')),
                ('sponsor_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='sponsors.sponsorlevel', verbose_name='sponsor level')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SponsorLevelBenefits',
        ),
    ]
