# Generated by Django 5.0.8 on 2024-09-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0013_sponsorlevel_price_sponsorlevel_slots_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorBrochure',
        ),
    ]
