# Generated by Django 5.0.8 on 2024-09-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0014_remove_sponsorlevel_benefits_sponsorlevelbenefit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorlevelbenefit',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sponsorlevelbenefit',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sponsorlevelbenefit',
            name='map_link',
        ),
    ]
