# Generated by Django 5.0.8 on 2024-09-29 15:23

import i18n.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0015_remove_sponsorlevelbenefit_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlevelbenefit',
            name='category',
            field=i18n.fields.I18nCharField(choices=[('content', 'Sponsored Content'), ('booth', 'Booth'), ('passes', 'Conference Passes'), ('brand', 'Brand Visibility'), ('recruiting', 'Recruiting'), ('attendee_interaction', 'Attendee Interaction')], max_length=100, verbose_name='category'),
        ),
    ]
