# Generated by Django 5.0.8 on 2024-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0016_alter_sponsorlevelbenefit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorlevel',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='levels', to='sponsors.sponsor', verbose_name='sponsors'),
        ),
        migrations.AlterField(
            model_name='sponsorlevelbenefit',
            name='category',
            field=models.CharField(choices=[('content', 'Sponsored Content'), ('booth', 'Booth'), ('passes', 'Conference Passes'), ('brand', 'Brand Visibility'), ('recruiting', 'Recruiting'), ('attendee_interaction', 'Attendee Interaction')], max_length=100, verbose_name='category'),
        ),
    ]
