# Generated by Django 5.0.8 on 2024-09-29 16:12

import i18n.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0018_remove_sponsorbrochure_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorbrochure',
            name='why_sponsor',
            field=i18n.fields.I18nTextField(blank=True, verbose_name='why sponsor'),
        ),
    ]
