# Generated by Django 5.0.8 on 2024-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0019_alter_sponsorbrochure_why_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlevel',
            name='price',
            field=models.CharField(default='Ask us', max_length=10, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='slots',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 means unlimited'),
        ),
    ]
