# Generated by Django 5.0.8 on 2024-09-29 17:37

import django.db.models.deletion
import django.utils.timezone
import i18n.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0020_sponsorlevel_price_sponsorlevel_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', i18n.fields.I18nCharField(max_length=100, verbose_name='name')),
                ('category', models.CharField(choices=[('content', 'Sponsored Content'), ('booth', 'Booth'), ('passes', 'Conference Passes'), ('brand', 'Brand Visibility'), ('recruiting', 'Recruiting'), ('attendee_interaction', 'Attendee Interaction')], max_length=100, verbose_name='category')),
                ('value', i18n.fields.I18nTextField(blank=True, verbose_name='value')),
                ('description', i18n.fields.I18nTextField(blank=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sponsorlevelbenefit',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity of benefit (0 means unlimited)'),
        ),
        migrations.AlterField(
            model_name='sponsorlevelbenefit',
            name='sponsor_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.sponsorlevel', verbose_name='sponsor level'),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='benefits',
            field=models.ManyToManyField(blank=True, through='sponsors.SponsorLevelBenefit', to='sponsors.sponsorbenefit', verbose_name='benefits'),
        ),
        migrations.AddField(
            model_name='sponsorlevelbenefit',
            name='benefit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sponsors.sponsorbenefit', verbose_name='benefit'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sponsorlevelbenefit',
            unique_together={('sponsor_level', 'benefit')},
        ),
        migrations.RemoveField(
            model_name='sponsorlevelbenefit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sponsorlevelbenefit',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sponsorlevelbenefit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sponsorlevelbenefit',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='sponsorlevelbenefit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sponsorlevelbenefit',
            name='value',
        ),
    ]
