# Generated by Django 5.0.8 on 2024-09-29 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0049_remove_conferencesponsorshippackage_conference_and_more'),
        ('sponsors', '0021_sponsorbenefit_sponsorlevelbenefit_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorbenefit',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_benefits', to='conferences.conference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsorlevel',
            name='benefits',
            field=models.ManyToManyField(blank=True, limit_choices_to={'conference': models.F('conference')}, through='sponsors.SponsorLevelBenefit', to='sponsors.sponsorbenefit', verbose_name='benefits'),
        ),
    ]
