# Generated by Django 5.0.8 on 2024-09-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0049_remove_conferencesponsorshippackage_conference_and_more'),
        ('sponsors', '0022_sponsorbenefit_conference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorbenefit',
            options={'verbose_name': 'sponsor benefit', 'verbose_name_plural': 'sponsor benefits'},
        ),
        migrations.AlterModelOptions(
            name='sponsorlevelbenefit',
            options={'verbose_name': 'sponsor level benefit', 'verbose_name_plural': 'sponsor level benefits'},
        ),
        migrations.RemoveField(
            model_name='sponsorlevelbenefit',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sponsorlevelbenefit',
            name='value',
            field=models.PositiveIntegerField(default=0, help_text='Value of the benefit, e.g. number of passes'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorbenefit',
            unique_together={('name', 'conference')},
        ),
    ]
