# Generated by Django 5.0.8 on 2024-09-29 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0049_remove_conferencesponsorshippackage_conference_and_more'),
        ('sponsors', '0024_remove_sponsorbenefit_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_options', to='conferences.conference')),
            ],
            options={
                'verbose_name': 'special option',
                'verbose_name_plural': 'special options',
                'unique_together': {('name', 'conference')},
            },
        ),
    ]
