# Generated by Django 5.0.8 on 2024-09-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0049_remove_conferencesponsorshippackage_conference_and_more'),
        ('sponsors', '0025_specialoption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialOption',
            new_name='SponsorSpecialOption',
        ),
    ]
