# Generated by Django 5.0.8 on 2024-09-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0026_rename_specialoption_sponsorspecialoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorspecialoption',
            name='price',
            field=models.CharField(max_length=10, verbose_name='price'),
        ),
    ]
