# Generated by Django 4.2.7 on 2024-05-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_upload', '0003_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='purpose',
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('participant_avatar', 'Participant Avatar'), ('proposal_resource', 'Proposal Resource')], default='participant_avatar', max_length=32, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
