# Generated by Django 4.2.7 on 2024-05-27 15:10

from django.db import migrations, models
import files_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('files_upload', '0004_remove_file_purpose_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=files_upload.models.get_upload_to_from_instance, verbose_name='File'),
        ),
    ]
