# Generated by Django 4.2.7 on 2024-06-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_upload', '0005_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='virus',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is detected as virus?'),
        ),
    ]
