# Generated by Django 4.2.7 on 2024-06-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_upload', '0006_file_virus'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mime Type'),
        ),
    ]
