# Generated by Django 4.2.7 on 2024-06-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_upload', '0007_file_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('participant_avatar', 'Participant Avatar'), ('proposal_material', 'Proposal Material')], max_length=32, verbose_name='Type'),
        ),
    ]
