# Generated by Django 5.1.1 on 2024-10-06 22:48

import files_upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_upload', '0008_alter_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=1024, upload_to=files_upload.models.get_upload_to_from_instance, verbose_name='File'),
        ),
    ]
