# Generated by Django 3.2.12 on 2022-11-13 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0028_store_incoming_webhooks_in_conference_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('photo', models.TextField(verbose_name='photo')),
                ('bio', models.TextField(max_length=500)),
                ('website', models.URLField(max_length=2048, blank=True)),
                ('twitter_handle', models.CharField(max_length=15, blank=True)),
                ('speaker_level', models.CharField(choices=[('new', 'New speaker'), ('intermediate', 'Intermediate experience'), ('experienced', 'Experienced')], max_length=20, verbose_name='speaker level')),
                ('previous_talk_video', models.URLField(blank=True, max_length=2049, verbose_name='previous talk video')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='conferences.conference', verbose_name='conference')),
            ],
        ),
    ]
