# Generated by Django 3.2.12 on 2022-11-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_store_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='participant',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='participant',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
