# Generated by Django 3.2.12 on 2023-01-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0031_fix_keynote_details_save'),
        ('participants', '0003_add_mastodon_social'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('conference', 'user_id')},
        ),
    ]
