# Generated by Django 3.2.12 on 2023-01-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_fix_keynote_details_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='bio',
            field=models.TextField(max_length=1000),
        ),
    ]
