# Generated by Django 4.1.7 on 2023-03-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_bigger_participant_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='bio',
            field=models.TextField(max_length=2048),
        ),
    ]
