# Generated by Django 4.1.7 on 2023-05-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_increase_bio_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='public_profile',
            field=models.BooleanField(default=False, verbose_name='public profile'),
        ),
    ]
