# Generated by Django 4.2.7 on 2024-05-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_upload', '0003_alter_file_file'),
        ('participants', '0008_alter_participant_unique_together_participant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='photo_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files_upload.file'),
        ),
    ]
