# Generated by Django 4.2.7 on 2024-05-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_upload', '0005_alter_file_file'),
        ('participants', '0009_participant_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='photo_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='files_upload.file'),
        ),
    ]
