# Generated by Django 5.1.1 on 2024-10-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_alter_participant_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='photo'),
        ),
    ]
