# Generated by Django 5.1.1 on 2024-11-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_alter_participant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='speaker_availabilities',
            field=models.JSONField(blank=True, null=True, verbose_name='speaker availabilities'),
        ),
    ]
