# Generated by Django 5.2.8 on 2026-08-14 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participants", "0012_participant_speaker_availabilities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
