# Generated by Django 5.0.8 on 2024-08-18 22:29

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0044_remove_conference_slack_new_grant_reply_incoming_incoming_webhook_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='name')),
                ('identifier', models.CharField(choices=[('proposal_accepted', 'Proposal accepted'), ('proposal_rejected', 'Proposal rejected'), ('proposal_in_waiting_list', 'Proposal in waiting list'), ('proposal_scheduled_time_changed', 'Proposal scheduled time changed'), ('custom', 'Custom')], max_length=200, verbose_name='identifier')),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True, verbose_name='reply to')),
                ('subject', models.TextField(verbose_name='subject')),
                ('preview_text', models.TextField(blank=True, verbose_name='preview text')),
                ('body', models.TextField(verbose_name='body')),
                ('cc_addresses', models.JSONField(blank=True, default=list, verbose_name='cc addresses')),
                ('bcc_addresses', models.JSONField(blank=True, default=list, verbose_name='bcc addresses')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='conferences.conference', verbose_name='conference')),
            ],
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=200, verbose_name='status')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='recipient email')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('placeholders', models.JSONField(default=dict, verbose_name='placeholders')),
                ('subject', models.TextField(verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('preview_text', models.TextField(blank=True, verbose_name='preview text')),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254, verbose_name='reply to')),
                ('cc_addresses', models.JSONField(blank=True, default=list, verbose_name='cc addresses')),
                ('bcc_addresses', models.JSONField(blank=True, default=list, verbose_name='bcc addresses')),
                ('message_id', models.TextField(blank=True, verbose_name='message id')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='conferences.conference', verbose_name='conference')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='notifications.emailtemplate', verbose_name='email template')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('identifier', 'custom'), _negated=True), fields=('identifier', 'conference'), name='unique_non_custom_identifier_conference'),
        ),
    ]
