# Generated by Django 5.0.8 on 2024-08-25 18:16

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_emailtemplate_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='message_id',
            field=models.TextField(blank=True, db_index=True, verbose_name='message id'),
        ),
        migrations.CreateModel(
            name='SentEmailEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('event', models.CharField(choices=[('bounced', 'Bounced'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('complaint', 'Complaint'), ('unsubscribed', 'Unsubscribed')], max_length=200, verbose_name='event')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('sent_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notifications.sentemail', verbose_name='sent email')),
            ],
            options={
                'indexes': [models.Index(fields=['sent_email', 'event'], name='notificatio_sent_em_dd1297_idx')],
            },
        ),
    ]
