# Generated by Django 5.0.8 on 2024-08-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_sentemail_message_id_sentemailevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], db_index=True, default='pending', max_length=200, verbose_name='status'),
        ),
    ]
