# Generated by Django 5.0.8 on 2024-08-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_sentemail_text_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='from_email',
            field=models.EmailField(default='', max_length=254, verbose_name='from email'),
            preserve_default=False,
        ),
    ]
