# Generated by Django 5.0.8 on 2024-08-26 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0045_conference_logo'),
        ('notifications', '0007_alter_sentemailevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='is_system_template',
            field=models.BooleanField(default=False, verbose_name='is system template'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='conferences.conference', verbose_name='conference'),
        ),
    ]
