# Generated by Django 5.0.8 on 2024-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_emailtemplate_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=200, verbose_name='status'),
        ),
    ]
