# Generated by Django 5.0.8 on 2024-09-29 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0047_alter_conferencevoucher_options_and_more'),
        ('notifications', '0014_alter_emailtemplate_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='conferences.conference', verbose_name='conference'),
        ),
    ]
