# Generated by Django 5.1.4 on 2025-03-09 22:29

import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_alter_emailtemplate_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='body_file',
            field=models.FileField(blank=True, null=True, upload_to=notifications.models.sent_email_body_upload_to, verbose_name='body file'),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='text_body_file',
            field=models.FileField(blank=True, null=True, upload_to=notifications.models.sent_email_body_upload_to, verbose_name='text body file'),
        ),
    ]
