# Generated by Django 5.1.4

from django.db import migrations, models


def forwards_grant_voucher_to_voucher_code(apps, schema_editor):
    EmailTemplate = apps.get_model("notifications", "EmailTemplate")
    EmailTemplate.objects.filter(identifier="grant_voucher_code").update(
        identifier="voucher_code"
    )


def noop_reverse(apps, schema_editor):
    # Intentionally empty: reversing would not restore grant_voucher_code rows in a
    # distinguishable way from existing voucher_code templates (data loss on rollback).
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0021_alter_emailtemplate_identifier"),
    ]

    operations = [
        migrations.RunPython(
            forwards_grant_voucher_to_voucher_code,
            noop_reverse,
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="identifier",
            field=models.CharField(
                choices=[
                    ("proposal_accepted", "Proposal accepted"),
                    ("proposal_scheduled", "Proposal scheduled"),
                    ("proposal_rejected", "Proposal rejected"),
                    ("proposal_in_waiting_list", "Proposal in waiting list"),
                    (
                        "proposal_scheduled_time_changed",
                        "Proposal scheduled time changed",
                    ),
                    (
                        "proposal_received_confirmation",
                        "Proposal received confirmation",
                    ),
                    ("speaker_communication", "Speaker communication"),
                    ("voucher_code", "Voucher code"),
                    ("reset_password", "[System] Reset password"),
                    (
                        "grant_application_confirmation",
                        "Grant application confirmation",
                    ),
                    ("grant_approved", "Grant approved"),
                    ("grant_rejected", "Grant rejected"),
                    ("grant_waiting_list", "Grant waiting list"),
                    (
                        "grant_waiting_list_update",
                        "Grant waiting list update",
                    ),
                    ("sponsorship_brochure", "Sponsorship brochure"),
                    (
                        "visa_invitation_letter_download",
                        "Visa invitation letter download",
                    ),
                    ("custom", "Custom"),
                ],
                max_length=200,
                verbose_name="identifier",
            ),
        ),
    ]
