# Generated by Django 5.2.8 on 2026-08-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_remove_grant_voucher_code_template_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=200, verbose_name='status'),
        ),
    ]
