pycon-frontend:
  - any: ['frontend/*']

pycon-backend:
  - any: ['backend/*']

association-backend:
  - any: ['association-backend/*']

association-frontend:
  - any: ['association-frontend/*']

users-backend:
  - any: ['users-backend/*']

gateway:
  - any: ['gateway/*']

infrastructure:
  - any: ['infrastructure/*']

🐙 github:
  - any: ['.github/*']

🔨toolkit:
  - any: ['toolkit/*']
