# Generated by Django 2.2.3 on 2019-07-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20190716_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='vote_range',
        ),
    ]
