# Generated by Django 2.2.4 on 2019-08-31 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_auto_20190811_1953'),
        ('conferences', '0006_auto_20190811_1918'),
    ]

    operations = [
    ]
