# Generated by Django 2.2.5 on 2019-10-12 20:38

from django.db import migrations
import i18n.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0011_auto_20190921_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='description',
            field=i18n.fields.I18nTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='name',
            field=i18n.fields.I18nCharField(max_length=100, verbose_name='name'),
        ),
    ]
