# Generated by Django 2.2.7 on 2019-12-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0014_auto_20191201_1327'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='ticketfare',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='ticketfare',
        #     name='conference',
        # ),
        # migrations.DeleteModel(
        #     name='TicketFareQuestion',
        # ),
        # migrations.DeleteModel(
        #     name='TicketFare',
        # ),
    ]
