# Generated by Django 2.2.7 on 2019-12-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0015_auto_20191215_0740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketFare',
        ),
    ]
