codecov:
  notify: {}
  require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range: "80%"
  round: down
  status:
    changes: false
    patch: true
    project: true
