FROM node:18.17.1

WORKDIR /home/node/app

RUN apt-get update -y

RUN apt-get install -y python3 python3-pip

RUN npm install -g pnpm; \
    pnpm --version; \
    pnpm setup; \
    mkdir -p /usr/local/share/pnpm &&\
    export PNPM_HOME="/usr/local/share/pnpm" &&\
    export PATH="$PNPM_HOME:$PATH"; \
    pnpm bin -g

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

RUN pip3 install websockets --break-system-packages

COPY . .
