FROM node:18.17.1

WORKDIR /home/node/app

RUN npm install -g pnpm; \
    pnpm --version; \
    pnpm setup; \
    mkdir -p /usr/local/share/pnpm &&\
    export PNPM_HOME="/usr/local/share/pnpm" &&\
    export PATH="$PNPM_HOME:$PATH"; \
    pnpm bin -g

# COPY package.json pnpm-lock.yaml ./
# RUN pnpm install

COPY . .

