ARG FUNCTION_DIR="/home/app/"

FROM python:3.11

RUN apt update -y && apt install -y ffmpeg libsm6 libxext6

ARG FUNCTION_DIR

RUN mkdir -p ${FUNCTION_DIR}
WORKDIR ${FUNCTION_DIR}

RUN pip install pdm==2.21.0 uv==0.5.5
RUN pdm config use_uv true

COPY pyproject.toml pdm.lock ${FUNCTION_DIR}

RUN mkdir -p ${FUNCTION_DIR}/assets

COPY . ${FUNCTION_DIR}
