ARG FUNCTION_DIR="/home/app/"

FROM python:3.13.5

RUN apt update -y && apt install -y ffmpeg libsm6 libxext6

ARG FUNCTION_DIR

RUN mkdir -p ${FUNCTION_DIR}
WORKDIR ${FUNCTION_DIR}

COPY --from=ghcr.io/astral-sh/uv:0.12.5 /uv /uvx /usr/local/bin/

RUN mkdir -p ${FUNCTION_DIR}/assets

COPY . ${FUNCTION_DIR}
