FROM node:23.9.0

WORKDIR /home/node/app

RUN apt-get update -y

RUN apt-get install -y python3 python3-pip

ENV PNPM_HOME="/usr/local/share/pnpm"
ENV PATH="/usr/local/share/pnpm/bin:$PATH"

RUN npm install -g pnpm && \
    mkdir -p /usr/local/share/pnpm/bin && \
    pnpm --version

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

RUN pip3 install websockets==14.1 --break-system-packages

COPY . .
