# hi
[build]
    base    = "frontend"


[[redirects]]
    from = "/speaker-guidelines"
    to = "/en/speaker-guidelines"
    status = 200
    force = true

[[redirects]]
    from = "/admin/*"
    to = "https://d1111jewijk23m.cloudfront.net/admin/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/_/*"
    to = "https://d1111jewijk23m.cloudfront.net/admin/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/django-static/*"
    to = "https://d1111jewijk23m.cloudfront.net/django-static/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/media/*"
    to = "https://d1111jewijk23m.cloudfront.net/media/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/graphql"
    to = "https://d1111jewijk23m.cloudfront.net/graphql"
    status = 200
    force = true

[[redirects]]
    from = "/login/google"
    to = "https://d1111jewijk23m.cloudfront.net/login/google-oauth2/"
    status = 200
    force = true

[[redirects]]
    from = "/complete/google-oauth2"
    to = "https://d1111jewijk23m.cloudfront.net/complete/google-oauth2/"
    status = 200
    force = true

[[redirects]]
    from = "/_dbg"
    to = "https://d1111jewijk23m.cloudfront.net/_dbg/"
    status = 200
    force = true

[[redirects]]
    from = "/"
    to = "/it"
    status = 301
    force = false
    conditions = {Language = ["it"]}

[[redirects]]
    from = "/"
    to = "/en"
    status = 301
    force = false

[[redirects]]
    from = "/en/blog/ pycon-11-cancelled/"
    to = "/en/blog/pycon-11-cancelled/"
    status = 301
    force = true

[[redirects]]
    from = "/en/blog/%20pycon-11-cancelled/"
    to = "/en/blog/pycon-11-cancelled/"
    status = 301
    force = true

[[redirects]]
    from = "/en/blog/ pycon-11-cancelled"
    to = "/en/blog/pycon-11-cancelled/"
    status = 301
    force = true

[[redirects]]
    from = "/en/blog/%20pycon-11-cancelled"
    to = "/en/blog/pycon-11-cancelled/"
    status = 301
    force = true
