# Generated by Django 2.2.3 on 2019-07-16 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import orders.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('bank', 'Bank Transfer')], max_length=10)),
                ('transaction_id', models.TextField(blank=True, default='', verbose_name='transaction id')),
                ('state', django_fsm.FSMIntegerField(choices=[(1, 'NEW'), (2, 'PROCESSING'), (3, 'COMPLETE'), (-1, 'FAILED')], default=orders.enums.PaymentState(1))),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('item_object_id', models.PositiveIntegerField(verbose_name='item object id')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='item type')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.Order', verbose_name='order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
