# Generated by Django 2.1.7 on 2019-06-08 14:00

from django.db import migrations
import django_fsm
import orders.enums


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(choices=[(1, 'NEW'), (2, 'PROCESSING'), (3, 'COMPLETE'), (-1, 'FAILED')], default=orders.enums.PaymentState(1), max_length=50),
        ),
    ]
