# Generated by Django 2.2.5 on 2019-09-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('bank', 'Bank Transfer'), ('paypal', 'PayPal')], max_length=10),
        ),
    ]
