# Generated by Django 2.1.1 on 2018-11-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='name')),
                ('type', models.CharField(choices=[('event', 'Conference'), ('cfp', 'Call for proposal'), ('voting', 'Voting'), ('refund', 'Ticket refund'), ('custom', 'Custom deadline')], max_length=10, verbose_name='type')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference', verbose_name='conference')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
