# Generated by Django 2.1.1 on 2018-10-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name': 'Conference', 'verbose_name_plural': 'Conferences'},
        ),
    ]
