# Generated by Django 2.1.2 on 2018-12-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='submission_types',
            field=models.ManyToManyField(to='submissions.SubmissionType', verbose_name='submission types'),
        ),
        migrations.AddField(
            model_name='duration',
            name='allowed_submission_types',
            field=models.ManyToManyField(to='submissions.SubmissionType', verbose_name='allowed submission types'),
        ),
    ]
