# Generated by Django 2.1.2 on 2018-12-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20181224_1331'),
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='submission_types',
            field=models.ManyToManyField(to='submissions.SubmissionType', verbose_name='submission types'),
        ),
    ]
