# Generated by Django 2.1.1 on 2018-10-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_auto_20181017_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='code',
            field=models.CharField(default='pp18', max_length=10, unique=True, verbose_name='code'),
            preserve_default=False,
        ),
    ]
