# Generated by Django 2.1.2 on 2018-12-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20181226_1924'),
        ('conferences', '0002_conference_submission_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='allowed_submission_types',
            field=models.ManyToManyField(to='submissions.SubmissionType', verbose_name='allowed submission types'),
        ),
    ]
