# Generated by Django 2.2.3 on 2019-07-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voting', '0001_initial'),
        ('conferences', '0002_auto_20190716_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='vote_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='voting.VoteRange', verbose_name='vote range'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketfare',
            unique_together={('conference', 'code')},
        ),
    ]
