# Generated by Django 2.1.7 on 2019-06-03 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('conferences', '0002_auto_20190511_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Order', verbose_name='order')),
                ('ticket_fare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conferences.TicketFare', verbose_name='ticket fare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
