# Generated by Django 2.1.7 on 2019-06-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('voting', '0001_initial'),
        ('conferences', '0002_auto_20190511_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='vote_range',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='voting.VoteRange',
                                    verbose_name='Vote Range'),
        ),
    ]
