# Generated by Django 2.1.1 on 2018-11-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_auto_20181111_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Audience Level',
                'verbose_name_plural': 'Audience Levels',
            },
        ),
        migrations.AlterField(
            model_name='deadline',
            name='type',
            field=models.CharField(choices=[('cfp', 'Call for proposal'), ('voting', 'Voting'), ('refund', 'Ticket refund'), ('custom', 'Custom deadline')], max_length=10, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='conference',
            name='audience_levels',
            field=models.ManyToManyField(to='conferences.AudienceLevel', verbose_name='audience levels'),
        ),
    ]
