# Generated by Django 2.1.7 on 2019-06-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('conferences', '0003_conference_vote_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='vote_range',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='voting.VoteRange',
                                    verbose_name='vote range'),
        ),
    ]
