# Generated by Django 2.1.1 on 2018-10-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_conference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='cfp_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='call for proposals ends at'),
        ),
        migrations.AddField(
            model_name='conference',
            name='cfp_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='call for proposals starts at'),
        ),
        migrations.AddField(
            model_name='conference',
            name='refund_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='refund ends at'),
        ),
        migrations.AddField(
            model_name='conference',
            name='refund_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='refund starts at'),
        ),
        migrations.AddField(
            model_name='conference',
            name='voting_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='voting ends at'),
        ),
        migrations.AddField(
            model_name='conference',
            name='voting_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='voting starts at'),
        ),
    ]
