# Generated by Django 2.2.4 on 2019-08-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketquestion_ticketquestionchoices_useranswer'),
        ('conferences', '0004_remove_conference_vote_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfare',
            name='questions',
            field=models.ManyToManyField(to='tickets.TicketQuestion', verbose_name='ticket questions'),
        ),
    ]
