# Generated by Django 2.2.4 on 2019-08-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0004_remove_conference_vote_range"),
    ]

    operations = [migrations.RunPython(migrations.RunPython.noop)]
