# Generated by Django 2.2.3 on 2019-07-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_auto_20190617_0011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
