# Generated by Django 2.1.2 on 2018-11-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_auto_20181111_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('duration', models.PositiveIntegerField(verbose_name='duration')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference', verbose_name='conference')),
            ],
            options={
                'verbose_name': 'Duration',
                'verbose_name_plural': 'Durations',
            },
        ),
    ]
