# Generated by Django 2.2.4 on 2019-08-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_ticketfare_questions'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop)
    ]
