# Generated by Django 2.2.4 on 2019-08-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_auto_20190811_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='maps_link',
            field=models.URLField(blank=True, verbose_name='map link'),
        ),
    ]
