# Generated by Django 2.1.2 on 2018-11-21 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='duration',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='duration'),
        ),
    ]
