# Generated by Django 2.1.2 on 2018-11-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_auto_20181121_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='conferences.Conference', verbose_name='conference'),
        ),
    ]
