# Generated by Django 2.1.1 on 2018-11-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('conferences', '0006_auto_20181029_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='languages',
            field=models.ManyToManyField(to='languages.Language', verbose_name='languages'),
        ),
    ]
