# Generated by Django 2.2.4 on 2019-08-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_auto_20190811_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='audience_levels',
            field=models.ManyToManyField(blank=True, to='conferences.AudienceLevel', verbose_name='audience levels'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='languages',
            field=models.ManyToManyField(blank=True, to='languages.Language', verbose_name='languages'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='submission_types',
            field=models.ManyToManyField(blank=True, to='submissions.SubmissionType', verbose_name='submission types'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='topics',
            field=models.ManyToManyField(blank=True, to='conferences.Topic', verbose_name='topics'),
        ),
    ]
