# Generated by Django 2.1.1 on 2018-11-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_conference_languages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Track',
            new_name='Topic',
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.RemoveField(
            model_name='conference',
            name='tracks',
        ),
        migrations.AddField(
            model_name='conference',
            name='topics',
            field=models.ManyToManyField(to='conferences.Topic', verbose_name='topics'),
        ),
    ]
