# Generated by Django 2.1.1 on 2018-11-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_auto_20181104_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='slug',
        ),
    ]
