# Generated by Django 2.2.4 on 2019-09-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_auto_20190831_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='introduction',
            field=models.TextField(default='Hiiiii', verbose_name='introduction'),
            preserve_default=False,
        ),
    ]
