# Generated by Django 2.1.1 on 2018-11-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_remove_conference_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
