# Generated by Django 2.2.4 on 2019-09-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_conference_introduction'),
        ('conferences', '0008_merge_20190831_1711'),
    ]

    operations = [
    ]
