# Generated by Django 2.2.6 on 2019-11-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0012_auto_20191012_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='pretix_event_url',
            field=models.URLField(blank=True, default='', verbose_name='pretix event url'),
        ),
    ]
