# Generated by Django 2.2.7 on 2019-11-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_auto_20191119_2132'),
        ('conferences', '0012_auto_20191012_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='submission_tags',
            field=models.ManyToManyField(blank=True, to='submissions.SubmissionTag', verbose_name='submission tags'),
        ),
    ]
