# Generated by Django 2.2.6 on 2019-11-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0012_auto_20191012_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='url_mailchimp',
            field=models.URLField(blank=True, verbose_name='url_mailchimp'),
        ),
    ]
