# Generated by Django 3.2.9 on 2021-12-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0017_auto_20191231_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='type',
            field=models.CharField(choices=[('cfp', 'Call for proposal'), ('voting', 'Voting'), ('refund', 'Ticket refund'), ('grants', 'Grants'), ('custom', 'Custom deadline')], max_length=10, verbose_name='type'),
        ),
    ]
