# Generated by Django 3.2.9 on 2021-12-31 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0019_add_new_keynote_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keynote',
            old_name='keynote_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='keynote',
            old_name='keynote_title',
            new_name='title',
        ),
    ]
