# Generated by Django 3.2.9 on 2021-12-31 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0020_rename_keynote_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='keynote',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferences.topic'),
        ),
    ]
