# Generated by Django 3.2.9 on 2022-01-01 14:17
import json
from django.db import migrations
import i18n.fields

def convert_data(apps, schema_editor):
    Keynote = apps.get_model("conferences", "Keynote")
    for keynote in Keynote.objects.all():
        keynote.description = json.dumps({
            "en": keynote.description
        })
        keynote.title = json.dumps({
            "en": keynote.title
        })
        for speaker in keynote.speakers.all():
            speaker.bio = json.dumps({
                "en": speaker.bio
            })
            speaker.pronouns = json.dumps({
                "en": speaker.pronouns
            })
            speaker.save()

        keynote.save()


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0021_allow_adding_a_topic_for_a_keynote'),
    ]

    operations = [
        migrations.RunPython(convert_data),
        migrations.AlterField(
            model_name='keynote',
            name='description',
            field=i18n.fields.I18nTextField(default='', verbose_name='keynote description'),
        ),
        migrations.AlterField(
            model_name='keynote',
            name='title',
            field=i18n.fields.I18nCharField(default='', max_length=512, verbose_name='keynote title'),
        ),
        migrations.AlterField(
            model_name='keynotespeaker',
            name='bio',
            field=i18n.fields.I18nTextField(verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='keynotespeaker',
            name='pronouns',
            field=i18n.fields.I18nCharField(max_length=512, verbose_name='pronouns'),
        ),
    ]
