# Generated by Django 3.2.9 on 2022-02-01 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0023_make_keynote_slug_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='keynote',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='published'),
        ),
    ]
