# Generated by Django 3.2.12 on 2022-03-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0024_allow_scheduling_keynoters'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='pretix_speaker_voucher_quota_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pretix speaker voucher quota id'),
        ),
    ]
