# Generated by Django 3.2.12 on 2022-03-30 22:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0025_allow_storing_voucher_quota_id_in_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_id', models.IntegerField(verbose_name='user')),
                ('voucher_code', models.TextField(help_text='Voucher code generated for this speaker. If the speaker has multiple events, only one code will be generated.')),
                ('pretix_voucher_id', models.IntegerField(help_text='ID of the voucher in the Pretix database')),
                ('voucher_email_sent_at', models.DateTimeField(blank=True, help_text='When the email was last sent', null=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='conferences.conference', verbose_name='conference')),
            ],
            options={
                'verbose_name': 'Speakers Voucher',
                'verbose_name_plural': 'Speakers Vouchers',
                'unique_together': {('conference', 'user_id')},
            },
        ),
    ]
