# Generated by Django 3.2.12 on 2022-07-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0027_allow_creating_empty_unsynced_speaker_vouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='slack_new_proposal_comment_incoming_webhook_url',
            field=models.URLField(blank=True, default='', max_length=1024, verbose_name='New proposal comment Slack incoming webhook for notification'),
        ),
        migrations.AddField(
            model_name='conference',
            name='slack_new_proposal_incoming_webhook_url',
            field=models.URLField(blank=True, default='', max_length=1024, verbose_name='New proposal Slack incoming webhook for notification'),
        ),
    ]
