# Generated by Django 3.2.12 on 2022-12-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0028_store_incoming_webhooks_in_conference_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='pretix_hotel_bed_layout_question_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='pretix hotel bed layout question id'),
        ),
    ]
