# Generated by Django 3.2.12 on 2023-01-28 11:39

from django.db import migrations
import i18n.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0030_connect_keynote_speaker_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keynotespeaker',
            name='bio',
            field=i18n.fields.I18nTextField(null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='keynotespeaker',
            name='pronouns',
            field=i18n.fields.I18nCharField(max_length=512, null=True, verbose_name='pronouns'),
        ),
    ]
