# Generated by Django 4.1.6 on 2023-02-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0031_fix_keynote_details_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='slack_new_grant_reply_incoming_incoming_webhook_url',
            field=models.URLField(blank=True, default='', max_length=1024, verbose_name='New grant reply Slack incoming webhook for notification'),
        ),
    ]
