# Generated by Django 4.1.6 on 2023-02-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0032_conference_slack_new_grant_reply_incoming_incoming_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='grants_default_accommodation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='grants default accommodation amount'),
        ),
        migrations.AddField(
            model_name='conference',
            name='grants_default_ticket_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='grants default ticket amount'),
        ),
        migrations.AddField(
            model_name='conference',
            name='grants_default_travel_from_europe_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='grants default travel from Europe amount'),
        ),
        migrations.AddField(
            model_name='conference',
            name='grants_default_travel_from_extra_eu_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='grants default travel from Extra EU amount'),
        ),
        migrations.AddField(
            model_name='conference',
            name='grants_default_travel_from_italy_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='grants default travel from Italy amount'),
        ),
    ]
