# Generated by Django 4.1.6 on 2023-02-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0033_grants_default_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='grants_default_accommodation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='grants default accommodation amount'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='grants_default_ticket_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='grants default ticket amount'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='grants_default_travel_from_europe_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='grants default travel from Europe amount'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='grants_default_travel_from_extra_eu_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='grants default travel from Extra EU amount'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='grants_default_travel_from_italy_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='grants default travel from Italy amount'),
        ),
    ]
