# Generated by Django 4.1.7 on 2023-02-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0034_alter_conference_grants_default_accommodation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='slack_speaker_invitation_answer_incoming_webhook_url',
            field=models.URLField(blank=True, default='', max_length=1024, verbose_name='New speaker invitation answer Slack incoming webhook for notification'),
        ),
    ]
