# Generated by Django 4.1.7 on 2023-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0035_send_slack_notification_when_speaker_replies_to_schedule_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakervoucher',
            name='voucher_type',
            field=models.CharField(choices=[('speaker', 'Speaker'), ('so_speaker', 'Co-Speaker')], default='speaker', max_length=20),
            preserve_default=False,
        ),
    ]
