# Generated by Django 4.2.3 on 2023-07-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0036_add_support_for_cospeakers_vouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='youtube_video_bottom_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
