# Generated by Django 4.2.3 on 2023-10-01 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conferences", "0037_conference_youtube_video_bottom_text"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name="keynotespeaker",
                    name="user_id",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                        db_column="user_id",
                    ),
                ),
                migrations.AlterField(
                    model_name="speakervoucher",
                    name="user_id",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                        db_column="user_id",
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="speakervoucher",
                    unique_together=set(),
                ),
                migrations.RemoveField(
                    model_name="keynotespeaker",
                    name="user_id",
                ),
                migrations.AddField(
                    model_name="keynotespeaker",
                    name="user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                migrations.AddField(
                    model_name="speakervoucher",
                    name="user",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                    preserve_default=False,
                ),
                migrations.AlterUniqueTogether(
                    name="speakervoucher",
                    unique_together={("conference", "user")},
                ),
                migrations.RemoveField(
                    model_name="speakervoucher",
                    name="user_id",
                ),
            ],
        )
    ]
