# Generated by Django 4.2.7 on 2024-01-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conferences", "0038_alter_speakervoucher_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="slack_new_sponsor_lead_incoming_webhook_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="New sponsor lead Slack incoming webhook for notification",
            ),
        ),
    ]
