# Generated by Django 4.2.7 on 2024-02-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conferences", "0039_conference_slack_new_sponsor_lead_incoming_webhook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="visa_application_form_link",
            field=models.URLField(
                blank=True, default="", verbose_name="Visa application form link"
            ),
        ),
    ]
