# Generated by Django 5.0.7 on 2024-07-27 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0042_conference_video_description_template_and_more'),
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conferences', to='organizers.organizer', verbose_name='organizer'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='code'),
        ),
    ]
