# Generated by Django 5.0.8 on 2024-08-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0043_conference_organizer_alter_conference_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='slack_new_grant_reply_incoming_incoming_webhook_url',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='slack_new_proposal_comment_incoming_webhook_url',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='slack_new_proposal_incoming_webhook_url',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='slack_new_sponsor_lead_incoming_webhook_url',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='slack_speaker_invitation_answer_incoming_webhook_url',
        ),
        migrations.AddField(
            model_name='conference',
            name='slack_new_grant_reply_channel_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='New grant reply Slack channel ID for notification'),
        ),
        migrations.AddField(
            model_name='conference',
            name='slack_new_proposal_channel_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='New proposal Slack channel ID for notification'),
        ),
        migrations.AddField(
            model_name='conference',
            name='slack_new_sponsor_lead_channel_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='New sponsor lead Slack channel ID for notification'),
        ),
        migrations.AddField(
            model_name='conference',
            name='slack_speaker_invitation_answer_channel_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='New speaker invitation answer Slack channel ID for notification'),
        ),
    ]
