# Generated by Django 5.0.8 on 2024-08-26 15:22

import conferences.models.conference
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0044_remove_conference_slack_new_grant_reply_incoming_incoming_webhook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='logo',
            field=models.ImageField(blank=True, upload_to=conferences.models.conference.get_upload_to, verbose_name='logo'),
        ),
    ]
