# Generated by Django 5.0.7 on 2024-08-24 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "conferences",
            "0044_remove_conference_slack_new_grant_reply_incoming_incoming_webhook_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conference",
            name="grants_default_accommodation_amount",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="grants_default_ticket_amount",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="grants_default_travel_from_europe_amount",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="grants_default_travel_from_extra_eu_amount",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="grants_default_travel_from_italy_amount",
        ),
    ]
