# Generated by Django 5.0.8 on 2024-09-12 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conferences", "0045_conference_logo"),
        (
            "conferences",
            "0045_remove_conference_grants_default_accommodation_amount_and_more",
        ),
    ]

    operations = []
