# Generated by Django 5.0.8 on 2024-09-18 21:23

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0045_conference_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpeakerVoucher',
            new_name='ConferenceVoucher'
        ),
    ]
