# Generated by Django 5.0.8 on 2024-09-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0046_rename_speaker_voucher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferencevoucher',
            options={'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='pretix_speaker_voucher_quota_id',
            new_name='pretix_conference_voucher_quota_id',
        ),
        migrations.AlterField(
            model_name='conferencevoucher',
            name='voucher_code',
            field=models.TextField(help_text='Voucher code generated for this user. A user can only have one code associated to them.'),
        ),
        migrations.AlterField(
            model_name='conferencevoucher',
            name='voucher_type',
            field=models.CharField(choices=[('speaker', 'Speaker'), ('co_speaker', 'Co-Speaker'), ('grant', 'Grant')], max_length=20),
        ),
    ]
