# Generated by Django 5.0.8 on 2024-10-12 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conferences", "0047_alter_conferencevoucher_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conference",
            name="grants_default_accommodation_amount",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="grants_default_ticket_amount",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="grants_default_travel_from_europe_amount",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="grants_default_travel_from_extra_eu_amount",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="grants_default_travel_from_italy_amount",
        ),
    ]
