# Generated by Django 5.1.1 on 2024-10-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0047_alter_conferencevoucher_options_and_more'),
        ('submissions', '0025_remove_proposalmaterial_title_proposalmaterial_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='proposal_tags',
            field=models.ManyToManyField(blank=True, to='submissions.submissiontag', verbose_name='proposal tags'),
        ),
    ]
