# Generated by Django 5.1.1 on 2024-11-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0048_conference_proposal_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='pretix_hotel_bed_layout_question_id',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='pretix_hotel_checkin_question_id',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='pretix_hotel_checkout_question_id',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='pretix_hotel_room_type_question_id',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='pretix_hotel_ticket_id',
        ),
    ]
