# Generated by Django 5.0.8 on 2024-09-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0048_conferencesponsorshippackageoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencesponsorshippackage',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='conferencesponsorshippackage',
            name='package_options',
        ),
        migrations.DeleteModel(
            name='ConferenceSponsorshipBrochure',
        ),
        migrations.DeleteModel(
            name='ConferenceSponsorshipPackage',
        ),
        migrations.DeleteModel(
            name='ConferenceSponsorshipPackageOption',
        ),
    ]
