# Generated by Django 5.1.1 on 2024-11-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0049_remove_conference_pretix_hotel_bed_layout_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='type',
            field=models.CharField(choices=[('cfp', 'Call for proposal'), ('voting', 'Voting'), ('refund', 'Ticket refund'), ('grants', 'Grants'), ('badge_preview', 'Badge preview'), ('custom', 'Custom deadline')], max_length=256, verbose_name='type'),
        ),
    ]
