# Generated by Django 5.1.4 on 2024-12-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0050_alter_deadline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='location',
            field=models.TextField(blank=True, max_length=1024, verbose_name='location'),
        ),
    ]
