# Generated by Django 5.1.4 on 2025-01-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0052_alter_deadline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='slack_new_invitation_letter_request_channel_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='New invitation letter request Slack channel ID for notification'),
        ),
    ]
