# Generated by Django 5.1.4 on 2025-04-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0053_conference_slack_new_invitation_letter_request_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='frontend_revalidate_secret',
            field=models.CharField(blank=True, default='', max_length=32224),
        ),
        migrations.AddField(
            model_name='conference',
            name='frontend_revalidate_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
