# Generated by Django 5.1.4 on 2025-07-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0054_conference_frontend_revalidate_secret_and_more'),
        ('grants', '0030_remove_grant_accommodation_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='grants_default_accommodation_amount',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='grants_default_ticket_amount',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='grants_default_travel_from_europe_amount',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='grants_default_travel_from_extra_eu_amount',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='grants_default_travel_from_italy_amount',
        ),
    ]
