# Generated by Django 5.1.4 on 2026-01-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0055_remove_conference_grants_default_accommodation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='max_proposals_per_user',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of proposals a user can submit. Leave empty for no limit.', null=True, verbose_name='max proposals per user'),
        ),
    ]
