# Generated by Django 5.1.4 on 2026-01-28

from django.db import migrations, models


def convert_custom_deadlines_to_grants_waiting_list_update(apps, schema_editor):
    """
    Convert existing custom deadlines with name containing
    'Update Grants in Waiting List' to the new grants_waiting_list_update type.
    """
    Deadline = apps.get_model("conferences", "Deadline")

    # Update custom deadlines that have "Update Grants in Waiting List" in their name
    Deadline.objects.filter(
        type="custom", name__contains={"en": "Update Grants in Waiting List"}
    ).update(type="grants_waiting_list_update")


def revert_grants_waiting_list_update_to_custom(apps, schema_editor):
    """
    Revert grants_waiting_list_update deadlines back to custom type.
    """
    Deadline = apps.get_model("conferences", "Deadline")
    Deadline.objects.filter(type="grants_waiting_list_update").update(type="custom")


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0056_conference_max_proposals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deadline",
            name="type",
            field=models.CharField(
                choices=[
                    ("cfp", "Call for proposal"),
                    ("voting", "Voting"),
                    ("refund", "Ticket refund"),
                    ("grants", "Grants"),
                    ("badge_preview", "Badge preview"),
                    ("invitation_letter_request", "Invitation letter request"),
                    ("grants_waiting_list_update", "Grants waiting list update"),
                    ("custom", "Custom deadline"),
                ],
                max_length=256,
                verbose_name="type",
            ),
        ),
        migrations.RunPython(
            convert_custom_deadlines_to_grants_waiting_list_update,
            revert_grants_waiting_list_update_to_custom,
        ),
    ]
