# Generated by Django 5.1.4 on 2026-05-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0057_add_grants_waiting_list_update_deadline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='hostname'),
        ),
    ]
