# Generated by Django 5.1.4 on 2026-05-28 17:12

from django.db import migrations, models


def set_conference_hostnames(apps, schema_editor):
    Conference = apps.get_model("conferences", "Conference")

    hostname_mapping = {
        "pycon2026": "2026.pycon.it",
        "pycon2025": "2025.pycon.it",
        "2024": "2024.pycon.it",
        "pycon2023": "2023.pycon.it",
        "pycon12": "2022.pycon.it",
        "pycon11": "2020.pycon.it",
        "testconf": "test.pycon.it",
    }

    for conference in Conference.objects.all():
        if conference.code in hostname_mapping:
            conference.hostname = hostname_mapping[conference.code]
            conference.save(update_fields=["hostname"])


def reverse_set_conference_hostnames(apps, schema_editor):
    Conference = apps.get_model("conferences", "Conference")
    Conference.objects.all().update(hostname="")


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0057_add_grants_waiting_list_update_deadline_type"),
    ]

    operations = [
        # Step 1: Add the field without unique constraint
        migrations.AddField(
            model_name="conference",
            name="hostname",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="hostname"
            ),
        ),
        # Step 2: Run data migration to set hostnames
        migrations.RunPython(
            set_conference_hostnames,
            reverse_set_conference_hostnames,
        ),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name="conference",
            name="hostname",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                unique=True,
                verbose_name="hostname",
            ),
        ),
    ]
