# Generated by Django 5.1.4 on 2025-03-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='user_first_name',
            field=models.TextField(default='', verbose_name='user first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='user_last_name',
            field=models.TextField(default='', verbose_name='user last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='user_name',
            field=models.TextField(blank=True, default='', verbose_name='user name'),
        ),
    ]
