# Generated by Django 2.1.5 on 2019-02-16 08:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        ('conferences', '0003_conference_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='conferences.Conference', verbose_name='conference')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(choices=[('submission', 'Submission'), ('custom', 'Custom')], max_length=10, verbose_name='type')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='conferences.Conference', verbose_name='conference')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talks', to='schedule.Room', verbose_name='room')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='submissions.Submission', verbose_name='submission')),
            ],
            options={
                'verbose_name': 'Schedule item',
                'verbose_name_plural': 'Schedule items',
            },
        ),
    ]
