# Generated by Django 2.2.3 on 2019-07-16 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('conferences', '0003_auto_20190716_0954'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='additional_speakers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='additional speakers'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='conferences.Conference', verbose_name='conference'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='rooms',
            field=models.ManyToManyField(related_name='talks', to='schedule.Room', verbose_name='rooms'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='submissions.Submission', verbose_name='submission'),
        ),
        migrations.AddField(
            model_name='room',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='conferences.Conference', verbose_name='conference'),
        ),
    ]
