# Generated by Django 2.2.8 on 2020-01-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200116_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='slug',
            field=models.CharField(blank=True, max_length=100, verbose_name='slug'),
        ),
    ]
