# Generated by Django 2.2.8 on 2020-02-06 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='schedule_configuration',
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('offset', models.PositiveSmallIntegerField()),
                ('size', models.PositiveSmallIntegerField(default=45)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedule.Day')),
            ],
        ),
    ]
