# Generated by Django 2.2.8 on 2020-02-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20200209_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('talk', 'Talk room'), ('training', 'Training room')], default='talk', max_length=10, verbose_name='type'),
        ),
    ]
