# Generated by Django 2.2.8 on 2020-02-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_scheduleitem_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleitem',
            old_name='languages',
            new_name='language',
        ),
    ]
