# Generated by Django 2.2.8 on 2020-02-12 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0017_auto_20191231_1607'),
        ('schedule', '0020_auto_20200212_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='audience_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='conferences.AudienceLevel', verbose_name='audience level'),
        ),
    ]
