# Generated by Django 2.2.8 on 2020-02-13 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0021_scheduleitem_audience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='subscribed_users',
            field=models.ManyToManyField(blank=True, related_name='intrested_in_items', to=settings.AUTH_USER_MODEL, verbose_name='subscribed users'),
        ),
    ]
