# Generated by Django 2.2.8 on 2020-02-19 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_scheduleitem_subscribed_users'),
        ('schedule', '0022_auto_20200215_2340'),
    ]

    operations = [
    ]
