# Generated by Django 2.2.8 on 2020-03-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_auto_20200304_2245'),
        ('schedule', '0023_merge_20200219_0001'),
    ]

    operations = [
    ]
