# Generated by Django 2.2.8 on 2020-03-16 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0024_auto_20200304_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='maximum_capacity',
            field=models.PositiveIntegerField(default=30, verbose_name='maximum capacity'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='maximum_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum capacity'),
        ),
        migrations.CreateModel(
            name='ScheduleItemBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='schedule.ScheduleItem', verbose_name='schedule item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Schedule item booking',
                'verbose_name_plural': 'Schedule item bookings',
                'unique_together': {('user', 'schedule_item')},
            },
        ),
    ]
