# Generated by Django 3.1.4 on 2021-05-02 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_auto_20200304_2245'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE schedule_scheduleitem_additional_speakers DROP CONSTRAINT schedule_scheduleite_user_id_ecd7e435_fk_users_use',
                    reverse_sql='ALTER TABLE schedule_scheduleitem_additional_speakers ADD CONSTRAINT schedule_scheduleite_user_id_ecd7e435_fk_users_use FOREIGN KEY (user_id) REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED',
                )
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='scheduleitem',
                    name='additional_speakers',
                ),
                migrations.CreateModel(
                    name='ScheduleItemAdditionalSpeaker',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('user_id', models.IntegerField(verbose_name='user')),
                        ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_speakers', to='schedule.scheduleitem', verbose_name='schedule item')),
                    ],
                    options={
                        'verbose_name': 'Schedule item additional speaker',
                        'verbose_name_plural': 'Schedule item additional speakers',
                        'db_table': 'schedule_scheduleitem_additional_speakers',
                        'unique_together': {('user_id', 'schedule_item')},
                    },
                ),
            ],
        ),
    ]
