# Generated by Django 3.2.12 on 2022-02-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_add_ability_to_specify_rooms_of_the_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='speaker_invitation_notes',
            field=models.TextField(blank=True, default='', verbose_name='Speaker invitation notes'),
        ),
    ]
