# Generated by Django 3.2.12 on 2022-02-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_allow_storing_speaker_invitation_notes_on_the_schedule_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('maybe', 'Maybe'), ('rejected', 'Speaker Rejected'), ('cant_attend', "Speaker can't attend anymore"), ('waiting_confirmation', 'Waiting confirmation'), ('cancelled', 'Cancelled')], default='waiting_confirmation', max_length=25, verbose_name='status'),
        ),
    ]
