# Generated by Django 3.2.12 on 2022-03-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_schedule_item_invitation_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='speaker_invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='speaker invitation sent at'),
        ),
    ]
