# Generated by Django 3.2.12 on 2022-03-04 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0024_allow_scheduling_keynoters'),
        ('schedule', '0030_store_when_speaker_invitation_was_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='keynote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='conferences.keynote', verbose_name='keynote'),
        ),
    ]
