# Generated by Django 3.2.12 on 2022-03-06 01:23

from django.db import migrations, models


def fix_rooms(apps, schema_editor):
    Room = apps.get_model("schedule", "Room")
    DayRoomThroughModel = apps.get_model("schedule", "DayRoomThroughModel")
    ScheduleItem = apps.get_model("schedule", "ScheduleItem")

    rooms_map = {
        # 'name': rooms_id
    }

    for room in Room.objects.all():
        if room.name not in rooms_map:
            rooms_map[room.name] = room.id

    for day_room in DayRoomThroughModel.objects.all():
        replace_with = rooms_map[day_room.room.name]
        day_room.room_id = replace_with
        day_room.save()

    for schedule_item in ScheduleItem.objects.all():
        new_rooms = []

        for schedule_room in schedule_item.rooms.all():
            replace_with = rooms_map[schedule_room.name]
            new_rooms.append(replace_with)

        schedule_item.rooms.set(new_rooms)
        schedule_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0031_allow_storing_keynotes_in_the_schedule'),
    ]

    operations = [
        migrations.RunPython(
            fix_rooms,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='room',
            name='conference',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
