# Generated by Django 3.2.12 on 2022-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0032_make_schedule_rooms_generic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='type',
            field=models.CharField(choices=[('submission', 'Submission'), ('talk', 'Talk'), ('training', 'Training'), ('keynote', 'Keynote'), ('custom', 'Custom')], max_length=10, verbose_name='type'),
        ),
    ]
