# Generated by Django 3.2.12 on 2022-03-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0033_new_schedule_item_type_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='attendees_total_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum capacity for this event. Leave blank for unlimited.', null=True, verbose_name='Attendees total capacity'),
        ),
    ]
