# Generated by Django 3.2.12 on 2022-03-28 23:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0024_allow_scheduling_keynoters'),
        ('schedule', '0034_add_support_for_booking_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='exclude_from_voucher_generation',
            field=models.BooleanField(default=False, help_text='If true this speaker will not be included in the voucher generation.'),
        ),
        migrations.CreateModel(
            name='SpeakerVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_id', models.IntegerField(verbose_name='user')),
                ('voucher_code', models.TextField(help_text='Voucher code generated for this speaker. If the speaker has multiple events, only one code will be generated.')),
                ('pretix_voucher_id', models.IntegerField(help_text='ID of the voucher in the Pretix database')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conference_speaker_vouchers', to='conferences.conference', verbose_name='conference')),
            ],
            options={
                'unique_together': {('conference', 'user_id')},
            },
        ),
    ]
