# Generated by Django 3.2.12 on 2022-03-26 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0034_add_field_to_store_max_capacity_for_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItemBookedSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_id', models.IntegerField(verbose_name='user')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='schedule.scheduleitem', verbose_name='schedule item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
