# Generated by Django 3.2.12 on 2022-03-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0035_voucher_code_generation_for_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakervoucher',
            name='voucher_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the email was last sent', null=True),
        ),
    ]
