# Generated by Django 3.2.12 on 2022-03-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0035_add_model_to_store_schedule_item_attendees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleItemBookedSeat',
            new_name='ScheduleItemAttendee',
        ),
        migrations.AlterUniqueTogether(
            name='scheduleitemattendee',
            unique_together={('user_id', 'schedule_item')},
        ),
    ]
