# Generated by Django 3.2.12 on 2022-03-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0036_make_attendees_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='attendees_total_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum capacity for this event. Leave blank to not limit attendees.', null=True, verbose_name='Attendees total capacity'),
        ),
    ]
