# Generated by Django 3.2.12 on 2022-03-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0026_move_speaker_voucher_in_conferences'),
        ('schedule', '0036_store_when_the_voucher_email_was_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakervoucher',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='conferences.conference', verbose_name='conference'),
        ),
    ]
