# Generated by Django 3.2.12 on 2022-05-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0039_add_support_for_slot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayroomthroughmodel',
            name='streaming_link',
            field=models.URLField(blank=True, verbose_name='Streaming URL'),
        ),
    ]
