# Generated by Django 3.2.12 on 2022-05-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0039_add_support_for_slot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitemattendee',
            name='is_in_waiting_list',
            field=models.BooleanField(default=False),
        ),
    ]
