# Generated by Django 3.2.12 on 2022-06-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0039_add_support_for_slot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayroomthroughmodel',
            name='slido_url',
            field=models.URLField(blank=True, default='', verbose_name='Sli.do URL'),
        ),
        migrations.AddField(
            model_name='dayroomthroughmodel',
            name='streaming_url',
            field=models.URLField(blank=True, default='', verbose_name='Streaming URL'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='slido_url',
            field=models.URLField(blank=True, default='', verbose_name='Sli.do URL'),
        ),
    ]
