# Generated by Django 3.2.12 on 2022-06-19 22:08

from django.db import migrations


def move_schedule_item_submissions_to_talk(apps, schema_editor):
    ScheduleItem = apps.get_model("schedule", "ScheduleItem")
    for schedule_item in ScheduleItem.objects.all():
        if schedule_item.type == 'submission':
            schedule_item.type = 'talk'
            schedule_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0040_add_streaming_slido_support'),
    ]

    operations = [
        migrations.RunPython(
            move_schedule_item_submissions_to_talk,
            reverse_code=migrations.RunPython.noop,
        )
    ]
