# Generated by Django 4.2.3 on 2023-07-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0043_allow_people_to_star_schedule_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='video_uploaded_path',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='path in the storage where the video file is uploaded'),
        ),
    ]
