# Generated by Django 4.2.3 on 2023-07-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0044_scheduleitem_video_uploaded_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='youtube_video_id',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Youtube video ID'),
        ),
    ]
