# Generated by Django 4.2.3 on 2023-10-01 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedule", "0045_scheduleitem_youtube_video_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name="scheduleitemadditionalspeaker",
                    name="user_id",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                        db_column="user_id",
                    ),
                ),
                migrations.AlterField(
                    model_name="scheduleitemattendee",
                    name="user_id",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                        db_column="user_id",
                    ),
                ),
                migrations.AlterField(
                    model_name="scheduleitemstar",
                    name="user_id",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                        db_column="user_id",
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="scheduleitemadditionalspeaker",
                    unique_together=set(),
                ),
                migrations.AlterUniqueTogether(
                    name="scheduleitemattendee",
                    unique_together=set(),
                ),
                migrations.AlterUniqueTogether(
                    name="scheduleitemstar",
                    unique_together=set(),
                ),
                migrations.AddField(
                    model_name="scheduleitemadditionalspeaker",
                    name="user",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="scheduleitemattendee",
                    name="user",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="scheduleitemstar",
                    name="user",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                    preserve_default=False,
                ),
                migrations.AlterUniqueTogether(
                    name="scheduleitemadditionalspeaker",
                    unique_together={("user", "scheduleitem")},
                ),
                migrations.AlterUniqueTogether(
                    name="scheduleitemattendee",
                    unique_together={("user", "schedule_item")},
                ),
                migrations.AlterUniqueTogether(
                    name="scheduleitemstar",
                    unique_together={("user", "schedule_item")},
                ),
                migrations.RemoveField(
                    model_name="scheduleitemadditionalspeaker",
                    name="user_id",
                ),
                migrations.RemoveField(
                    model_name="scheduleitemattendee",
                    name="user_id",
                ),
                migrations.RemoveField(
                    model_name="scheduleitemstar",
                    name="user_id",
                ),
            ],
        )
    ]
