# Generated by Django 4.2.3 on 2023-10-08 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0046_alter_scheduleitemadditionalspeaker_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitemadditionalspeaker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
