# Generated by Django 4.2.7 on 2024-02-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0047_alter_scheduleitemadditionalspeaker_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("submission", "Submission"),
                    ("talk", "Talk"),
                    ("training", "Training"),
                    ("keynote", "Keynote"),
                    ("panel", "Panel"),
                    ("registration", "Registration"),
                    ("announcements", "Announcements"),
                    ("break", "Break"),
                    ("custom", "Custom"),
                ],
                max_length=100,
                verbose_name="type",
            ),
        ),
    ]
