# Generated by Django 4.2.7 on 2024-02-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0048_alter_scheduleitem_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleitem",
            name="type",
            field=models.CharField(
                choices=[
                    ("submission", "Submission"),
                    ("talk", "Talk"),
                    ("training", "Training"),
                    ("keynote", "Keynote"),
                    ("panel", "Panel"),
                    ("registration", "Registration"),
                    ("announcements", "Announcements"),
                    ("break", "Break"),
                    ("social", "Social"),
                    ("custom", "Custom"),
                ],
                max_length=100,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="type",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("free_time", "Free Time"),
                    ("break", "Break"),
                ],
                default="default",
                max_length=100,
                verbose_name="type",
            ),
        ),
    ]
