# Generated by Django 4.2.7 on 2024-02-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0049_alter_scheduleitem_type_alter_slot_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleitem",
            name="rooms",
            field=models.ManyToManyField(
                blank=True,
                related_name="talks",
                to="schedule.room",
                verbose_name="rooms",
            ),
        ),
    ]
