# Generated by Django 4.2.7 on 2024-02-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0050_alter_scheduleitem_rooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="plain_thread_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Plain threadID"
            ),
        ),
    ]
