# Generated by Django 4.2.7 on 2024-03-03 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0051_scheduleitem_plain_thread_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItemSentForVideoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=100, verbose_name='Status')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Video upload attempts')),
                ('video_uploaded', models.BooleanField(default=False, verbose_name='Video uploaded')),
                ('thumbnail_uploaded', models.BooleanField(default=False, verbose_name='Thumbnail uploaded')),
                ('failed_reason', models.TextField(blank=True, default='', verbose_name='Failed reason')),
                ('schedule_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
