# Generated by Django 4.2.7 on 2024-03-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0052_scheduleitemsentforvideoupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitemsentforvideoupload',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last attempt at'),
        ),
    ]
