# Generated by Django 4.2.7 on 2024-05-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0053_scheduleitemsentforvideoupload_last_attempt_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='link_to',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='link to'),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='type',
            field=models.CharField(choices=[('submission', 'Submission'), ('talk', 'Talk'), ('training', 'Training'), ('keynote', 'Keynote'), ('panel', 'Panel'), ('registration', 'Registration'), ('announcements', 'Announcements'), ('recruiting', 'Recruiting'), ('break', 'Break'), ('social', 'Social'), ('custom', 'Custom')], max_length=100, verbose_name='type'),
        ),
    ]
