# Generated by Django 5.1.4 on 2025-05-29 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0055_scheduleitem_talk_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='livestreaming_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livestreaming_talks', to='schedule.room', verbose_name='livestreaming room'),
        ),
    ]
