# Generated by Django 5.2.8 on 2026-03-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0056_scheduleitem_livestreaming_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='attendees_total_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum capacity for this room. Leave blank to not limit attendees.', null=True, verbose_name='default attendees total capacity'),
        ),
    ]
