# Generated by Django 5.2.8 on 2026-08-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0057_room_attendees_total_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitemsentforvideoupload',
            name='emails_scheduled',
            field=models.BooleanField(default=False, verbose_name='Emails scheduled'),
        ),
    ]
