# Generated by Django 5.2.8 on 2026-08-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0058_scheduleitemsentforvideoupload_emails_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='type',
            field=models.CharField(choices=[('talk', 'Talk'), ('training', 'Training'), ('keynote', 'Keynote'), ('panel', 'Panel'), ('registration', 'Registration'), ('announcements', 'Announcements'), ('recruiting', 'Recruiting'), ('break', 'Break'), ('social', 'Social'), ('custom', 'Custom')], max_length=100, verbose_name='type'),
        ),
    ]
