# Generated by Django 2.2.3 on 2019-07-15 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                (
                'text', models.CharField(max_length=256, verbose_name='text')),
            ],
            options={
                'verbose_name': 'Ticket Question',
                'verbose_name_plural': 'Ticket Questions',
            },
        ),
        migrations.CreateModel(
            name='TicketQuestionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('choice',
                 models.CharField(max_length=256, verbose_name='text')),
                ('question',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='tickets.TicketQuestion',
                                   verbose_name='question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
