# Generated by Django 2.2.4 on 2019-08-10 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.CharField(max_length=256, verbose_name='text')),
                ('question_type', models.CharField(choices=[('choice', 'Option Choice'), ('text', 'Free Text')], default='choice', max_length=10)),
            ],
            options={
                'verbose_name': 'Ticket Question',
                'verbose_name_plural': 'Ticket Questions',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('answer', models.CharField(max_length=256, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='tickets.TicketQuestion', verbose_name='ticket')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='tickets.Ticket', verbose_name='ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketQuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('choice', models.CharField(max_length=256, verbose_name='text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='tickets.TicketQuestion', verbose_name='question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
