# Generated by Django 2.2.3 on 2019-07-20 09:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketquestion_ticketquestionchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketquestion',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Option Choice'), ('text', 'Free Text')], default='choice', max_length=10),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('answer_text', models.CharField(max_length=256)),
                ('answer_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.TicketQuestionChoices', verbose_name='answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='tickets.TicketQuestion', verbose_name='ticket')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='tickets.Ticket', verbose_name='ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
