# Generated by Django 2.1.1 on 2018-10-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
    ]
