# Generated by Django 2.2.4 on 2019-08-10 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketquestion_ticketquestionchoice_useranswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketquestionchoice',
            options={'verbose_name': 'Ticket question choice', 'verbose_name_plural': 'Ticket question choices'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'User answer', 'verbose_name_plural': 'User answers'},
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(max_length=256, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='tickets.TicketQuestion', verbose_name='question'),
        ),
    ]
