# Generated by Django 2.1.1 on 2018-10-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_auto_20181017_1627'),
        ('tickets', '0003_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(max_length=10, verbose_name='code'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('conference', 'code')},
        ),
    ]
