# Generated by Django 2.2.4 on 2019-08-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190810_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='answer'),
        ),
    ]
