# Generated by Django 2.2.4 on 2019-08-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190811_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(blank=True, max_length=256, verbose_name='answer'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('ticket', 'question')},
        ),
    ]
