# Generated by Django 4.2.3 on 2023-11-05 21:01

import cms.components.base.blocks.accordion
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "text_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "is_main_title",
                                            wagtail.blocks.BooleanBlock(
                                                default=False, required=False
                                            ),
                                        ),
                                        (
                                            "subtitle",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "body_text_size",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("text-1", "Text-1"),
                                                    ("text-2", "Text-2"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "illustration",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("cathedral", "Cathedral"),
                                                    ("florence", "Florence"),
                                                    ("florence2", "Florence2"),
                                                    (
                                                        "handWithSnakeInside",
                                                        "Hand With Snake Inside",
                                                    ),
                                                    ("snake1", "Snake1"),
                                                    ("snake2", "Snake2"),
                                                    ("snake4", "Snake4"),
                                                    ("snake5", "Snake5"),
                                                    ("snakeBody", "Snake Body"),
                                                    ("snakeCouple", "Snake Couple"),
                                                    ("snakeDNA", "Snake D N A"),
                                                    ("snakeHead", "Snake Head"),
                                                    (
                                                        "snakeInDragon",
                                                        "Snake In Dragon",
                                                    ),
                                                    (
                                                        "snakeInDragonInverted",
                                                        "Snake In Dragon Inverted",
                                                    ),
                                                    ("snakeLetter", "Snake Letter"),
                                                    (
                                                        "snakeLongNeck",
                                                        "Snake Long Neck",
                                                    ),
                                                    ("snakePencil", "Snake Pencil"),
                                                    ("snakeTail", "Snake Tail"),
                                                    (
                                                        "snakeWithBalloon",
                                                        "Snake With Balloon",
                                                    ),
                                                    (
                                                        "snakeWithContacts",
                                                        "Snake With Contacts",
                                                    ),
                                                    (
                                                        "snakesWithBanner",
                                                        "Snakes With Banner",
                                                    ),
                                                    (
                                                        "snakesWithCocktail",
                                                        "Snakes With Cocktail",
                                                    ),
                                                    (
                                                        "snakesWithDirections",
                                                        "Snakes With Directions",
                                                    ),
                                                    (
                                                        "snakesWithOutlines",
                                                        "Snakes With Outlines",
                                                    ),
                                                    ("tripleSnakes", "Triple Snakes"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "accordions",
                                            wagtail.blocks.ListBlock(
                                                cms.components.base.blocks.accordion.Accordion
                                            ),
                                        ),
                                        (
                                            "cta",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "label",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "link",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "map",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "longitude",
                                            wagtail.blocks.DecimalBlock(
                                                decimal_places=6, max_digits=9
                                            ),
                                        ),
                                        (
                                            "latitude",
                                            wagtail.blocks.DecimalBlock(
                                                decimal_places=6, max_digits=9
                                            ),
                                        ),
                                        (
                                            "zoom",
                                            wagtail.blocks.IntegerBlock(default=15),
                                        ),
                                        ("link", wagtail.blocks.URLBlock()),
                                    ]
                                ),
                            ),
                            (
                                "slider_cards_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "spacing",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("xl", "Extra Large"),
                                                    ("3xl", "3 Extra Large"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "snake_background",
                                            wagtail.blocks.BooleanBlock(
                                                default=False, required=False
                                            ),
                                        ),
                                        (
                                            "cards",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "simple_text_card",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(),
                                                                ),
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(),
                                                                ),
                                                                (
                                                                    "cta",
                                                                    wagtail.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "label",
                                                                                wagtail.blocks.CharBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "link",
                                                                                wagtail.blocks.CharBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "price_card",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(),
                                                                ),
                                                                (
                                                                    "body",
                                                                    wagtail.blocks.RichTextBlock(),
                                                                ),
                                                                (
                                                                    "price",
                                                                    wagtail.blocks.CharBlock(),
                                                                ),
                                                                (
                                                                    "price_tier",
                                                                    wagtail.blocks.CharBlock(),
                                                                ),
                                                                (
                                                                    "cta",
                                                                    wagtail.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "label",
                                                                                wagtail.blocks.CharBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "link",
                                                                                wagtail.blocks.CharBlock(
                                                                                    required=False
                                                                                ),
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "sponsors_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "cta",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "label",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "link",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "layout",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("side-by-side", "Side-by-side"),
                                                    ("vertical", "Vertical"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "home_intro_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "pretitle",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "keynoters_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "cta",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "label",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "link",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "schedule_preview_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "primary_cta",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "label",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "link",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ],
                                                label="Primary CTA",
                                            ),
                                        ),
                                        (
                                            "secondary_cta",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "label",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "link",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ],
                                                label="Secondary CTA",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "socials_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "hashtag",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "special_guest_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "guest_name",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "guest_photo",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "guest_job_title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "event_date",
                                            wagtail.blocks.DateBlock(required=True),
                                        ),
                                        (
                                            "cta",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "label",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "link",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "information_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "illustration",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("cathedral", "Cathedral"),
                                                    ("florence", "Florence"),
                                                    ("florence2", "Florence2"),
                                                    (
                                                        "handWithSnakeInside",
                                                        "Hand With Snake Inside",
                                                    ),
                                                    ("snake1", "Snake1"),
                                                    ("snake2", "Snake2"),
                                                    ("snake4", "Snake4"),
                                                    ("snake5", "Snake5"),
                                                    ("snakeBody", "Snake Body"),
                                                    ("snakeCouple", "Snake Couple"),
                                                    ("snakeDNA", "Snake D N A"),
                                                    ("snakeHead", "Snake Head"),
                                                    (
                                                        "snakeInDragon",
                                                        "Snake In Dragon",
                                                    ),
                                                    (
                                                        "snakeInDragonInverted",
                                                        "Snake In Dragon Inverted",
                                                    ),
                                                    ("snakeLetter", "Snake Letter"),
                                                    (
                                                        "snakeLongNeck",
                                                        "Snake Long Neck",
                                                    ),
                                                    ("snakePencil", "Snake Pencil"),
                                                    ("snakeTail", "Snake Tail"),
                                                    (
                                                        "snakeWithBalloon",
                                                        "Snake With Balloon",
                                                    ),
                                                    (
                                                        "snakeWithContacts",
                                                        "Snake With Contacts",
                                                    ),
                                                    (
                                                        "snakesWithBanner",
                                                        "Snakes With Banner",
                                                    ),
                                                    (
                                                        "snakesWithCocktail",
                                                        "Snakes With Cocktail",
                                                    ),
                                                    (
                                                        "snakesWithDirections",
                                                        "Snakes With Directions",
                                                    ),
                                                    (
                                                        "snakesWithOutlines",
                                                        "Snakes With Outlines",
                                                    ),
                                                    ("tripleSnakes", "Triple Snakes"),
                                                ],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("coral", "coral"),
                                                    ("caramel", "caramel"),
                                                    ("cream", "cream"),
                                                    ("yellow", "yellow"),
                                                    ("green", "green"),
                                                    ("purple", "purple"),
                                                    ("pink", "pink"),
                                                    ("blue", "blue"),
                                                    ("red", "red"),
                                                    ("success", "success"),
                                                    ("warning", "warning"),
                                                    ("neutral", "neutral"),
                                                    ("error", "error"),
                                                    ("black", "black"),
                                                    ("grey", "grey"),
                                                    ("white", "white"),
                                                    ("milk", "milk"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "countdown_to_datetime",
                                            wagtail.blocks.DateTimeBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "countdown_to_deadline",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "cta",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "label",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "link",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("news_grid_section", wagtail.blocks.StructBlock([])),
                            (
                                "checkout_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "show_conference_tickets_products",
                                            wagtail.blocks.BooleanBlock(
                                                default=False, required=False
                                            ),
                                        ),
                                        (
                                            "show_social_events_products",
                                            wagtail.blocks.BooleanBlock(
                                                default=False, required=False
                                            ),
                                        ),
                                        (
                                            "show_tours_products",
                                            wagtail.blocks.BooleanBlock(
                                                default=False, required=False
                                            ),
                                        ),
                                        (
                                            "show_gadgets_products",
                                            wagtail.blocks.BooleanBlock(
                                                default=False, required=False
                                            ),
                                        ),
                                        (
                                            "show_membership_products",
                                            wagtail.blocks.BooleanBlock(
                                                default=False, required=False
                                            ),
                                        ),
                                        (
                                            "show_hotel_products",
                                            wagtail.blocks.BooleanBlock(
                                                default=False, required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("live_streaming_section", wagtail.blocks.StructBlock([])),
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
