"""subscription

Revision ID: 181756698b17
Revises: 
Create Date: 2021-03-18 03:58:45.942162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181756698b17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=128), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subscription_payment',
    sa.Column('stripe_invoice_id', sa.String(length=128), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invoice_pdf', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.user_id'], ),
    sa.PrimaryKeyConstraint('stripe_invoice_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_payment')
    op.drop_table('subscription')
    # ### end Alembic commands ###
