"""subscription

Revision ID: 43aa24ab0d8d
Revises: # noqa
Create Date: 2021-03-07 19:22:05.563315

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "43aa24ab0d8d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_payment_due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stripe_id", sa.String(length=128), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=128), nullable=False),
        sa.Column("stripe_session_id", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "subscription_payment",
        sa.Column("invoice_id", sa.String(length=128), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("payment_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("invoice_pdf", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscription.user_id"]),
        sa.PrimaryKeyConstraint("invoice_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription_payment")
    op.drop_table("subscription")
    # ### end Alembic commands ###
