"""subscription model

Revision ID: baf3a41d2a8f
Create Date: 2021-02-17 18:35:52.486998

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "baf3a41d2a8f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Subscription",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("payment_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stripe_id", sa.String(length=128), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "payment_date"),
        sa.UniqueConstraint("stripe_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Subscription")
    # ### end Alembic commands ###
