"""added subscription.canceled_at

Revision ID: c6d6e1f8cdad
Revises: 181756698b17
Create Date: 2021-03-22 05:26:00.180901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d6e1f8cdad'
down_revision = '181756698b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'canceled_at')
    # ### end Alembic commands ###
