# Generated by Django 2.2.5 on 2019-09-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20190911_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ('order',)},
        ),
    ]
