# Generated by Django 3.2.12 on 2022-05-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_notifications', '0002_remove_subtitle_from_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
