# Generated by Django 3.2.12 on 2022-05-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_notifications', '0003_change_default_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerdevice',
            name='user_id',
        ),
    ]
