# Generated by Django 2.1.7 on 2019-06-14 16:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField(verbose_name='vote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('first', models.IntegerField(verbose_name='first')),
                ('last', models.IntegerField(verbose_name='last')),
                ('step', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='step')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vote',
            name='range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voting.VoteRange', verbose_name='range'),
        ),
        migrations.AddField(
            model_name='vote',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.Submission', verbose_name='submission'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
