# Generated by Django 2.1.7 on 2019-06-24 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('voting', '0002_auto_20190614_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='range',
        ),
        migrations.AlterField(
            model_name='vote',
            name='submission',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='votes', to='submissions.Submission',
                verbose_name='submission'),
        ),
    ]
