# Generated by Django 2.2.8 on 2020-01-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20200117_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranksubmission',
            name='absolute_score',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='absolute score'),
        ),
    ]
