# Generated by Django 2.2.8 on 2020-01-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20200121_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='propagated',
            field=models.BooleanField(default=False, verbose_name='propagated'),
        ),
    ]
