# Generated by Django 3.2.9 on 2022-01-07 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0023_make_keynote_slug_i18n'),
        ('voting', '0014_vote_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pretix_organizer_id', models.CharField(max_length=200, verbose_name='pretix organizer id')),
                ('pretix_event_id', models.CharField(max_length=200, verbose_name='pretix event id')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_voting_events', to='conferences.conference', verbose_name='conference')),
            ],
            options={
                'verbose_name': 'included event for voting',
                'verbose_name_plural': 'included events for voting',
            },
        ),
    ]
