# Generated by Django 3.2.9 on 2022-02-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_add_model_to_store_included_events_when_checking_voting_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankrequest',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is_public'),
            preserve_default=False,
        ),
    ]
