# Generated by Django 3.2.9 on 2022-02-11 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_rankrequest_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranksubmission',
            name='absolute_rank',
        ),
        migrations.RemoveField(
            model_name='ranksubmission',
            name='absolute_score',
        ),
        migrations.RemoveField(
            model_name='ranksubmission',
            name='topic_rank',
        ),
        migrations.AddField(
            model_name='ranksubmission',
            name='rank',
            field=models.PositiveIntegerField(default=1, verbose_name='rank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranksubmission',
            name='score',
            field=models.DecimalField(decimal_places=6, default=5, max_digits=9, verbose_name='score'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RankStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
                ('type', models.CharField(choices=[('speakers', 'Speakers'), ('submissions', 'Submissions'), ('gender', 'Gender'), ('submission_type', 'Submission  Type'), ('topic', 'Topic'), ('language', 'Language'), ('audience_level', 'Audience Level')], max_length=25, verbose_name='type')),
                ('rank_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='voting.rankrequest', verbose_name='Rank Request')),
            ],
        ),
    ]
