# Generated by Django 3.2.9 on 2022-02-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_rankrequest_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
                ('type', models.CharField(choices=[('speakers', 'Speakers'), ('submissions', 'Submissions'), ('gender', 'Gender'), ('submission_type', 'Submission  Type'), ('language', 'Language'), ('audience_level', 'Audience Level')], max_length=25, verbose_name='type')),
                ('rank_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='voting.rankrequest', verbose_name='Rank Request')),
            ],
        ),
    ]
