# Generated by Django 3.2.12 on 2022-12-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_make_submission_topi_optional'),
        ('voting', '0017_rankrequest_by_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranksubmission',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.submissiontag', verbose_name='tag'),
        ),
    ]
