# Generated by Django 3.2.12 on 2023-01-28 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_make_submission_topi_optional'),
        ('voting', '0017_rankrequest_by_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranksubmission',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.submissiontag', verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='ranksubmission',
            name='total_submissions_per_tag',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Submissions Per Tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ranksubmission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='submissions.submission', verbose_name='submission'),
        ),
    ]
