# Generated by Django 3.2.9 on 2022-02-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_rankstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranksubmission',
            name='absolute_rank',
        ),
        migrations.RemoveField(
            model_name='ranksubmission',
            name='absolute_score',
        ),
        migrations.RemoveField(
            model_name='ranksubmission',
            name='topic_rank',
        ),
        migrations.AddField(
            model_name='ranksubmission',
            name='rank',
            field=models.PositiveIntegerField(default=1, verbose_name='rank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranksubmission',
            name='score',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='score'),
            preserve_default=False,
        ),
    ]
