# Generated by Django 4.2.3 on 2023-10-01 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0023_remove_submission_speaker_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voting", "0018_ranksubmission_add_tag"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS voting_vote_user_id_c15f54ee;",
                    reverse_sql="CREATE INDEX voting_vote_user_id_c15f54ee ON voting_vote USING btree (user_id);",
                ),
                migrations.AlterField(
                    model_name="vote",
                    name="user_id",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                        db_column="user_id",
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="vote",
                    unique_together=set(),
                ),
                migrations.AddField(
                    model_name="vote",
                    name="user",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                    preserve_default=False,
                ),
                migrations.AlterUniqueTogether(
                    name="vote",
                    unique_together={("user", "submission")},
                ),
                migrations.RemoveField(
                    model_name="vote",
                    name="user_id",
                ),
            ],
        )
    ]
