# Generated by Django 3.2.12 on 2022-12-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0028_store_incoming_webhooks_in_conference_model'),
        ('voting', '0018_ranksubmission_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankrequest',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference', verbose_name='conference'),
        ),
    ]
