# Generated by Django 2.1.1 on 2018-10-29 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0006_auto_20181029_2205'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('abstract', models.CharField(max_length=1000, verbose_name='abstract')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference', verbose_name='conference')),
                ('helpers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='helpers')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talks', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferences.Track', verbose_name='track')),
            ],
        ),
    ]
