# Generated by Django 2.1.1 on 2018-11-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='elevator_pitch',
            field=models.TextField(default='', max_length=300, verbose_name='elevator pitch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='notes',
            field=models.TextField(default='', verbose_name='notes'),
            preserve_default=False,
        ),
    ]
