# Generated by Django 2.1.2 on 2018-11-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_auto_20181113_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='owner',
            new_name='speaker',
        ),
    ]
