# Generated by Django 2.1.1 on 2018-11-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_auto_20181029_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='abstract',
            field=models.TextField(max_length=1000, verbose_name='abstract'),
        ),
    ]
