# Generated by Django 2.1.1 on 2018-11-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_auto_20181103_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='helpers',
        ),
    ]
