# Generated by Django 2.1.1 on 2018-11-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('talks', '0004_remove_talk_helpers'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.Language', verbose_name='language'),
        ),
    ]
