name: 'Generate and publish schema to Apollo'
inputs:
  service-name:
    description: 'Name of the service'
    required: true
  service-graphql-url:
    description: 'Service GraphQL URL'
    required: true
  apollo-key:
    description: 'Apollo Key'
    required: true
  graph:
    description: 'What graph to use'
    required: true
    default: 'default-python-italia'
  variant:
    description: 'Variant of the graph'
    required: true
    default: 'ghactions'

runs:
  using: "composite"
  steps:
    - name: Download & Publish service ${{ inputs.service-name }} to Apollo Studio
      shell: bash
      env:
        APOLLO_KEY: ${{ inputs.apollo-key }}
      run: |
          rover subgraph introspect ${{ inputs.service-graphql-url }} > ${{ inputs.service-name }}-schema.graphql
          rover subgraph publish ${{ inputs.graph }}@${{ inputs.variant }} \
            --schema ${{ inputs.service-name }}-schema.graphql \
            --name ${{ inputs.service-name }} \
            --convert \
            --routing-url ${{ inputs.service-graphql-url }}
