# Generated by Django 5.1.1 on 2024-10-02 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0047_alter_conferencevoucher_options_and_more'),
        ('privacy_policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicyacceptancerecord',
            name='conference',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='conferences.conference'),
            preserve_default=False,
        ),
    ]
