# Generated by Django 2.1.2 on 2018-12-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_conference_submission_types'),
        ('submissions', '0002_auto_20181224_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conferences.Duration', verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='conferences.Conference', verbose_name='conference'),
        ),
    ]
