# Generated by Django 2.1.2 on 2018-12-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20181226_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='elevator_pitch',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='elevator pitch'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='notes'),
        ),
    ]
