# Generated by Django 2.1.2 on 2018-12-28 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20181228_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='duration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='conferences.Duration', verbose_name='duration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='languages.Language', verbose_name='language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='speaker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='conferences.Topic', verbose_name='topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='submissions.SubmissionType', verbose_name='type'),
            preserve_default=False,
        ),
    ]
