# Generated by Django 2.2.6 on 2019-11-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20191102_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='languages',
            field=models.ManyToManyField(to='languages.Language', verbose_name='languages'),
        ),
    ]
