# Generated by Django 2.2.5 on 2019-11-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_slug'),
        ('submissions', '0005_auto_20191102_2010'),
    ]

    operations = [
    ]
