# Generated by Django 2.2.7 on 2019-12-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_auto_20191119_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='previous_talk_video',
            field=models.URLField(blank=True, verbose_name='previous talk video'),
        ),
        migrations.AddField(
            model_name='submission',
            name='speaker_level',
            field=models.CharField(choices=[('new', 'New speaker'), ('intermediate', 'Intermediate experience'), ('experienced', 'Experienced')], default='', max_length=20, verbose_name='speaker level'),
            preserve_default=False,
        ),
    ]
