# Generated by Django 3.1.4 on 2021-05-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_submission_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name='submission',
                    name='speaker',
                    field=models.ForeignKey('users.User', db_constraint=False, db_index=True, null=False, on_delete=models.PROTECT)
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='submission',
                    name='speaker',
                ),
                migrations.AddField(
                    model_name='submission',
                    name='speaker_id',
                    field=models.IntegerField(verbose_name='speaker'),
                ),
            ]
        ),
    ]
