# Generated by Django 3.1.4 on 2021-05-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_speaker_fk'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name='submissioncomment',
                    name='author',
                    field=models.ForeignKey('users.User', db_constraint=False, db_index=True, null=False, on_delete=models.CASCADE, related_name="comments")
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='submissioncomment',
                    name='author',
                ),
                migrations.AddField(
                    model_name='submissioncomment',
                    name='author_id',
                    field=models.IntegerField(verbose_name='author'),
                ),
            ]
        ),
    ]
