# Generated by Django 3.2.9 on 2021-11-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_submission_comment_author_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='previous_talk_video',
            field=models.URLField(blank=True, max_length=2049, verbose_name='previous talk video'),
        ),
    ]
