# Generated by Django 3.2.12 on 2022-08-03 16:47

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_allow_bigger_previous_talk_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(verbose_name='title', max_length=99999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='elevator_pitch',
            field=models.CharField(blank=True, default='', verbose_name='elevator pitch', max_length=99999),
        ),
    ]
