# Generated by Django 3.2.12 on 2022-08-03 17:22

from django.db import migrations
import json

def update_multi_lingual_fields(apps, schema_editor):
    Submission = apps.get_model("submissions", "Submission")
    for submission in Submission.objects.all():
        languages = list(submission.languages.values_list('code', flat=True))
        if languages == ['en']:
            submission.abstract = {'en': submission.abstract, 'it': ''}
            submission.elevator_pitch = {'en': submission.elevator_pitch, 'it': ''}
            submission.title = {'en': submission.title, 'it': ''}
        elif languages == ['it']:
            submission.abstract = {'it': submission.abstract, 'en': ''}
            submission.elevator_pitch = {'it': submission.elevator_pitch, 'en': ''}
            submission.title = {'it': submission.title, 'en': ''}
        else:
            submission.abstract = {'en': submission.abstract, 'it': ''}
            submission.elevator_pitch = {'en': submission.elevator_pitch, 'it': ''}
            submission.title = {'en': submission.title, 'it': ''}

        submission.abstract = json.dumps(submission.abstract)
        submission.elevator_pitch = json.dumps(submission.elevator_pitch)
        submission.title = json.dumps(submission.title)
        submission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_add_support_for_multilingual_proposals'),
    ]

    operations = [
        migrations.RunPython(
            update_multi_lingual_fields,
        ),
    ]
