# Generated by Django 3.2.12 on 2022-08-03 17:24

from django.db import migrations
import i18n.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0016_migrate_data_of_proposals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='abstract',
            field=i18n.fields.I18nTextField(verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='elevator_pitch',
            field=i18n.fields.I18nTextField(blank=True, default='', verbose_name='elevator pitch'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=i18n.fields.I18nCharField(max_length=9000, verbose_name='title'),
        ),
    ]
