# Generated by Django 3.2.12 on 2022-08-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_change_data_to_be_international'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='notes'),
        ),
    ]
