# Generated by Django 3.2.12 on 2022-10-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_add_limit_to_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='short_social_summary',
            field=models.TextField(blank=True, default='', max_length=128, verbose_name='short social summary'),
        ),
    ]
