# Generated by Django 3.2.12 on 2022-11-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0028_store_incoming_webhooks_in_conference_model'),
        ('submissions', '0019_allow_adding_a_short_summy_for_socials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='topic',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='conferences.topic', verbose_name='topic'),
        ),
    ]
