# Generated by Django 3.2.12 on 2023-01-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_make_submission_topi_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pending_status',
            field=models.CharField(blank=True, choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='', max_length=20, verbose_name='pending status'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='proposed', max_length=20, verbose_name='status'),
        ),
    ]
