# Generated by Django 4.1.7 on 2023-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0021_pending_status_for_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='pending_status',
            field=models.CharField(blank=True, choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('waiting_list', 'Waiting list'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='', max_length=20, verbose_name='pending status'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('waiting_list', 'Waiting list'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='proposed', max_length=20, verbose_name='status'),
        ),
    ]
