# Generated by Django 4.2.3 on 2023-10-01 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submissions", "0022_add_waiting_list_status_to_submission"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS submissions_submission_speaker_id_9f7da519;",
                    reverse_sql="CREATE INDEX submissions_submission_speaker_id_9f7da519 ON submissions_submission USING btree (speaker_id);",
                ),
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS submissions_submissioncomment_author_id_f5be2cbf;",
                    reverse_sql="CREATE INDEX submissions_submissioncomment_author_id_f5be2cbf ON submissions_submissioncomment USING btree (author_id);",
                ),
                migrations.AlterField(
                    model_name="submission",
                    name="speaker_id",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="speaker",
                        db_column="speaker_id",
                    ),
                ),
                migrations.AlterField(
                    model_name="submissioncomment",
                    name="author_id",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                        db_column="author_id",
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="submission",
                    name="speaker_id",
                ),
                migrations.RemoveField(
                    model_name="submissioncomment",
                    name="author_id",
                ),
                migrations.AddField(
                    model_name="submission",
                    name="speaker",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="speaker",
                    ),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="submissioncomment",
                    name="author",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                    preserve_default=False,
                ),
            ],
        )
    ]
