# Generated by Django 4.2.7 on 2024-06-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0024_proposalmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalmaterial',
            name='title',
        ),
        migrations.AddField(
            model_name='proposalmaterial',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
