# Generated by Django 5.1.4 on 2025-01-20 22:54

from django.db import migrations

def sync_pending_status(apps, schema_editor):
    from django.db import models

    Submission = apps.get_model('submissions', 'Submission')
    Submission.objects.update(
        pending_status=models.F('status')
    )

class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0025_remove_proposalmaterial_title_proposalmaterial_name'),
    ]

    operations = [
        migrations.RunPython(sync_pending_status, reverse_code=migrations.RunPython.noop),
    ]
