# Generated by Django 5.1.4 on 2025-11-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0027_submissionconfirmpendingstatusproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='pending_status',
            field=models.CharField(blank=True, choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('waiting_list', 'Waiting list'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20, null=True, verbose_name='pending status'),
        ),
    ]
