# Generated by Django 5.2.8 on 2025-12-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0028_alter_submission_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='do_not_record',
            field=models.BooleanField(default=False, help_text='If true, the submission will not be recorded.', verbose_name='do not record'),
        ),
    ]
