# Generated by Django 5.2.8 on 2025-12-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0029_submission_do_not_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='is_recordable',
            field=models.BooleanField(default=True, help_text='If true, the proposals of this type can be recorded.', verbose_name='is recordable'),
        ),
    ]
