# Generated by Django 5.2.8 on 2026-01-05 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0030_submissiontype_is_recordable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionCoSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_speakers', to='submissions.submission', verbose_name='submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_speaker_submissions', to=settings.AUTH_USER_MODEL, verbose_name='co-speaker')),
            ],
            options={
                'verbose_name': 'co-speaker',
                'verbose_name_plural': 'co-speakers',
                'unique_together': {('submission', 'user')},
            },
        ),
    ]
