# Generated by Django 2.2.5 on 2019-09-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190914_1745'),
        ('cms', '0002_auto_20190914_1504'),
    ]

    operations = [
    ]
