# Generated by Django 2.2.5 on 2019-09-22 08:14

from django.db import migrations
import i18n.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_merge_20190919_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericcopy',
            name='content',
            field=i18n.fields.I18nTextField(verbose_name='content'),
        ),
    ]
