# Generated by Django 2.2.5 on 2019-10-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_menu_menulink'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is primary'),
        ),
    ]
