# Generated by Django 2.2.5 on 2019-10-04 19:35

from django.db import migrations
import i18n.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_menulink_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title',
            field=i18n.fields.I18nTextField(default={}, verbose_name='title'),
            preserve_default=False,
        ),
    ]
