# Generated by Django 2.2.4 on 2019-09-01 21:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0009_conference_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.SlugField(max_length=200, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy', to='conferences.Conference', verbose_name='conference')),
            ],
            options={
                'unique_together': {('key', 'conference')},
            },
        ),
    ]
