# Generated by Django 2.2.5 on 2019-09-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericcopy',
            options={'verbose_name': 'Generic Copy', 'verbose_name_plural': 'Generic Copy'},
        ),
    ]
