# Generated by Django 2.2.5 on 2019-10-03 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import i18n.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0011_auto_20190921_2340'),
        ('pages', '0002_auto_20190914_1504'),
        ('cms', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('identifier', models.SlugField(verbose_name='identifier')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='conferences.Conference', verbose_name='conference')),
            ],
            options={
                'unique_together': {('identifier', 'conference')},
            },
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', i18n.fields.I18nTextField(verbose_name='title')),
                ('href', i18n.fields.I18nTextField(blank=True, verbose_name='Link url')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cms.Menu', verbose_name='menu')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.Page', verbose_name='page')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
