query Submission($id: ID!) {
  submission(id: $id) {
    id
    title(language: "en")
    abstract(language: "en")
    elevatorPitch(language: "en")
    notes
    canEdit
    type {
      id
      name
    }
    duration {
      id
      name
      duration
    }
    audienceLevel {
      id
      name
    }
    languages {
      id
      name
      code
    }
    tags {
      id
      name
    }
    materials {
      id
      name
      url
      fileId
      fileUrl
      fileMimeType
    }
    speaker {
      id
      fullName
      participant {
        id
        photo
        bio
        twitterHandle
        instagramHandle
        linkedinUrl
        facebookUrl
        mastodonHandle
        website
      }
    }
  }
}
