# Generated by Django 5.1.4 on 2024-12-21 03:40

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import visa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0051_conference_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationLetterConferenceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_letter_config', to='conferences.conference', verbose_name='conference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvitationLetterAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('identifier', models.CharField(max_length=100, verbose_name='identifier')),
                ('image', models.ImageField(blank=True, null=True, storage=visa.models.private_storage_getter, upload_to='invitation_letters_assets/', verbose_name='image')),
                ('invitation_letter_conference_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='visa.invitationletterconferenceconfig', verbose_name='Invitation letter conference config')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvitationLetterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('document', models.FileField(blank=True, null=True, storage=visa.models.private_storage_getter, upload_to=visa.models.invitation_letter_attached_document_upload_to, verbose_name='document')),
                ('dynamic_document', models.JSONField(blank=True, null=True, verbose_name='dynamic document')),
                ('invitation_letter_conference_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_documents', to='visa.invitationletterconferenceconfig', verbose_name='Invitation letter conference config')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvitationLetterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('on_behalf_of', models.CharField(choices=[('SELF', 'Self'), ('OTHER', 'Other')], default='SELF', max_length=20, verbose_name='On behalf of')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('SENT', 'Sent'), ('REJECTED', 'Rejected'), ('FAILED_TO_GENERATE', 'Failed to generate')], default='PENDING', max_length=20, verbose_name='Status')),
                ('full_name', models.CharField(max_length=300, verbose_name='full name')),
                ('email_address', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('address', models.TextField(verbose_name='Address')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Passport number')),
                ('embassy_name', models.CharField(max_length=300, verbose_name='Embassy name')),
                ('invitation_letter', models.FileField(blank=True, null=True, storage=visa.models.private_storage_getter, upload_to=visa.models.invitation_letter_upload_to, verbose_name='Invitation letter')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('on_behalf_of', 'SELF')), fields=('conference', 'requester'), name='unique_self_request_per_conference')],
            },
        ),
    ]
