# Generated by Django 5.1.4 on 2025-01-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationletterdocument',
            name='inclusion_policy',
            field=models.CharField(choices=[('ALWAYS', 'Always'), ('GRANT_ACCOMMODATION', 'Has Accommodation via grant')], default='ALWAYS', max_length=20, verbose_name='Inclusion policy'),
        ),
    ]
