# Generated by Django 5.1.4 on 2024-12-14 17:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import visa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_organizer_email_from_address'),
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationletterrequest',
            name='invitation_letter',
            field=models.FileField(blank=True, null=True, storage=visa.models.private_storage_getter, upload_to=visa.models.invitation_letter_upload_to, verbose_name='Invitation letter'),
        ),
        migrations.CreateModel(
            name='InvitationLetterOrganizerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizers.organizer', verbose_name='organizer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvitationLetterAttachedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('document', models.FileField(storage=visa.models.private_storage_getter, upload_to=visa.models.invitation_letter_attached_document_upload_to, verbose_name='document')),
                ('invitation_letter_organizer_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_documents', to='visa.invitationletterorganizerconfig', verbose_name='invitation letter organizer config')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
