# Generated by Django 5.1.4 on 2024-12-16 16:41

import visa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_alter_invitationletterrequest_invitation_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationletterattacheddocument',
            name='dynamic_document',
            field=models.JSONField(blank=True, null=True, verbose_name='dynamic document'),
        ),
        migrations.AlterField(
            model_name='invitationletterattacheddocument',
            name='document',
            field=models.FileField(blank=True, null=True, storage=visa.models.private_storage_getter, upload_to=visa.models.invitation_letter_attached_document_upload_to, verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='invitationletterrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('SENT', 'Sent'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
