# Generated by Django 5.1.4 on 2024-12-18 20:22

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import visa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0004_rename_invitationletterattacheddocument_invitationletterdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationLetterAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('handle', models.CharField(max_length=100, verbose_name='handle')),
                ('image', models.ImageField(blank=True, null=True, storage=visa.models.private_storage_getter, upload_to='invitation_letters_assets/', verbose_name='image')),
                ('invitation_letter_organizer_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='visa.invitationletterorganizerconfig', verbose_name='invitation letter organizer config')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
