# Generated by Django 5.1.4 on 2024-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0005_invitationletterasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationletterdocument',
            name='name',
            field=models.CharField(default='', max_length=300, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationletterrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('SENT', 'Sent'), ('REJECTED', 'Rejected'), ('FAILED_TO_GENERATE', 'Failed to generate')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
