# Generated by Django 5.1.4 on 2024-12-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0006_invitationletterdocument_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationletterasset',
            old_name='handle',
            new_name='identifier',
        ),
    ]
