# Generated by Django 5.1.4 on 2024-12-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0007_rename_field_to_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationletterasset',
            name='identifier',
            field=models.CharField(max_length=100, verbose_name='identifier'),
        ),
    ]
