# Generated by Django 5.1.4 on 2024-12-21 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0051_conference_location'),
        ('visa', '0009_invitationletterconferenceconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationletterconferenceconfig',
            name='conference',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_letter_config', to='conferences.conference', verbose_name='conference'),
        ),
        migrations.RemoveField(
            model_name='invitationletterconferenceconfig',
            name='organizer',
        ),
    ]
