# Generated by Django 5.1.4 on 2024-12-21 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0011_alter_invitationletterconferenceconfig_conference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationletterasset',
            old_name='invitation_letter_organizer_config',
            new_name='invitation_letter_conference_config',
        ),
        migrations.RenameField(
            model_name='invitationletterdocument',
            old_name='invitation_letter_organizer_config',
            new_name='invitation_letter_conference_config',
        ),
    ]
