# Generated by Django 5.1.4 on 2024-12-21 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0012_remove_invitationletterasset_invitation_letter_organizer_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationletterasset',
            name='invitation_letter_conference_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='visa.invitationletterconferenceconfig', verbose_name='Invitation letter conference config'),
        ),
        migrations.AlterField(
            model_name='invitationletterdocument',
            name='invitation_letter_conference_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_documents', to='visa.invitationletterconferenceconfig', verbose_name='Invitation letter conference config'),
        ),
    ]
