# Generated by Django 4.1.7 on 2023-05-09 20:16

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('scanned_by_id', models.IntegerField(verbose_name='Scanned By')),
                ('badge_url', models.URLField(max_length=2048, verbose_name='Badge URL')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
