# Generated by Django 4.1.7 on 2023-05-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgescan',
            name='scanned_user_id',
            field=models.IntegerField(default=1, verbose_name='Attendee'),
            preserve_default=False,
        ),
    ]
