# Generated by Django 4.1.7 on 2023-05-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0036_add_support_for_cospeakers_vouchers'),
        ('badge_scanner', '0002_badgescan_scanned_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgescan',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='badge_scans', to='conferences.conference', verbose_name='conference'),
            preserve_default=False,
        ),
    ]
