# Generated by Django 4.1.7 on 2023-05-21 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0036_add_support_for_cospeakers_vouchers'),
        ('badge_scanner', '0004_badgescan_attendee_email_badgescan_attendee_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeScanExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('requested_by', models.IntegerField(verbose_name='requested_by')),
                ('file', models.FileField(upload_to='badge_scan_exports', verbose_name='file')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_scan_exports', to='conferences.conference', verbose_name='conference')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
