# Generated by Django 4.1.7 on 2023-05-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge_scanner', '0005_badgescanexport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgescanexport',
            old_name='requested_by',
            new_name='requested_by_id',
        ),
    ]
