# Generated by Django 3.1.4 on 2021-05-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191130_0913'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name='post',
                    name='author',
                    field=models.ForeignKey('users.User', db_constraint=False, db_index=True, null=False, on_delete=models.CASCADE)
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='post',
                    name='author',
                ),
                migrations.AddField(
                    model_name='post',
                    name='author_id',
                    field=models.IntegerField(verbose_name='author'),
                ),
            ],
        ),
    ]
