# Generated by Django 4.2.3 on 2023-10-01 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_post_author_fk"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS blog_post_author_id_dd7a8485;",
                    reverse_sql="CREATE INDEX blog_post_author_id_dd7a8485 ON blog_post USING btree (author_id);",
                ),
                migrations.AlterField(
                    model_name="post",
                    name="author_id",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                        db_column="author_id",
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="post",
                    name="author_id",
                ),
                migrations.AddField(
                    model_name="post",
                    name="author",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                    preserve_default=False,
                ),
            ],
        )
    ]
