# Generated by Django 2.2.4 on 2019-08-14 11:48

from django.db import migrations, models



def create_countries(apps, schema_editor):
    from ..countries import COUNTRIES

    Country = apps.get_model('countries', 'Country')

    for country in COUNTRIES:
        Country.objects.create(code=country['code'], name=country['name'])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.RunPython(create_countries, migrations.RunPython.noop)
    ]
