# https://www.iso.org/obp/ui/#search
COUNTRIES = [
    {"code": "AF", "name": "Afghanistan", "continent": "AS", "emoji": "🇦🇫"},
    {"code": "AL", "name": "Albania", "continent": "EU", "emoji": "🇦🇱"},
    {"code": "DZ", "name": "Algeria", "continent": "AF", "emoji": "🇩🇿"},
    {"code": "AS", "name": "American Samoa", "continent": "OC", "emoji": "🇦🇸"},
    {"code": "AD", "name": "Andorra", "continent": "EU", "emoji": "🇦🇩"},
    {"code": "AO", "name": "Angola", "continent": "AF", "emoji": "🇦🇴"},
    {"code": "AI", "name": "Anguilla", "continent": "NA", "emoji": "🇦🇮"},
    {"code": "AQ", "name": "Antarctica", "continent": "AN", "emoji": "🇦🇶"},
    {"code": "AG", "name": "Antigua and Barbuda", "continent": "NA", "emoji": "🇦🇬"},
    {"code": "AR", "name": "Argentina", "continent": "SA", "emoji": "🇦🇷"},
    {"code": "AM", "name": "Armenia", "continent": "AS", "emoji": "🇦🇲"},
    {"code": "AW", "name": "Aruba", "continent": "NA", "emoji": "🇦🇼"},
    {"code": "AU", "name": "Australia", "continent": "OC", "emoji": "🇦🇺"},
    {"code": "AT", "name": "Austria", "continent": "EU", "emoji": "🇦🇹"},
    {"code": "AZ", "name": "Azerbaijan", "continent": "AS", "emoji": "🇦🇿"},
    {"code": "BS", "name": "Bahamas", "continent": "NA", "emoji": "🇧🇸"},
    {"code": "BH", "name": "Bahrain", "continent": "AS", "emoji": "🇧🇭"},
    {"code": "BD", "name": "Bangladesh", "continent": "AS", "emoji": "🇧🇩"},
    {"code": "BB", "name": "Barbados", "continent": "NA", "emoji": "🇧🇧"},
    {"code": "BY", "name": "Belarus", "continent": "EU", "emoji": "🇧🇾"},
    {"code": "BE", "name": "Belgium", "continent": "EU", "emoji": "🇧🇪"},
    {"code": "BZ", "name": "Belize", "continent": "NA", "emoji": "🇧🇿"},
    {"code": "BJ", "name": "Benin", "continent": "AF", "emoji": "🇧🇯"},
    {"code": "BM", "name": "Bermuda", "continent": "NA", "emoji": "🇧🇲"},
    {"code": "BT", "name": "Bhutan", "continent": "AS", "emoji": "🇧🇹"},
    {
        "code": "BO",
        "name": "Bolivia, Plurinational State of",
        "continent": "SA",
        "emoji": "🇧🇴",
    },
    {
        "code": "BQ",
        "name": "Bonaire, Sint Eustatius and Saba",
        "continent": "NA",
        "emoji": "🇧🇶",
    },
    {"code": "BA", "name": "Bosnia and Herzegovina", "continent": "EU", "emoji": "🇧🇦"},
    {"code": "BW", "name": "Botswana", "continent": "AF", "emoji": "🇧🇼"},
    {"code": "BV", "name": "Bouvet Island", "continent": "AN", "emoji": "🇧🇻"},
    {"code": "BR", "name": "Brazil", "continent": "SA", "emoji": "🇧🇷"},
    {
        "code": "IO",
        "name": "British Indian Ocean Territory",
        "continent": "AS",
        "emoji": "🇮🇴",
    },
    {"code": "BN", "name": "Brunei Darussalam", "continent": "AS", "emoji": "🇧🇳"},
    {"code": "BG", "name": "Bulgaria", "continent": "EU", "emoji": "🇧🇬"},
    {"code": "BF", "name": "Burkina Faso", "continent": "AF", "emoji": "🇧🇫"},
    {"code": "BI", "name": "Burundi", "continent": "AF", "emoji": "🇧🇮"},
    {"code": "CV", "name": "Cabo Verde", "continent": "AF", "emoji": "🇨🇻"},
    {"code": "KH", "name": "Cambodia", "continent": "AS", "emoji": "🇰🇭"},
    {"code": "CM", "name": "Cameroon", "continent": "AF", "emoji": "🇨🇲"},
    {"code": "CA", "name": "Canada", "continent": "NA", "emoji": "🇨🇦"},
    {"code": "KY", "name": "Cayman Islands", "continent": "NA", "emoji": "🇰🇾"},
    {
        "code": "CF",
        "name": "Central African Republic",
        "continent": "AF",
        "emoji": "🇨🇫",
    },
    {"code": "TD", "name": "Chad", "continent": "AF", "emoji": "🇹🇩"},
    {"code": "CL", "name": "Chile", "continent": "SA", "emoji": "🇨🇱"},
    {"code": "CN", "name": "China", "continent": "AS", "emoji": "🇨🇳"},
    {"code": "CX", "name": "Christmas Island", "continent": "OC", "emoji": "🇨🇽"},
    {"code": "CC", "name": "Cocos (Keeling) Islands", "continent": "AS", "emoji": "🇨🇨"},
    {"code": "CO", "name": "Colombia", "continent": "SA", "emoji": "🇨🇴"},
    {"code": "KM", "name": "Comoros", "continent": "AF", "emoji": "🇰🇲"},
    {"code": "CG", "name": "Congo", "continent": "AF", "emoji": "🇨🇬"},
    {
        "code": "CD",
        "name": "Congo, The Democratic Republic of the",
        "continent": "AF",
        "emoji": "🇨🇩",
    },
    {"code": "CK", "name": "Cook Islands", "continent": "OC", "emoji": "🇨🇰"},
    {"code": "CR", "name": "Costa Rica", "continent": "NA", "emoji": "🇨🇷"},
    {"code": "HR", "name": "Croatia", "continent": "EU", "emoji": "🇭🇷"},
    {"code": "CU", "name": "Cuba", "continent": "NA", "emoji": "🇨🇺"},
    {"code": "CW", "name": "Curaçao", "continent": "NA", "emoji": "🇨🇼"},
    {"code": "CY", "name": "Cyprus", "continent": "EU", "emoji": "🇨🇾"},
    {"code": "CZ", "name": "Czechia", "continent": "EU", "emoji": "🇨🇿"},
    {"code": "CI", "name": "Côte d'Ivoire", "continent": "AF", "emoji": "🇨🇮"},
    {"code": "DK", "name": "Denmark", "continent": "EU", "emoji": "🇩🇰"},
    {"code": "DJ", "name": "Djibouti", "continent": "AF", "emoji": "🇩🇯"},
    {"code": "DM", "name": "Dominica", "continent": "NA", "emoji": "🇩🇲"},
    {"code": "DO", "name": "Dominican Republic", "continent": "NA", "emoji": "🇩🇴"},
    {"code": "EC", "name": "Ecuador", "continent": "SA", "emoji": "🇪🇨"},
    {"code": "EG", "name": "Egypt", "continent": "AF", "emoji": "🇪🇬"},
    {"code": "SV", "name": "El Salvador", "continent": "NA", "emoji": "🇸🇻"},
    {"code": "GQ", "name": "Equatorial Guinea", "continent": "AF", "emoji": "🇬🇶"},
    {"code": "ER", "name": "Eritrea", "continent": "AF", "emoji": "🇪🇷"},
    {"code": "EE", "name": "Estonia", "continent": "EU", "emoji": "🇪🇪"},
    {"code": "SZ", "name": "Eswatini", "continent": "AF", "emoji": "🇸🇿"},
    {"code": "ET", "name": "Ethiopia", "continent": "AF", "emoji": "🇪🇹"},
    {
        "code": "FK",
        "name": "Falkland Islands (Malvinas)",
        "continent": "SA",
        "emoji": "🇫🇰",
    },
    {"code": "FO", "name": "Faroe Islands", "continent": "EU", "emoji": "🇫🇴"},
    {"code": "FJ", "name": "Fiji", "continent": "OC", "emoji": "🇫🇯"},
    {"code": "FI", "name": "Finland", "continent": "EU", "emoji": "🇫🇮"},
    {"code": "FR", "name": "France", "continent": "EU", "emoji": "🇫🇷"},
    {"code": "GF", "name": "French Guiana", "continent": "SA", "emoji": "🇬🇫"},
    {"code": "PF", "name": "French Polynesia", "continent": "OC", "emoji": "🇵🇫"},
    {
        "code": "TF",
        "name": "French Southern Territories",
        "continent": "AN",
        "emoji": "🇹🇫",
    },
    {"code": "GA", "name": "Gabon", "continent": "AF", "emoji": "🇬🇦"},
    {"code": "GM", "name": "Gambia", "continent": "AF", "emoji": "🇬🇲"},
    {"code": "GE", "name": "Georgia", "continent": "AS", "emoji": "🇬🇪"},
    {"code": "DE", "name": "Germany", "continent": "EU", "emoji": "🇩🇪"},
    {"code": "GH", "name": "Ghana", "continent": "AF", "emoji": "🇬🇭"},
    {"code": "GI", "name": "Gibraltar", "continent": "EU", "emoji": "🇬🇮"},
    {"code": "GR", "name": "Greece", "continent": "EU", "emoji": "🇬🇷"},
    {"code": "GL", "name": "Greenland", "continent": "NA", "emoji": "🇬🇱"},
    {"code": "GD", "name": "Grenada", "continent": "NA", "emoji": "🇬🇩"},
    {"code": "GP", "name": "Guadeloupe", "continent": "NA", "emoji": "🇬🇵"},
    {"code": "GU", "name": "Guam", "continent": "OC", "emoji": "🇬🇺"},
    {"code": "GT", "name": "Guatemala", "continent": "NA", "emoji": "🇬🇹"},
    {"code": "GG", "name": "Guernsey", "continent": "EU", "emoji": "🇬🇬"},
    {"code": "GN", "name": "Guinea", "continent": "AF", "emoji": "🇬🇳"},
    {"code": "GW", "name": "Guinea-Bissau", "continent": "AF", "emoji": "🇬🇼"},
    {"code": "GY", "name": "Guyana", "continent": "SA", "emoji": "🇬🇾"},
    {"code": "HT", "name": "Haiti", "continent": "NA", "emoji": "🇭🇹"},
    {
        "code": "HM",
        "name": "Heard Island and McDonald Islands",
        "continent": "AN",
        "emoji": "🇭🇲",
    },
    {
        "code": "VA",
        "name": "Holy See (Vatican City State)",
        "continent": "EU",
        "emoji": "🇻🇦",
    },
    {"code": "HN", "name": "Honduras", "continent": "NA", "emoji": "🇭🇳"},
    {"code": "HK", "name": "Hong Kong", "continent": "AS", "emoji": "🇭🇰"},
    {"code": "HU", "name": "Hungary", "continent": "EU", "emoji": "🇭🇺"},
    {"code": "IS", "name": "Iceland", "continent": "EU", "emoji": "🇮🇸"},
    {"code": "IN", "name": "India", "continent": "AS", "emoji": "🇮🇳"},
    {"code": "ID", "name": "Indonesia", "continent": "AS", "emoji": "🇮🇩"},
    {
        "code": "IR",
        "name": "Iran, Islamic Republic of",
        "continent": "AS",
        "emoji": "🇮🇷",
    },
    {"code": "IQ", "name": "Iraq", "continent": "AS", "emoji": "🇮🇶"},
    {"code": "IE", "name": "Ireland", "continent": "EU", "emoji": "🇮🇪"},
    {"code": "IM", "name": "Isle of Man", "continent": "EU", "emoji": "🇮🇲"},
    {"code": "IL", "name": "Israel", "continent": "AS", "emoji": "🇮🇱"},
    {"code": "IT", "name": "Italy", "continent": "EU", "emoji": "🇮🇹"},
    {"code": "JM", "name": "Jamaica", "continent": "NA", "emoji": "🇯🇲"},
    {"code": "JP", "name": "Japan", "continent": "AS", "emoji": "🇯🇵"},
    {"code": "JE", "name": "Jersey", "continent": "EU", "emoji": "🇯🇪"},
    {"code": "JO", "name": "Jordan", "continent": "AS", "emoji": "🇯🇴"},
    {"code": "KZ", "name": "Kazakhstan", "continent": "AS", "emoji": "🇰🇿"},
    {"code": "KE", "name": "Kenya", "continent": "AF", "emoji": "🇰🇪"},
    {"code": "KI", "name": "Kiribati", "continent": "OC", "emoji": "🇰🇮"},
    {
        "code": "KP",
        "name": "Korea, Democratic People's Republic of",
        "continent": "AS",
        "emoji": "🇰🇵",
    },
    {"code": "KR", "name": "Korea, Republic of", "continent": "AS", "emoji": "🇰🇷"},
    {"code": "KW", "name": "Kuwait", "continent": "AS", "emoji": "🇰🇼"},
    {"code": "KG", "name": "Kyrgyzstan", "continent": "AS", "emoji": "🇰🇬"},
    {
        "code": "LA",
        "name": "Lao People's Democratic Republic",
        "continent": "AS",
        "emoji": "🇱🇦",
    },
    {"code": "LV", "name": "Latvia", "continent": "EU", "emoji": "🇱🇻"},
    {"code": "LB", "name": "Lebanon", "continent": "AS", "emoji": "🇱🇧"},
    {"code": "LS", "name": "Lesotho", "continent": "AF", "emoji": "🇱🇸"},
    {"code": "LR", "name": "Liberia", "continent": "AF", "emoji": "🇱🇷"},
    {"code": "LY", "name": "Libya", "continent": "AF", "emoji": "🇱🇾"},
    {"code": "LI", "name": "Liechtenstein", "continent": "EU", "emoji": "🇱🇮"},
    {"code": "LT", "name": "Lithuania", "continent": "EU", "emoji": "🇱🇹"},
    {"code": "LU", "name": "Luxembourg", "continent": "EU", "emoji": "🇱🇺"},
    {"code": "MO", "name": "Macao", "continent": "AS", "emoji": "🇲🇴"},
    {"code": "MG", "name": "Madagascar", "continent": "AF", "emoji": "🇲🇬"},
    {"code": "MW", "name": "Malawi", "continent": "AF", "emoji": "🇲🇼"},
    {"code": "MY", "name": "Malaysia", "continent": "AS", "emoji": "🇲🇾"},
    {"code": "MV", "name": "Maldives", "continent": "AS", "emoji": "🇲🇻"},
    {"code": "ML", "name": "Mali", "continent": "AF", "emoji": "🇲🇱"},
    {"code": "MT", "name": "Malta", "continent": "EU", "emoji": "🇲🇹"},
    {"code": "MH", "name": "Marshall Islands", "continent": "OC", "emoji": "🇲🇭"},
    {"code": "MQ", "name": "Martinique", "continent": "NA", "emoji": "🇲🇶"},
    {"code": "MR", "name": "Mauritania", "continent": "AF", "emoji": "🇲🇷"},
    {"code": "MU", "name": "Mauritius", "continent": "AF", "emoji": "🇲🇺"},
    {"code": "YT", "name": "Mayotte", "continent": "AF", "emoji": "🇾🇹"},
    {"code": "MX", "name": "Mexico", "continent": "NA", "emoji": "🇲🇽"},
    {
        "code": "FM",
        "name": "Micronesia, Federated States of",
        "continent": "OC",
        "emoji": "🇫🇲",
    },
    {"code": "MD", "name": "Moldova, Republic of", "continent": "EU", "emoji": "🇲🇩"},
    {"code": "MC", "name": "Monaco", "continent": "EU", "emoji": "🇲🇨"},
    {"code": "MN", "name": "Mongolia", "continent": "AS", "emoji": "🇲🇳"},
    {"code": "ME", "name": "Montenegro", "continent": "EU", "emoji": "🇲🇪"},
    {"code": "MS", "name": "Montserrat", "continent": "NA", "emoji": "🇲🇸"},
    {"code": "MA", "name": "Morocco", "continent": "AF", "emoji": "🇲🇦"},
    {"code": "MZ", "name": "Mozambique", "continent": "AF", "emoji": "🇲🇿"},
    {"code": "MM", "name": "Myanmar", "continent": "AS", "emoji": "🇲🇲"},
    {"code": "NA", "name": "Namibia", "continent": "AF", "emoji": "🇳🇦"},
    {"code": "NR", "name": "Nauru", "continent": "OC", "emoji": "🇳🇷"},
    {"code": "NP", "name": "Nepal", "continent": "AS", "emoji": "🇳🇵"},
    {"code": "NL", "name": "Netherlands", "continent": "EU", "emoji": "🇳🇱"},
    {"code": "NC", "name": "New Caledonia", "continent": "OC", "emoji": "🇳🇨"},
    {"code": "NZ", "name": "New Zealand", "continent": "OC", "emoji": "🇳🇿"},
    {"code": "NI", "name": "Nicaragua", "continent": "NA", "emoji": "🇳🇮"},
    {"code": "NE", "name": "Niger", "continent": "AF", "emoji": "🇳🇪"},
    {"code": "NG", "name": "Nigeria", "continent": "AF", "emoji": "🇳🇬"},
    {"code": "NU", "name": "Niue", "continent": "OC", "emoji": "🇳🇺"},
    {"code": "NF", "name": "Norfolk Island", "continent": "OC", "emoji": "🇳🇫"},
    {"code": "MK", "name": "North Macedonia", "continent": "EU", "emoji": "🇲🇰"},
    {
        "code": "MP",
        "name": "Northern Mariana Islands",
        "continent": "OC",
        "emoji": "🇲🇵",
    },
    {"code": "NO", "name": "Norway", "continent": "EU", "emoji": "🇳🇴"},
    {"code": "OM", "name": "Oman", "continent": "AS", "emoji": "🇴🇲"},
    {"code": "PK", "name": "Pakistan", "continent": "AS", "emoji": "🇵🇰"},
    {"code": "PW", "name": "Palau", "continent": "OC", "emoji": "🇵🇼"},
    {"code": "PS", "name": "Palestine, State of", "continent": "AS", "emoji": "🇵🇸"},
    {"code": "PA", "name": "Panama", "continent": "NA", "emoji": "🇵🇦"},
    {"code": "PG", "name": "Papua New Guinea", "continent": "OC", "emoji": "🇵🇬"},
    {"code": "PY", "name": "Paraguay", "continent": "SA", "emoji": "🇵🇾"},
    {"code": "PE", "name": "Peru", "continent": "SA", "emoji": "🇵🇪"},
    {"code": "PH", "name": "Philippines", "continent": "AS", "emoji": "🇵🇭"},
    {"code": "PN", "name": "Pitcairn", "continent": "OC", "emoji": "🇵🇳"},
    {"code": "PL", "name": "Poland", "continent": "EU", "emoji": "🇵🇱"},
    {"code": "PT", "name": "Portugal", "continent": "EU", "emoji": "🇵🇹"},
    {"code": "PR", "name": "Puerto Rico", "continent": "NA", "emoji": "🇵🇷"},
    {"code": "QA", "name": "Qatar", "continent": "AS", "emoji": "🇶🇦"},
    {"code": "RO", "name": "Romania", "continent": "EU", "emoji": "🇷🇴"},
    {"code": "RU", "name": "Russian Federation", "continent": "EU", "emoji": "🇷🇺"},
    {"code": "RW", "name": "Rwanda", "continent": "AF", "emoji": "🇷🇼"},
    {"code": "RE", "name": "Réunion", "continent": "AF", "emoji": "🇷🇪"},
    {"code": "BL", "name": "Saint Barthélemy", "continent": "NA", "emoji": "🇧🇱"},
    {
        "code": "SH",
        "name": "Saint Helena, Ascension and Tristan da Cunha",
        "continent": "AF",
        "emoji": "🇸🇭",
    },
    {"code": "KN", "name": "Saint Kitts and Nevis", "continent": "NA", "emoji": "🇰🇳"},
    {"code": "LC", "name": "Saint Lucia", "continent": "NA", "emoji": "🇱🇨"},
    {
        "code": "MF",
        "name": "Saint Martin (French part)",
        "continent": "NA",
        "emoji": "🇲🇫",
    },
    {
        "code": "PM",
        "name": "Saint Pierre and Miquelon",
        "continent": "NA",
        "emoji": "🇵🇲",
    },
    {
        "code": "VC",
        "name": "Saint Vincent and the Grenadines",
        "continent": "NA",
        "emoji": "🇻🇨",
    },
    {"code": "WS", "name": "Samoa", "continent": "OC", "emoji": "🇼🇸"},
    {"code": "SM", "name": "San Marino", "continent": "EU", "emoji": "🇸🇲"},
    {"code": "ST", "name": "Sao Tome and Principe", "continent": "AF", "emoji": "🇸🇹"},
    {"code": "SA", "name": "Saudi Arabia", "continent": "AS", "emoji": "🇸🇦"},
    {"code": "SN", "name": "Senegal", "continent": "AF", "emoji": "🇸🇳"},
    {"code": "RS", "name": "Serbia", "continent": "EU", "emoji": "🇷🇸"},
    {"code": "SC", "name": "Seychelles", "continent": "AF", "emoji": "🇸🇨"},
    {"code": "SL", "name": "Sierra Leone", "continent": "AF", "emoji": "🇸🇱"},
    {"code": "SG", "name": "Singapore", "continent": "AS", "emoji": "🇸🇬"},
    {
        "code": "SX",
        "name": "Sint Maarten (Dutch part)",
        "continent": "NA",
        "emoji": "🇸🇽",
    },
    {"code": "SK", "name": "Slovakia", "continent": "EU", "emoji": "🇸🇰"},
    {"code": "SI", "name": "Slovenia", "continent": "EU", "emoji": "🇸🇮"},
    {"code": "SB", "name": "Solomon Islands", "continent": "OC", "emoji": "🇸🇧"},
    {"code": "SO", "name": "Somalia", "continent": "AF", "emoji": "🇸🇴"},
    {"code": "ZA", "name": "South Africa", "continent": "AF", "emoji": "🇿🇦"},
    {
        "code": "GS",
        "name": "South Georgia and the South Sandwich Islands",
        "continent": "AN",
        "emoji": "🇬🇸",
    },
    {"code": "SS", "name": "South Sudan", "continent": "AF", "emoji": "🇸🇸"},
    {"code": "ES", "name": "Spain", "continent": "EU", "emoji": "🇪🇸"},
    {"code": "LK", "name": "Sri Lanka", "continent": "AS", "emoji": "🇱🇰"},
    {"code": "SD", "name": "Sudan", "continent": "AF", "emoji": "🇸🇩"},
    {"code": "SR", "name": "Suriname", "continent": "SA", "emoji": "🇸🇷"},
    {"code": "SJ", "name": "Svalbard and Jan Mayen", "continent": "EU", "emoji": "🇸🇯"},
    {"code": "SE", "name": "Sweden", "continent": "EU", "emoji": "🇸🇪"},
    {"code": "CH", "name": "Switzerland", "continent": "EU", "emoji": "🇨🇭"},
    {"code": "SY", "name": "Syrian Arab Republic", "continent": "AS", "emoji": "🇸🇾"},
    {
        "code": "TW",
        "name": "Taiwan, Province of China",
        "continent": "AS",
        "emoji": "🇹🇼",
    },
    {"code": "TJ", "name": "Tajikistan", "continent": "AS", "emoji": "🇹🇯"},
    {
        "code": "TZ",
        "name": "Tanzania, United Republic of",
        "continent": "AF",
        "emoji": "🇹🇿",
    },
    {"code": "TH", "name": "Thailand", "continent": "AS", "emoji": "🇹🇭"},
    {"code": "TL", "name": "Timor-Leste", "continent": "OC", "emoji": "🇹🇱"},
    {"code": "TG", "name": "Togo", "continent": "AF", "emoji": "🇹🇬"},
    {"code": "TK", "name": "Tokelau", "continent": "OC", "emoji": "🇹🇰"},
    {"code": "TO", "name": "Tonga", "continent": "OC", "emoji": "🇹🇴"},
    {"code": "TT", "name": "Trinidad and Tobago", "continent": "NA", "emoji": "🇹🇹"},
    {"code": "TN", "name": "Tunisia", "continent": "AF", "emoji": "🇹🇳"},
    {"code": "TM", "name": "Turkmenistan", "continent": "AS", "emoji": "🇹🇲"},
    {
        "code": "TC",
        "name": "Turks and Caicos Islands",
        "continent": "NA",
        "emoji": "🇹🇨",
    },
    {"code": "TV", "name": "Tuvalu", "continent": "OC", "emoji": "🇹🇻"},
    {"code": "TR", "name": "Türkiye", "continent": "AS", "emoji": "🇹🇷"},
    {"code": "UG", "name": "Uganda", "continent": "AF", "emoji": "🇺🇬"},
    {"code": "UA", "name": "Ukraine", "continent": "EU", "emoji": "🇺🇦"},
    {"code": "AE", "name": "United Arab Emirates", "continent": "AS", "emoji": "🇦🇪"},
    {"code": "GB", "name": "United Kingdom", "continent": "EU", "emoji": "🇬🇧"},
    {"code": "US", "name": "United States", "continent": "NA", "emoji": "🇺🇸"},
    {
        "code": "UM",
        "name": "United States Minor Outlying Islands",
        "continent": "OC",
        "emoji": "🇺🇲",
    },
    {"code": "UY", "name": "Uruguay", "continent": "SA", "emoji": "🇺🇾"},
    {"code": "UZ", "name": "Uzbekistan", "continent": "AS", "emoji": "🇺🇿"},
    {"code": "VU", "name": "Vanuatu", "continent": "OC", "emoji": "🇻🇺"},
    {
        "code": "VE",
        "name": "Venezuela, Bolivarian Republic of",
        "continent": "SA",
        "emoji": "🇻🇪",
    },
    {"code": "VN", "name": "Viet Nam", "continent": "AS", "emoji": "🇻🇳"},
    {"code": "VG", "name": "Virgin Islands, British", "continent": "NA", "emoji": "🇻🇬"},
    {"code": "VI", "name": "Virgin Islands, U.S.", "continent": "NA", "emoji": "🇻🇮"},
    {"code": "WF", "name": "Wallis and Futuna", "continent": "OC", "emoji": "🇼🇫"},
    {"code": "EH", "name": "Western Sahara", "continent": "AF", "emoji": "🇪🇭"},
    {"code": "YE", "name": "Yemen", "continent": "AS", "emoji": "🇾🇪"},
    {"code": "ZM", "name": "Zambia", "continent": "AF", "emoji": "🇿🇲"},
    {"code": "ZW", "name": "Zimbabwe", "continent": "AF", "emoji": "🇿🇼"},
    {"code": "AX", "name": "Åland Islands", "continent": "EU", "emoji": "🇦🇽"},
]


CONTINENTS = [
    {"code": "AF", "name": "Africa"},
    {"code": "NA", "name": "North America"},
    {"code": "OC", "name": "Oceania"},
    {"code": "AN", "name": "Antarctica"},
    {"code": "AS", "name": "Asia"},
    {"code": "EU", "name": "Europe"},
    {"code": "SA", "name": "South America"},
]
