# https://www.iso.org/obp/ui/#search
COUNTRIES = [
    {"code": "AD", "name": "Andorra", "continent": "EU"},
    {"code": "AE", "name": "United Arab Emirates", "continent": "AS"},
    {"code": "AF", "name": "Afghanistan", "continent": "AS"},
    {"code": "AG", "name": "Antigua and Barbuda", "continent": "NA"},
    {"code": "AI", "name": "Anguilla", "continent": "NA"},
    {"code": "AL", "name": "Albania", "continent": "EU"},
    {"code": "AM", "name": "Armenia", "continent": "AS"},
    {"code": "AO", "name": "Angola", "continent": "AF"},
    {"code": "AQ", "name": "Antarctica", "continent": "AN"},
    {"code": "AR", "name": "Argentina", "continent": "SA"},
    {"code": "AS", "name": "American Samoa", "continent": "OC"},
    {"code": "AT", "name": "Austria", "continent": "EU"},
    {"code": "AU", "name": "Australia", "continent": "OC"},
    {"code": "AW", "name": "Aruba", "continent": "NA"},
    {"code": "AX", "name": "\u00c5land Islands", "continent": "EU"},
    {"code": "AZ", "name": "Azerbaijan", "continent": "AS"},
    {"code": "BA", "name": "Bosnia and Herzegovina", "continent": "EU"},
    {"code": "BB", "name": "Barbados", "continent": "NA"},
    {"code": "BD", "name": "Bangladesh", "continent": "AS"},
    {"code": "BE", "name": "Belgium", "continent": "EU"},
    {"code": "BF", "name": "Burkina Faso", "continent": "AF"},
    {"code": "BG", "name": "Bulgaria", "continent": "EU"},
    {"code": "BH", "name": "Bahrain", "continent": "AS"},
    {"code": "BI", "name": "Burundi", "continent": "AF"},
    {"code": "BJ", "name": "Benin", "continent": "AF"},
    {"code": "BL", "name": "Saint Barth\u00e9lemy", "continent": "NA"},
    {"code": "BM", "name": "Bermuda", "continent": "NA"},
    {"code": "BN", "name": "Brunei Darussalam", "continent": "AS"},
    {"code": "BO", "name": "Bolivia, Plurinational State of", "continent": "SA"},
    {"code": "BQ", "name": "Bonaire, Sint Eustatius and Saba", "continent": "NA"},
    {"code": "BR", "name": "Brazil", "continent": "SA"},
    {"code": "BS", "name": "Bahamas", "continent": "NA"},
    {"code": "BT", "name": "Bhutan", "continent": "AS"},
    {"code": "BV", "name": "Bouvet Island", "continent": "AN"},
    {"code": "BW", "name": "Botswana", "continent": "AF"},
    {"code": "BY", "name": "Belarus", "continent": "EU"},
    {"code": "BZ", "name": "Belize", "continent": "NA"},
    {"code": "CA", "name": "Canada", "continent": "NA"},
    {"code": "CC", "name": "Cocos (Keeling) Islands", "continent": "AS"},
    {"code": "CD", "name": "Congo, The Democratic Republic of the", "continent": "AF"},
    {"code": "CF", "name": "Central African Republic", "continent": "AF"},
    {"code": "CG", "name": "Congo", "continent": "AF"},
    {"code": "CH", "name": "Switzerland", "continent": "EU"},
    {"code": "CI", "name": "C\u00f4te d'Ivoire", "continent": "AF"},
    {"code": "CK", "name": "Cook Islands", "continent": "OC"},
    {"code": "CL", "name": "Chile", "continent": "SA"},
    {"code": "CM", "name": "Cameroon", "continent": "AF"},
    {"code": "CN", "name": "China", "continent": "AS"},
    {"code": "CO", "name": "Colombia", "continent": "SA"},
    {"code": "CR", "name": "Costa Rica", "continent": "NA"},
    {"code": "CU", "name": "Cuba", "continent": "NA"},
    {"code": "CV", "name": "Cabo Verde", "continent": "AF"},
    {"code": "CW", "name": "Cura\u00e7ao", "continent": "NA"},
    {"code": "CX", "name": "Christmas Island", "continent": "OC"},
    {"code": "CY", "name": "Cyprus", "continent": "EU"},
    {"code": "CZ", "name": "Czechia", "continent": "EU"},
    {"code": "DE", "name": "Germany", "continent": "EU"},
    {"code": "DJ", "name": "Djibouti", "continent": "AF"},
    {"code": "DK", "name": "Denmark", "continent": "EU"},
    {"code": "DM", "name": "Dominica", "continent": "NA"},
    {"code": "DO", "name": "Dominican Republic", "continent": "NA"},
    {"code": "DZ", "name": "Algeria", "continent": "AF"},
    {"code": "EC", "name": "Ecuador", "continent": "SA"},
    {"code": "EE", "name": "Estonia", "continent": "EU"},
    {"code": "EG", "name": "Egypt", "continent": "AF"},
    {"code": "EH", "name": "Western Sahara", "continent": "AF"},
    {"code": "ER", "name": "Eritrea", "continent": "AF"},
    {"code": "ES", "name": "Spain", "continent": "EU"},
    {"code": "ET", "name": "Ethiopia", "continent": "AF"},
    {"code": "FI", "name": "Finland", "continent": "EU"},
    {"code": "FJ", "name": "Fiji", "continent": "OC"},
    {"code": "FK", "name": "Falkland Islands (Malvinas)", "continent": "SA"},
    {"code": "FM", "name": "Micronesia, Federated States of", "continent": "OC"},
    {"code": "FO", "name": "Faroe Islands", "continent": "EU"},
    {"code": "FR", "name": "France", "continent": "EU"},
    {"code": "GA", "name": "Gabon", "continent": "AF"},
    {"code": "GB", "name": "United Kingdom", "continent": "EU"},
    {"code": "GD", "name": "Grenada", "continent": "NA"},
    {"code": "GE", "name": "Georgia", "continent": "AS"},
    {"code": "GF", "name": "French Guiana", "continent": "SA"},
    {"code": "GG", "name": "Guernsey", "continent": "EU"},
    {"code": "GH", "name": "Ghana", "continent": "AF"},
    {"code": "GI", "name": "Gibraltar", "continent": "EU"},
    {"code": "GL", "name": "Greenland", "continent": "NA"},
    {"code": "GM", "name": "Gambia", "continent": "AF"},
    {"code": "GN", "name": "Guinea", "continent": "AF"},
    {"code": "GP", "name": "Guadeloupe", "continent": "NA"},
    {"code": "GQ", "name": "Equatorial Guinea", "continent": "AF"},
    {"code": "GR", "name": "Greece", "continent": "EU"},
    {
        "code": "GS",
        "name": "South Georgia and the South Sandwich Islands",
        "continent": "AN",
    },
    {"code": "GT", "name": "Guatemala", "continent": "NA"},
    {"code": "GU", "name": "Guam", "continent": "OC"},
    {"code": "GW", "name": "Guinea-Bissau", "continent": "AF"},
    {"code": "GY", "name": "Guyana", "continent": "SA"},
    {"code": "HK", "name": "Hong Kong", "continent": "AS"},
    {"code": "HM", "name": "Heard Island and McDonald Islands", "continent": "AN"},
    {"code": "HN", "name": "Honduras", "continent": "NA"},
    {"code": "HR", "name": "Croatia", "continent": "EU"},
    {"code": "HT", "name": "Haiti", "continent": "NA"},
    {"code": "HU", "name": "Hungary", "continent": "EU"},
    {"code": "ID", "name": "Indonesia", "continent": "AS"},
    {"code": "IE", "name": "Ireland", "continent": "EU"},
    {"code": "IL", "name": "Israel", "continent": "AS"},
    {"code": "IM", "name": "Isle of Man", "continent": "EU"},
    {"code": "IN", "name": "India", "continent": "AS"},
    {"code": "IO", "name": "British Indian Ocean Territory", "continent": "AS"},
    {"code": "IQ", "name": "Iraq", "continent": "AS"},
    {"code": "IR", "name": "Iran, Islamic Republic of", "continent": "AS"},
    {"code": "IS", "name": "Iceland", "continent": "EU"},
    {"code": "IT", "name": "Italy", "continent": "EU"},
    {"code": "JE", "name": "Jersey", "continent": "EU"},
    {"code": "JM", "name": "Jamaica", "continent": "NA"},
    {"code": "JO", "name": "Jordan", "continent": "AS"},
    {"code": "JP", "name": "Japan", "continent": "AS"},
    {"code": "KE", "name": "Kenya", "continent": "AF"},
    {"code": "KG", "name": "Kyrgyzstan", "continent": "AS"},
    {"code": "KH", "name": "Cambodia", "continent": "AS"},
    {"code": "KI", "name": "Kiribati", "continent": "OC"},
    {"code": "KM", "name": "Comoros", "continent": "AF"},
    {"code": "KN", "name": "Saint Kitts and Nevis", "continent": "NA"},
    {"code": "KP", "name": "Korea, Democratic People's Republic of", "continent": "AS"},
    {"code": "KR", "name": "Korea, Republic of", "continent": "AS"},
    {"code": "KW", "name": "Kuwait", "continent": "AS"},
    {"code": "KY", "name": "Cayman Islands", "continent": "NA"},
    {"code": "KZ", "name": "Kazakhstan", "continent": "AS"},
    {"code": "LA", "name": "Lao People's Democratic Republic", "continent": "AS"},
    {"code": "LB", "name": "Lebanon", "continent": "AS"},
    {"code": "LC", "name": "Saint Lucia", "continent": "NA"},
    {"code": "LI", "name": "Liechtenstein", "continent": "EU"},
    {"code": "LK", "name": "Sri Lanka", "continent": "AS"},
    {"code": "LR", "name": "Liberia", "continent": "AF"},
    {"code": "LS", "name": "Lesotho", "continent": "AF"},
    {"code": "LT", "name": "Lithuania", "continent": "EU"},
    {"code": "LU", "name": "Luxembourg", "continent": "EU"},
    {"code": "LV", "name": "Latvia", "continent": "EU"},
    {"code": "LY", "name": "Libya", "continent": "AF"},
    {"code": "MA", "name": "Morocco", "continent": "AF"},
    {"code": "MC", "name": "Monaco", "continent": "EU"},
    {"code": "MD", "name": "Moldova, Republic of", "continent": "EU"},
    {"code": "ME", "name": "Montenegro", "continent": "EU"},
    {"code": "MF", "name": "Saint Martin (French part)", "continent": "NA"},
    {"code": "MG", "name": "Madagascar", "continent": "AF"},
    {"code": "MH", "name": "Marshall Islands", "continent": "OC"},
    {"code": "MK", "name": "North Macedonia", "continent": "EU"},
    {"code": "ML", "name": "Mali", "continent": "AF"},
    {"code": "MM", "name": "Myanmar", "continent": "AS"},
    {"code": "MN", "name": "Mongolia", "continent": "AS"},
    {"code": "MO", "name": "Macao", "continent": "AS"},
    {"code": "MP", "name": "Northern Mariana Islands", "continent": "OC"},
    {"code": "MQ", "name": "Martinique", "continent": "NA"},
    {"code": "MR", "name": "Mauritania", "continent": "AF"},
    {"code": "MS", "name": "Montserrat", "continent": "NA"},
    {"code": "MT", "name": "Malta", "continent": "EU"},
    {"code": "MU", "name": "Mauritius", "continent": "AF"},
    {"code": "MV", "name": "Maldives", "continent": "AS"},
    {"code": "MW", "name": "Malawi", "continent": "AF"},
    {"code": "MX", "name": "Mexico", "continent": "NA"},
    {"code": "MY", "name": "Malaysia", "continent": "AS"},
    {"code": "MZ", "name": "Mozambique", "continent": "AF"},
    {"code": "NA", "name": "Namibia", "continent": "AF"},
    {"code": "NC", "name": "New Caledonia", "continent": "OC"},
    {"code": "NE", "name": "Niger", "continent": "AF"},
    {"code": "NF", "name": "Norfolk Island", "continent": "OC"},
    {"code": "NG", "name": "Nigeria", "continent": "AF"},
    {"code": "NI", "name": "Nicaragua", "continent": "NA"},
    {"code": "NL", "name": "Netherlands", "continent": "EU"},
    {"code": "NO", "name": "Norway", "continent": "EU"},
    {"code": "NP", "name": "Nepal", "continent": "AS"},
    {"code": "NR", "name": "Nauru", "continent": "OC"},
    {"code": "NU", "name": "Niue", "continent": "OC"},
    {"code": "NZ", "name": "New Zealand", "continent": "OC"},
    {"code": "OM", "name": "Oman", "continent": "AS"},
    {"code": "PA", "name": "Panama", "continent": "NA"},
    {"code": "PE", "name": "Peru", "continent": "SA"},
    {"code": "PF", "name": "French Polynesia", "continent": "OC"},
    {"code": "PG", "name": "Papua New Guinea", "continent": "OC"},
    {"code": "PH", "name": "Philippines", "continent": "AS"},
    {"code": "PK", "name": "Pakistan", "continent": "AS"},
    {"code": "PL", "name": "Poland", "continent": "EU"},
    {"code": "PM", "name": "Saint Pierre and Miquelon", "continent": "NA"},
    {"code": "PN", "name": "Pitcairn", "continent": "OC"},
    {"code": "PR", "name": "Puerto Rico", "continent": "NA"},
    {"code": "PS", "name": "Palestine, State of", "continent": "AS"},
    {"code": "PT", "name": "Portugal", "continent": "EU"},
    {"code": "PW", "name": "Palau", "continent": "OC"},
    {"code": "PY", "name": "Paraguay", "continent": "SA"},
    {"code": "QA", "name": "Qatar", "continent": "AS"},
    {"code": "RE", "name": "R\u00e9union", "continent": "AF"},
    {"code": "RO", "name": "Romania", "continent": "EU"},
    {"code": "RS", "name": "Serbia", "continent": "EU"},
    {"code": "RU", "name": "Russian Federation", "continent": "EU"},
    {"code": "RW", "name": "Rwanda", "continent": "AF"},
    {"code": "SA", "name": "Saudi Arabia", "continent": "AS"},
    {"code": "SB", "name": "Solomon Islands", "continent": "OC"},
    {"code": "SC", "name": "Seychelles", "continent": "AF"},
    {"code": "SD", "name": "Sudan", "continent": "AF"},
    {"code": "SE", "name": "Sweden", "continent": "EU"},
    {"code": "SG", "name": "Singapore", "continent": "AS"},
    {
        "code": "SH",
        "name": "Saint Helena, Ascension and Tristan da Cunha",
        "continent": "AF",
    },
    {"code": "SI", "name": "Slovenia", "continent": "EU"},
    {"code": "SJ", "name": "Svalbard and Jan Mayen", "continent": "EU"},
    {"code": "SK", "name": "Slovakia", "continent": "EU"},
    {"code": "SL", "name": "Sierra Leone", "continent": "AF"},
    {"code": "SM", "name": "San Marino", "continent": "EU"},
    {"code": "SN", "name": "Senegal", "continent": "AF"},
    {"code": "SO", "name": "Somalia", "continent": "AF"},
    {"code": "SR", "name": "Suriname", "continent": "SA"},
    {"code": "SS", "name": "South Sudan", "continent": "AF"},
    {"code": "ST", "name": "Sao Tome and Principe", "continent": "AF"},
    {"code": "SV", "name": "El Salvador", "continent": "NA"},
    {"code": "SX", "name": "Sint Maarten (Dutch part)", "continent": "NA"},
    {"code": "SY", "name": "Syrian Arab Republic", "continent": "AS"},
    {"code": "SZ", "name": "Eswatini", "continent": "AF"},
    {"code": "TC", "name": "Turks and Caicos Islands", "continent": "NA"},
    {"code": "TD", "name": "Chad", "continent": "AF"},
    {"code": "TF", "name": "French Southern Territories", "continent": "AN"},
    {"code": "TG", "name": "Togo", "continent": "AF"},
    {"code": "TH", "name": "Thailand", "continent": "AS"},
    {"code": "TJ", "name": "Tajikistan", "continent": "AS"},
    {"code": "TK", "name": "Tokelau", "continent": "OC"},
    {"code": "TL", "name": "Timor-Leste", "continent": "OC"},
    {"code": "TM", "name": "Turkmenistan", "continent": "AS"},
    {"code": "TN", "name": "Tunisia", "continent": "AF"},
    {"code": "TO", "name": "Tonga", "continent": "OC"},
    {"code": "TR", "name": "T\u00fcrkiye", "continent": "AS"},
    {"code": "TT", "name": "Trinidad and Tobago", "continent": "NA"},
    {"code": "TV", "name": "Tuvalu", "continent": "OC"},
    {"code": "TW", "name": "Taiwan, Province of China", "continent": "AS"},
    {"code": "TZ", "name": "Tanzania, United Republic of", "continent": "AF"},
    {"code": "UA", "name": "Ukraine", "continent": "EU"},
    {"code": "UG", "name": "Uganda", "continent": "AF"},
    {"code": "UM", "name": "United States Minor Outlying Islands", "continent": "OC"},
    {"code": "US", "name": "United States", "continent": "NA"},
    {"code": "UY", "name": "Uruguay", "continent": "SA"},
    {"code": "UZ", "name": "Uzbekistan", "continent": "AS"},
    {"code": "VA", "name": "Holy See (Vatican City State)", "continent": "EU"},
    {"code": "VC", "name": "Saint Vincent and the Grenadines", "continent": "NA"},
    {"code": "VE", "name": "Venezuela, Bolivarian Republic of", "continent": "SA"},
    {"code": "VG", "name": "Virgin Islands, British", "continent": "NA"},
    {"code": "VI", "name": "Virgin Islands, U.S.", "continent": "NA"},
    {"code": "VN", "name": "Viet Nam", "continent": "AS"},
    {"code": "VU", "name": "Vanuatu", "continent": "OC"},
    {"code": "WF", "name": "Wallis and Futuna", "continent": "OC"},
    {"code": "WS", "name": "Samoa", "continent": "OC"},
    {"code": "YE", "name": "Yemen", "continent": "AS"},
    {"code": "YT", "name": "Mayotte", "continent": "AF"},
    {"code": "ZA", "name": "South Africa", "continent": "AF"},
    {"code": "ZM", "name": "Zambia", "continent": "AF"},
    {"code": "ZW", "name": "Zimbabwe", "continent": "AF"},
]


CONTINENTS = [
    {"code": "AF", "name": "Africa"},
    {"code": "NA", "name": "North America"},
    {"code": "OC", "name": "Oceania"},
    {"code": "AN", "name": "Antarctica"},
    {"code": "AS", "name": "Asia"},
    {"code": "EU", "name": "Europe"},
    {"code": "SA", "name": "South America"},
]
