# Generated by Django 4.1.7 on 2023-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_news_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='excerpt',
            field=models.TextField(max_length=255),
        ),
    ]
