# Generated by Django 3.2.9 on 2022-01-01 05:43

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import i18n.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', i18n.fields.I18nCharField(max_length=200, verbose_name='title')),
                ('slug', i18n.fields.I18nCharField(blank=True, max_length=200, verbose_name='slug')),
                ('company', models.CharField(max_length=100, verbose_name='company')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='job-listings', verbose_name='company logo')),
                ('description', i18n.fields.I18nTextField(blank=True, verbose_name='description')),
                ('apply_url', models.URLField(blank=True, verbose_name='URL where you can apply')),
            ],
            options={
                'ordering': ['created'],
            },
            managers=[
                ('published_posts', django.db.models.manager.Manager()),
            ],
        ),
    ]
