# Generated by Django 3.2.9 on 2022-01-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='joblisting',
            managers=[
            ],
        ),
    ]
