# Generated by Django 3.2.12 on 2022-06-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_allow_sorting_job_postings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='apply_url',
            field=models.TextField(blank=True, verbose_name='URL where you can apply'),
        ),
    ]
