# Generated by Django 5.1.4 on 2025-04-13 16:00

from django.db import migrations, models


def fix_data(apps, schema_editor):
    JobListing = apps.get_model('job_board', 'JobListing')
    for job_listing in JobListing.objects.all():
        if job_listing.slug:
            slug = job_listing.slug.localize('en')
            assert slug
            job_listing.slug = slug
        if job_listing.title:
            title = job_listing.title.localize('en')
            assert title
            job_listing.title = title
        if job_listing.description:
            description = job_listing.description.localize('en')
            assert description
            job_listing.description = description
        job_listing.save()

class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0005_connect_job_listings_to_a_conf'),
    ]

    operations = [
        migrations.RunPython(fix_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='joblisting',
            name='apply_url',
            field=models.TextField(blank=True, verbose_name='Where you can apply'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.TextField(max_length=200, verbose_name='title'),
        ),
    ]
