# Generated by Django 5.1.4 on 2025-04-13 16:08

from django.db import migrations

def fix_quotes(apps, schema_editor):
    JobListing = apps.get_model('job_board', 'JobListing')
    for job_listing in JobListing.objects.all():
        if job_listing.title:
            title = job_listing.title.replace('"', "")
            assert title
            job_listing.title = title
        if job_listing.description:
            description = job_listing.description.replace('"', "")
            assert description
            job_listing.description = description
        if job_listing.slug:
            slug = job_listing.slug.replace('"', "")
            assert slug
            job_listing.slug = slug
        job_listing.save()

class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0006_alter_joblisting_apply_url_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_quotes, migrations.RunPython.noop),
    ]
