# Generated by Django 3.2.12 on 2023-01-28 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_make_submission_topi_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grants', '0004_grant_age_group'),
        ('reviews', '0001_initial_reviews_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('comment', models.TextField(blank=True)),
                ('grant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grants.grant')),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.submission')),
                ('review_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewsession')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.availablevoteoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
