# Generated by Django 4.2.7 on 2024-01-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_rename_options_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreview",
            name="private_comment",
            field=models.TextField(blank=True),
        ),
    ]
