# Generated by Django 4.2.7 on 2024-01-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_userreview_private_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("reviewing", "Reviewing"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=100,
            ),
        ),
    ]
