# Generated by Django 4.2.7 on 2024-01-14 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0006_alter_reviewsession_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewsession",
            options={"permissions": [("review_reviewsession", "Can review items")]},
        ),
    ]
