# Generated by Django 4.2.7 on 2024-01-15 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0007_alter_reviewsession_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewsession",
            options={
                "permissions": [
                    ("review_reviewsession", "Can review items"),
                    ("decision_reviewsession", "Can make decisions on items"),
                ]
            },
        ),
    ]
