"""store jwt auth id

Revision ID: 2e5e687d84d9
Revises: c998e741da04
Create Date: 2021-03-23 01:17:49.193077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5e687d84d9'
down_revision = 'c998e741da04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jwt_auth_id', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jwt_auth_id')
    # ### end Alembic commands ###
