"""add request reset password id

Revision ID: c00ad83a0232
Revises: c998e741da04
Create Date: 2021-03-22 00:26:32.265224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00ad83a0232'
down_revision = 'c998e741da04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('request_reset_password_id', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'request_reset_password_id')
    # ### end Alembic commands ###
