"""add tagline

Revision ID: c6e28d415f58
Revises: 2e5e687d84d9
Create Date: 2022-04-18 19:33:50.320144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e28d415f58'
down_revision = '2e5e687d84d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tagline', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tagline')
    # ### end Alembic commands ###
