# Generated by Django 3.1.4 on 2021-05-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterField(
                    model_name='hotelroomreservation',
                    name='user',
                    field=models.ForeignKey('users.User', db_constraint=False, db_index=True, null=False, on_delete=models.PROTECT)
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='hotelroomreservation',
                    name='user',
                ),
                migrations.AddField(
                    model_name='hotelroomreservation',
                    name='user_id',
                    field=models.IntegerField(verbose_name='user'),
                ),
            ]
        ),
    ]
