# Generated by Django 3.2.12 on 2022-12-21 12:02

from django.db import migrations, models
import i18n.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_room_reservation_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', i18n.fields.I18nCharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=200, verbose_name='code')),
            ],
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='available_bed_layouts',
            field=models.ManyToManyField(to='hotels.BedLayout'),
        ),
    ]
