# Generated by Django 3.2.12 on 2022-12-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_bed_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomreservation',
            name='bed_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotels.bedlayout'),
        ),
    ]
