# Generated by Django 3.2.12 on 2022-12-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_store_selected_bed_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedlayout',
            name='code',
        ),
    ]
