# Generated by Django 4.2.3 on 2023-10-01 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hotels", "0005_remove_code_from_bed_layout"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX hotels_hotelroomreservation_user_id_6109bb14;",
                    reverse_sql="CREATE INDEX hotels_hotelroomreservation_user_id_6109bb14 ON hotels_hotelroomreservation USING btree (user_id);",
                ),
                migrations.AlterField(
                    model_name="hotelroomreservation",
                    name="user_id",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                        db_column="user_id",
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="hotelroomreservation",
                    name="user_id",
                ),
                migrations.AddField(
                    model_name="hotelroomreservation",
                    name="user",
                    field=models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                    preserve_default=False,
                ),
            ],
        )
    ]
