const style =
  "style=element:labels.icon%7Chue:0x0066ff%7Cweight:1.9&style=element:labels.text.fill%7Ccolor:0x1673cb&style=feature:administrative%7Celement:geometry.stroke%7Chue:0x0077ff%7Csaturation:86%7Cweight:0.8&style=feature:administrative.land_parcel%7Celement:labels%7Cvisibility:off&style=feature:landscape.man_made%7Celement:geometry%7Ccolor:0xc7e2ff&style=feature:landscape.natural%7Ccolor:0xbcddff&style=feature:poi%7Celement:geometry%7Ccolor:0x4797e0&style=feature:poi%7Celement:geometry.fill%7Chue:0x0077ff%7Csaturation:-7%7Clightness:24&style=feature:poi%7Celement:labels.text%7Cvisibility:off&style=feature:poi.business%7Cvisibility:off&style=feature:poi.park%7Celement:geometry%7Ccolor:0x209ee1%7Clightness:49&style=feature:poi.park%7Celement:labels.text%7Cvisibility:off&style=feature:road.arterial%7Ccolor:0xebf4ff&style=feature:road.highway%7Celement:geometry.fill%7Ccolor:0x5fb3ff&style=feature:road.highway%7Celement:geometry.stroke%7Ccolor:0x3ea3ff&style=feature:road.highway%7Celement:labels.icon%7Chue:0x006eff%7Csaturation:58&style=feature:road.local%7Celement:geometry.fill%7Ccolor:0xebf4ff&style=feature:road.local%7Celement:geometry.stroke%7Ccolor:0x93c8ff%7Cvisibility:on&style=feature:road.local%7Celement:labels%7Cvisibility:off&style=feature:transit.line%7Celement:geometry.fill%7Ccolor:0x83befc&style=feature:transit.station.airport%7Celement:geometry%7Chue:0x0088ff%7Csaturation:100%7Cgamma:0.82";
const zoom = 15;
const center = "43.766134073544755,11.272070140475412";
const size = "1800x250";
const marker = `markers=label:P%7Ccolor:0xFFFF00%7Csize:mid%7Cscale:2%7Ccolor:yellow%7C${center}`;
const API_KEY = "AIzaSyDCF_XajdxbTxD5S3-yP8kG8I1kdMO7D1A";

export const GOOGLE_MAPS_URL = `https://maps.googleapis.com/maps/api/staticmap?key=${API_KEY}&${marker}&center=${center}&zoom=${zoom}&format=png&maptype=roadmap&${style}&size=${size}&scale=2`;
