# Generated by Django 4.2.7 on 2024-05-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_speakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailspeaker',
            name='send_only_to_speakers_without_ticket',
            field=models.BooleanField(default=False),
        ),
    ]
