# Generated by Django 4.2.7 on 2024-05-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_speakers', '0002_emailspeaker_send_only_to_speakers_without_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailspeaker',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
