# Generated by Django 4.2.7 on 2024-05-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_speakers', '0003_emailspeaker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailspeaker',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
