# Generated by Django 4.2.7 on 2024-05-02 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_speakers', '0004_emailspeaker_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSpeakerRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20, verbose_name='status')),
                ('is_test', models.BooleanField(default=False)),
                ('email_speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='email_speakers.emailspeaker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_speaker_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
