# Generated by Django 4.2.7 on 2024-05-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_speakers', '0005_emailspeakerrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailspeakerrecipient',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
