"""Initial user model

Revision ID: faeec382945e
Revises:
Create Date: 2021-01-24 02:10:26.913809

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "faeec382945e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fullname", sa.String(length=300), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("gender", sa.String(length=10), nullable=False),
        sa.Column("date_birth", sa.Date(), nullable=False),
        sa.Column("open_to_recruiting", sa.Boolean(), nullable=False),
        sa.Column("open_to_newsletter", sa.Boolean(), nullable=False),
        sa.Column("country", sa.String(length=50), nullable=False),
        sa.Column("date_joined", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
