# Generated by Django 2.0.3 on 2018-03-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('bank_transfer', 'bank transfer'), ('stripe', 'stripe')], max_length=10, verbose_name='payment provider'),
        ),
    ]
