# Generated by Django 4.1.7 on 2023-05-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0036_add_support_for_cospeakers_vouchers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeConferenceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('roles', models.JSONField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
            ],
        ),
    ]
