# Generated by Django 4.1.7 on 2023-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_alter_attendeeconferencerole_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeconferencerole',
            name='order_position_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendeeconferencerole',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
