# Generated by Django 2.2.8 on 2020-01-06 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0017_auto_20191231_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('full_name', models.CharField(max_length=300, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('age', models.PositiveSmallIntegerField(verbose_name='age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_say', 'Prefer not to say')], max_length=10, verbose_name='gender')),
                ('occupation', models.CharField(choices=[('developer', 'Developer'), ('student', 'Student'), ('researcher', 'Researcher'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=10, verbose_name='occupation')),
                ('grant_type', models.CharField(choices=[('diversity', 'Diversity'), ('unemployed', 'Unemployed'), ('speaker', 'Speaker')], max_length=10, verbose_name='grant type')),
                ('python_usage', models.TextField(verbose_name='How do they use python')),
                ('been_to_other_events', models.TextField(verbose_name='Have they been to other events?')),
                ('interested_in_volunteering', models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('absolutely', 'My soul is yours to take!')], max_length=10, verbose_name='interested in volunteering')),
                ('needs_funds_for_travel', models.BooleanField(verbose_name='Needs funds for travel')),
                ('why', models.TextField(verbose_name='Why are you asking for a grant?')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('travelling_from', models.CharField(max_length=200, verbose_name='Travelling from')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='conferences.Conference', verbose_name='conference')),
            ],
            options={
                'unique_together': {('email', 'conference')},
            },
        ),
    ]
