# Generated by Django 2.2.8 on 2020-01-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_say', 'Prefer not to say')], max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
