# Generated by Django 3.2.12 on 2022-11-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_auto_20200107_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='grant',
            unique_together=set(),
        ),
    ]
