# Generated by Django 3.2.12 on 2022-12-01 12:50

from django.db import migrations, models
from grants.models import Grant


def convert_data(apps, schema_editor):

    for grant in Grant.objects.all():
        if grant.age == 0:
            continue
        if grant.age <= 10:
            grant.age_group = Grant.AgeGroup.RANGE_LESS_THAN_10
        if 11 <= grant.age <= 18:
            grant.age_group = Grant.AgeGroup.RANGE_11_18
        if 19 <= grant.age <= 24:
            grant.age_group = Grant.AgeGroup.RANGE_19_24
        if 25 <= grant.age <= 34:
            grant.age_group = Grant.AgeGroup.RANGE_25_34
        if 35 <= grant.age <= 44:
            grant.age_group = Grant.AgeGroup.RANGE_35_44
        if 45 <= grant.age <= 54:
            grant.age_group = Grant.AgeGroup.RANGE_45_54
        if 55 <= grant.age <= 64:
            grant.age_group = Grant.AgeGroup.RANGE_55_64
        if grant.age >= 65:
            grant.age_group = Grant.AgeGroup.RANGE_MORE_THAN_65

        grant.save()


class Migration(migrations.Migration):

    dependencies = [
        ("grants", "0003_add_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="age_group",
            field=models.CharField(
                choices=[
                    ("range_less_than_10", "10 years old or under"),
                    ("range_11_18", "11 - 18 years old"),
                    ("range_19_24", "19 - 24 years old"),
                    ("range_25_34", "25 - 34 years old"),
                    ("range_35_44", "35 - 44 years old"),
                    ("range_45_54", "45 - 54 years old"),
                    ("range_55_64", "55 - 64 years old"),
                    ("range_more_than_65", "65 years or older"),
                ],
                max_length=20,
                null=True,
                verbose_name="Age group",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="age",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="age"),
        ),
        migrations.RunPython(convert_data),
    ]
