# Generated by Django 3.2.12 on 2023-02-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_grant_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='applicant_reply_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='applicant reply sent at'),
        ),
        migrations.AddField(
            model_name='grant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('waiting_list', 'Waiting List'), ('waiting_list_maybe', 'Waiting List, Maybe'), ('waiting_for_confirmation', 'Waiting for confirmation'), ('refused', 'Refused'), ('confirmed', 'Confirmed'), ('maybe', 'Maybe')], default='pending', max_length=30, verbose_name='status'),
        ),
    ]
