# Generated by Django 4.1.6 on 2023-02-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_grant_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='accommodation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='accommodation amount'),
        ),
        migrations.AddField(
            model_name='grant',
            name='applicant_message',
            field=models.TextField(blank=True, null=True, verbose_name='applicant message'),
        ),
        migrations.AddField(
            model_name='grant',
            name='applicant_reply_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='applicant reply deadline'),
        ),
        migrations.AddField(
            model_name='grant',
            name='applicant_reply_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='applicant reply sent at'),
        ),
        migrations.AddField(
            model_name='grant',
            name='approved_type',
            field=models.CharField(blank=True, choices=[('ticket_only', 'Ticket Only'), ('ticket_travel', 'Ticket + Travel'), ('ticket_accommodation', 'Ticket + Accommodation'), ('Ticket', 'Ticket + Travel + Accommodation')], max_length=30, null=True, verbose_name='approved type'),
        ),
        migrations.AddField(
            model_name='grant',
            name='country_type',
            field=models.CharField(blank=True, choices=[('italy', 'Italy'), ('europe', 'Europe'), ('extra_eu', 'Extra EU')], max_length=10, null=True, verbose_name='Country type'),
        ),
        migrations.AddField(
            model_name='grant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('waiting_list', 'Waiting List'), ('waiting_list_maybe', 'Waiting List, Maybe'), ('waiting_for_confirmation', 'Waiting for confirmation'), ('refused', 'Refused'), ('confirmed', 'Confirmed'), ('needs_info', 'Needs Info')], default='pending', max_length=30, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='grant',
            name='ticket_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='ticket amount'),
        ),
        migrations.AddField(
            model_name='grant',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='total amount'),
        ),
        migrations.AddField(
            model_name='grant',
            name='travel_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='travel amount'),
        ),
    ]
