# Generated by Django 4.1.6 on 2023-02-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_grant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='approved_amount',
        ),
        migrations.AddField(
            model_name='grant',
            name='accommodation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='accommodation amount'),
        ),
        migrations.AddField(
            model_name='grant',
            name='country_type',
            field=models.CharField(blank=True, choices=[('italy', 'Italy'), ('europe', 'Europe'), ('extra_eu', 'Extra EU')], max_length=10, null=True, verbose_name='Country type'),
        ),
        migrations.AddField(
            model_name='grant',
            name='ticket_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='ticket amount'),
        ),
        migrations.AddField(
            model_name='grant',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='total amount'),
        ),
        migrations.AddField(
            model_name='grant',
            name='travel_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='travel amount'),
        ),
    ]
