# Generated by Django 4.2.7 on 2023-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants", "0011_alter_grant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="community_contribution",
            field=models.TextField(blank=True, verbose_name="Community contribution"),
        ),
        migrations.AddField(
            model_name="grant",
            name="github_handle",
            field=models.CharField(
                blank=True, max_length=39, null=True, verbose_name="GitHub handle"
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="linkedin_url",
            field=models.URLField(
                blank=True, max_length=2048, verbose_name="LinkedIn url"
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="mastodon_handle",
            field=models.CharField(
                blank=True, max_length=2048, verbose_name="Mastodon handle"
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="need_accommodation",
            field=models.BooleanField(default=False, verbose_name="Need accommodation"),
        ),
        migrations.AddField(
            model_name="grant",
            name="need_visa",
            field=models.BooleanField(
                default=False, verbose_name="Need visa/invitation letter?"
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="twitter_handle",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Twitter handle"
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="website",
            field=models.URLField(blank=True, max_length=2048, verbose_name="Website"),
        ),
    ]
