# Generated by Django 4.2.7 on 2023-12-29 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grants", "0015_alter_grant_travelling_from"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GrantRecap",
        ),
    ]
