# Generated by Django 4.2.7 on 2024-01-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants", "0016_delete_grantrecap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grant",
            name="github_handle",
            field=models.CharField(
                blank=True, default="", max_length=39, verbose_name="GitHub handle"
            ),
            preserve_default=False,
        ),
    ]
