# Generated by Django 4.2.7 on 2024-01-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants", "0017_alter_grant_github_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="plain_thread_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Plain threadID"
            ),
        ),
    ]
