# Generated by Django 4.2.7 on 2024-05-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants", "0018_grant_plain_thread_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes only available to the Financial Aid Commettie",
                verbose_name="Internal Notes",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                    ("waiting_list", "Waiting List"),
                    ("waiting_list_maybe", "Waiting List, Maybe"),
                    ("waiting_for_confirmation", "Waiting for confirmation"),
                    ("refused", "Refused"),
                    ("confirmed", "Confirmed"),
                    ("did_not_attend", "Did Not Attend"),
                ],
                default="pending",
                max_length=30,
                verbose_name="status",
            ),
        ),
    ]
