# Generated by Django 4.2.7 on 2024-07-20 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grants", "0019_grant_internal_notes_alter_grant_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grant",
            name="applicant_message",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="plain_thread_id",
        ),
    ]
