# Generated by Django 5.1.1 on 2024-11-16 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grants", "0020_remove_grant_applicant_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grant",
            name="interested_in_volunteering",
        ),
    ]
