# Generated by Django 5.1.1 on 2024-11-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0021_remove_grant_interested_in_volunteering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='needs_funds_for_travel',
        ),
        migrations.AddField(
            model_name='grant',
            name='need_funds_for_travel',
            field=models.BooleanField(default=False, verbose_name='Needs funds for travel'),
        ),
    ]
