# Generated by Django 5.1.1 on 2024-12-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants", "0021_remove_grant_interested_in_volunteering"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="departure_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Departure city"
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nationality"
            ),
        ),
    ]
