# Generated by Django 5.1.1 on 2024-12-01 17:59

from django.db import migrations, models
import json

def forwards_func(apps, schema_editor):
    Grant = apps.get_model('grants', 'Grant')
    for grant in Grant.objects.all():
        old_value = grant.grant_type
        # Convert the old string value into a list
        grant.grant_type_json = [old_value] if old_value else []
        grant.save(update_fields=['grant_type_json'])

def reverse_func(apps, schema_editor):
    Grant = apps.get_model('grants', 'Grant')
    for grant in Grant.objects.all():
        value_list = grant.grant_type
        # Convert the list back to a single string
        if value_list:
            grant.grant_type = value_list[0]
        else:
            grant.grant_type = ''
        grant.save(update_fields=['grant_type'])

class Migration(migrations.Migration):
    dependencies = [
        ("grants", "0022_grant_departure_city_grant_nationality_and_more"),
    ]

    operations = [
        # Step 1: Add a temporary JSONField
        migrations.AddField(
            model_name='grant',
            name='grant_type_json',
            field=models.JSONField(default=list, verbose_name="grant type"),
        ),
        # Step 2: Backfill data into the temporary field
        migrations.RunPython(forwards_func, reverse_func),
        # Step 3: Remove the old field
        migrations.RemoveField(
            model_name='grant',
            name='grant_type',
        ),
        # Step 4: Rename the temporary field to grant_type
        migrations.RenameField(
            model_name='grant',
            old_name='grant_type_json',
            new_name='grant_type',
        ),
    ]
