# Generated by Django 5.1.1 on 2024-12-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0023_alter_grant_grant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='age_group',
            field=models.CharField(blank=True, choices=[('range_under_18', 'Under 18 years old'), ('range_18_24', '18 - 24 years old'), ('range_25_34', '25 - 34 years old'), ('range_35_44', '35 - 44 years old'), ('range_45_54', '45 - 54 years old'), ('range_55_64', '55 - 64 years old'), ('range_more_than_65', '65 years or older')], max_length=20, verbose_name='Age group'),
        ),
    ]
