# Generated by Django 5.1.4 on 2024-12-20 14:23

from django.db import migrations, models


def fix_data(apps, schema_editor):
    Grant = apps.get_model("grants", "Grant")
    Grant.objects.filter(approved_type="Ticket").update(approved_type="ticket_travel_accommodation")

class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0024_alter_grant_age_group'),
    ]

    operations = [
        migrations.RunPython(fix_data, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='grant',
            name='approved_type',
            field=models.CharField(blank=True, choices=[('ticket_only', 'Ticket Only'), ('ticket_travel', 'Ticket + Travel'), ('ticket_accommodation', 'Ticket + Accommodation'), ('ticket_travel_accommodation', 'Ticket + Travel + Accommodation')], max_length=30, null=True, verbose_name='approved type'),
        ),
    ]
