# Generated by Django 5.1.4 on 2025-01-20 00:57

from django.db import migrations, models

def copy_grant_status_to_pending_status(apps, schema_editor):
    Grant = apps.get_model('grants', 'Grant')
    for grant in Grant.objects.all():
        grant.pending_status = grant.status
        grant.save(update_fields=['pending_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0025_alter_grant_approved_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='pending_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('waiting_list', 'Waiting List'), ('waiting_list_maybe', 'Waiting List, Maybe'), ('waiting_for_confirmation', 'Waiting for confirmation'), ('refused', 'Refused'), ('confirmed', 'Confirmed'), ('did_not_attend', 'Did Not Attend')], default='pending', max_length=30, verbose_name='pending status'),
        ),
        migrations.RunPython(copy_grant_status_to_pending_status, reverse_code=migrations.RunPython.noop),
    ]
