# Generated by Django 5.1.4 on 2025-01-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0026_grant_pending_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantConfirmPendingStatusProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Grant Confirm Pending Status',
                'verbose_name_plural': 'Grants Confirm Pending Status',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('grants.grant',),
        ),
    ]
