# Generated by Django 5.1.4 on 2025-01-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0027_grantconfirmpendingstatusproxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='pretix_voucher_id',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='voucher_code',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='voucher_email_sent_at',
        ),
    ]
