# Generated by Django 5.1.4 on 2025-07-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0028_remove_grant_pretix_voucher_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='pending_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('waiting_list', 'Waiting List'), ('waiting_list_maybe', 'Waiting List, Maybe'), ('waiting_for_confirmation', 'Waiting for confirmation'), ('refused', 'Refused'), ('confirmed', 'Confirmed'), ('did_not_attend', 'Did Not Attend')], max_length=30, null=True, verbose_name='pending status'),
        ),
    ]
