# Generated by Django 5.1.4 on 2025-06-04 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0054_conference_frontend_revalidate_secret_and_more'),
        ('grants', '0028_remove_grant_pretix_voucher_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantReimbursementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_amount', models.DecimalField(decimal_places=0, help_text='Maximum amount for this category', max_digits=6)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('ticket', 'Ticket'), ('accommodation', 'Accommodation'), ('other', 'Other')], max_length=20)),
                ('included_by_default', models.BooleanField(default=False, help_text='Automatically include this category in grants by default')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_categories', to='conferences.conference')),
            ],
            options={
                'verbose_name': 'Grant Reimbursement Category',
                'verbose_name_plural': 'Grant Reimbursement Categories',
                'ordering': ['conference', 'category'],
                'unique_together': {('conference', 'category')},
            },
        ),
    ]
