# Generated by Django 5.1.4 on 2025-06-04 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0029_grantreimbursementcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantReimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_amount', models.DecimalField(decimal_places=0, help_text='Actual amount granted for this category', max_digits=6, verbose_name='granted amount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grants.grantreimbursementcategory', verbose_name='reimbursement category')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='grants.grant', verbose_name='grant')),
            ],
            options={
                'verbose_name': 'Grant Reimbursement',
                'verbose_name_plural': 'Grant Reimbursements',
                'ordering': ['grant', 'category'],
                'unique_together': {('grant', 'category')},
            },
        ),
        migrations.AddField(
            model_name='grant',
            name='reimbursement_categories',
            field=models.ManyToManyField(related_name='grants', through='grants.GrantReimbursement', to='grants.grantreimbursementcategory'),
        ),
    ]
