# Generated by Django 5.1.4 on 2025-11-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0030_remove_grant_accommodation_amount_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grantreimbursement',
            index=models.Index(fields=['grant', 'category'], name='grants_gran_grant_i_bd545b_idx'),
        ),
    ]
