# Generated by Django 5.2.8 on 2026-08-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_forms', '0001_initial'),
        ('grants', '0031_grantreimbursement_grants_gran_grant_i_bd545b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='form_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant', to='generic_forms.formanswer'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='been_to_other_events',
            field=models.TextField(blank=True, verbose_name='Have they been to other events?'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='occupation',
            field=models.CharField(blank=True, choices=[('developer', 'Developer'), ('student', 'Student'), ('researcher', 'Researcher'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=10, verbose_name='occupation'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='python_usage',
            field=models.TextField(blank=True, verbose_name='How do they use python'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='why',
            field=models.TextField(blank=True, verbose_name='Why are you asking for a grant?'),
        ),
    ]
