# Generated by Django 2.2.7 on 2019-11-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_subscribed', models.DateTimeField(auto_now_add=True, verbose_name='date subscribed')),
            ],
        ),
    ]
