# Generated by Django 2.2.8 on 2019-12-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='subject')),
                ('heading', models.CharField(max_length=300, verbose_name='heading')),
                ('body', models.TextField(verbose_name='body')),
                ('cta_label', models.CharField(blank=True, default='', max_length=100, verbose_name='link label')),
                ('cta_link', models.CharField(blank=True, default='', max_length=100, verbose_name='link')),
                ('recipients_types', models.CharField(choices=[('newsletter', 'Newsletter')], max_length=50, verbose_name='Recipients Type')),
                ('recipients', models.TextField(blank=True, default='', verbose_name='recipients')),
                ('send_date', models.DateTimeField(verbose_name='send date')),
            ],
        ),
    ]
