# Generated by Django 2.2.8 on 2019-12-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_auto_20191231_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='send_date',
        ),
        migrations.AddField(
            model_name='email',
            name='scheduled_date',
            field=models.DateTimeField(null=True, verbose_name='scheduled date'),
        ),
    ]
