# Generated by Django 2.2.8 on 2020-01-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_auto_20191231_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='recipients_types',
            new_name='recipients_type',
        ),
    ]
