# Generated by Django 2.2.8 on 2020-01-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0007_auto_20200105_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], default='draft', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='email',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='scheduled date'),
        ),
    ]
