# Generated by Django 3.1.4 on 2020-12-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0008_auto_20200105_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
