# Generated by Django 2.2.3 on 2019-07-16 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('abstract', models.TextField(max_length=1000, verbose_name='abstract')),
                ('elevator_pitch', models.TextField(blank=True, default='', max_length=300, verbose_name='elevator pitch')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='conferences.Conference', verbose_name='conference')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conferences.Duration', verbose_name='duration')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.Language', verbose_name='language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
