# Generated by Django 2.2.3 on 2019-07-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20190716_0954'),
        ('submissions', '0002_submission_audience_level'),
    ]

    operations = [
    ]
