# Generated by Django 2.2.6 on 2019-11-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("submissions", "0003_merge_20190730_2025")]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="slug",
            field=models.SlugField(default="", max_length=200, verbose_name="slug"),
            preserve_default=False,
        )
    ]
