# Generated by Django 2.2.7 on 2019-11-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_merge_20191113_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='tags',
            field=models.ManyToManyField(to='submissions.SubmissionTag', verbose_name='tags'),
        ),
    ]
