# Generated by Django 2.2.8 on 2020-01-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20191214_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='abstract',
            field=models.TextField(max_length=5000, verbose_name='abstract'),
        ),
    ]
