# Generated by Django 2.2.8 on 2020-02-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_submissioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('cancelled', 'Cancelled')], default='proposed', max_length=20, verbose_name='status'),
        ),
    ]
