mutation SendGrant($input: SendGrantInput!) {
  mutationOp: sendGrant(input: $input) {
    __typename

    ... on Grant {
      id
    }

    ... on GrantErrors {
      errors {
        validationConference: conference
        validationName: name
        validationFullName: fullName
        validationGender: gender
        validationGrantType: grantType
        validationOccupation: occupation
        validationNeedsFundsForTravel: needsFundsForTravel
        validationNeedVisa: needVisa
        validationNeedAccommodation: needAccommodation
        validationDepartureCountry: departureCountry
        validationParticipantBio: participantBio
        validationParticipantWebsite: participantWebsite
        validationParticipantTwitterHandle: participantTwitterHandle
        validationparticipantInstagramHandle: participantInstagramHandle
        validationParticipantLinkedinUrl: participantLinkedinUrl
        validationParticipantFacebookUrl: participantFacebookUrl
        validationParticipantMastodonHandle: participantMastodonHandle
        nonFieldErrors
        answersErrors
      }
    }
  }
}
