# Generated by Django 2.2.8 on 2020-02-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
