# Generated by Django 2.2.8 on 2020-01-05 14:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0006_auto_20200105_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254, verbose_name='recipients'), blank=True, null=True, size=None),
        ),
    ]
