FROM node:alpine AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

FROM node:alpine AS runner

WORKDIR /app

COPY --from=deps /app/node_modules /app/node_modules
COPY . .

EXPOSE 3020

CMD ["yarn", "dev"]
