query Header($code: String!) {
  conference(code: $code) {
    id
    isRunning
    currentDay {
      day
      rooms {
        id
        streamingUrl
      }
    }
    conferenceMenu: menu(identifier: "conference-nav") {
      links {
        text: title(language: "en")
        link: href(language: "en")

        page {
          slug(language: "en")
        }
      }
    }
    programMenu: menu(identifier: "program-nav") {
      links {
        text: title(language: "en")
        link: href(language: "en")

        page {
          slug(language: "en")
        }
      }
    }
  }
}
