# Generated by Django 4.2.3 on 2023-10-29 18:58

import association_membership.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('active', 'ACTIVE'), ('canceled', 'CANCELED')], default=association_membership.enums.MembershipStatus['PENDING'], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=256, unique=True)),
                ('total', models.IntegerField()),
                ('payment_date', models.DateTimeField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('paid', 'PAID'), ('canceled', 'CANCELED')], max_length=20)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='association_membership.membership')),
            ],
        ),
        migrations.CreateModel(
            name='StripeSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=256)),
                ('stripe_invoice_id', models.CharField(max_length=256, unique=True)),
                ('invoice_pdf', models.TextField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_subscription_payments', to='association_membership.payment')),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=256, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PretixPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=256, unique=True)),
                ('event_organizer', models.CharField(max_length=512)),
                ('event_id', models.CharField(max_length=512)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pretix_payments', to='association_membership.payment')),
            ],
        ),
    ]
