# Generated by Django 4.2.3 on 2023-07-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoogleCloudOAuthCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.TextField()),
                ("client_secret", models.TextField()),
                ("project_id", models.TextField()),
                ("auth_uri", models.URLField()),
                ("token_uri", models.URLField()),
                ("auth_provider_x509_cert_url", models.URLField()),
            ],
            options={
                "verbose_name": "Google Cloud OAuth Credential",
                "verbose_name_plural": "Google Cloud OAuth Credentials",
            },
        ),
    ]
