# Generated by Django 4.2.3 on 2023-07-22 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_api', '0002_googlecloudtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecloudoauthcredential',
            name='quota_limit_for_youtube',
            field=models.IntegerField(default=10000),
        ),
        migrations.CreateModel(
            name='UsedRequestQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('cost', models.IntegerField()),
                ('service', models.CharField(max_length=255)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_api.googlecloudoauthcredential')),
            ],
        ),
    ]
