# Generated by Django 4.2.3 on 2023-07-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_api', '0003_googlecloudoauthcredential_quota_limit_for_youtube_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedrequestquota',
            old_name='credential',
            new_name='credentials',
        ),
    ]
