# Generated by Django 5.2.8 on 2026-08-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("google_api", "0004_rename_credential_usedrequestquota_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecloudoauthcredential",
            name="quota_limit_for_drive",
            field=models.IntegerField(default=10000),
        ),
    ]
