# Generated by Django 4.2.7 on 2024-07-07 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0042_conference_video_description_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WetransferToS3TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('wetransfer_url', models.URLField(max_length=2048, verbose_name='WeTransfer URL')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('failed', 'Failed'), ('done', 'Done')], default='pending', max_length=10)),
                ('imported_files', models.JSONField(blank=True, null=True, verbose_name='Imported files')),
                ('failed_reason', models.TextField(blank=True, null=True, verbose_name='Failed reason')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference', verbose_name='conference')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
