# Generated by Django 2.2.3 on 2019-07-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterange',
            name='step',
        ),
    ]
