# Generated by Django 2.2.3 on 2019-07-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20190716_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(0, 'Not Interested'), (1, 'Maybe'), (2, 'Want to See'), (3, 'Must See')], verbose_name='vote'),
        ),
    ]
