# Generated by Django 2.2.3 on 2019-07-17 07:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_remove_conference_vote_range'),
        ('submissions', '0002_auto_20190716_0954'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0004_auto_20190716_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteRange',
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'submission')},
        ),
    ]
