# Generated by Django 2.2.8 on 2020-01-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20200110_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(1, 'Not Interested'), (2, 'Maybe'), (3, 'Want to See'), (4, 'Must See')], verbose_name='vote'),
        ),
    ]
