# Generated by Django 2.2.8 on 2020-01-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_rankrequest_ranksubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranksubmission',
            name='topic_score',
        ),
    ]
