# Generated by Django 2.2.8 on 2020-02-02 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_vote_propagated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='propagated',
        ),
        migrations.AlterField(
            model_name='rankrequest',
            name='conference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference', verbose_name='conference'),
        ),
    ]
