# Generated by Django 2.2.4 on 2019-08-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_to_newsletter',
            field=models.BooleanField(default=False, verbose_name='open to newsletter'),
        ),
    ]
