# Generated by Django 2.2.4 on 2019-08-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190808_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='business name'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, verbose_name='fiscal code'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='pec_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='PEC'),
        ),
        migrations.AddField(
            model_name='user',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=7, verbose_name='recipient code'),
        ),
        migrations.AddField(
            model_name='user',
            name='vat_number',
            field=models.CharField(blank=True, max_length=22, verbose_name='VAT number'),
        ),
    ]
