# Generated by Django 2.2.4 on 2019-09-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190901_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fiscal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pec_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recipient_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vat_number',
        ),
    ]
