# Generated by Django 2.2.4 on 2019-08-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_to_recruiting',
            field=models.BooleanField(default=False, verbose_name='open to recruiting'),
        ),
    ]
