# Generated by Django 4.2.3 on 2023-09-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_auth_id',
            field=models.IntegerField(default=1, verbose_name='jwt auth id'),
        ),
    ]
