# Generated by Django 4.2.7 on 2024-01-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conferences", "0039_conference_slack_new_sponsor_lead_incoming_webhook_url"),
        ("users", "0007_user_jwt_auth_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_all_conferences",
            field=models.BooleanField(
                default=False, verbose_name="admin all conferences"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="admin_conferences",
            field=models.ManyToManyField(
                blank=True,
                to="conferences.conference",
                verbose_name="admin conferences",
            ),
        ),
    ]
