# Generated by Django 4.1.7 on 2023-03-19 21:43

from django.db import migrations
import page.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "text_section",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                ("subtitle", wagtail.blocks.CharBlock(required=False)),
                                ("body", wagtail.blocks.RichTextBlock()),
                                (
                                    "illustration",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("snakeTail", "Snake Tail"),
                                            ("snakeHead", "Snake Head"),
                                            ("snakesWithSigns", "Snakes with Signs"),
                                        ],
                                        icon="image",
                                        required=False,
                                    ),
                                ),
                                (
                                    "accordions",
                                    wagtail.blocks.ListBlock(page.blocks.Accordion),
                                ),
                            ]
                        ),
                    ),
                    (
                        "map",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "longitude",
                                    wagtail.blocks.DecimalBlock(
                                        decimal_places=6, max_digits=9
                                    ),
                                ),
                                (
                                    "latitude",
                                    wagtail.blocks.DecimalBlock(
                                        decimal_places=6, max_digits=9
                                    ),
                                ),
                                ("zoom", wagtail.blocks.IntegerBlock(default=15)),
                                ("link", wagtail.blocks.URLBlock()),
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]
