# Generated by Django 4.1.7 on 2023-03-20 19:34

from django.db import migrations
import page.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_genericpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.fields.StreamField([('text_section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('is_main_title', wagtail.blocks.BooleanBlock(default=False, required=False)), ('subtitle', wagtail.blocks.CharBlock(required=False)), ('body', wagtail.blocks.RichTextBlock(required=False)), ('illustration', wagtail.blocks.ChoiceBlock(choices=[('snakeTail', 'Snake Tail'), ('snakeHead', 'Snake Head'), ('snakesWithSigns', 'Snakes with Signs')], icon='image', required=False)), ('accordions', wagtail.blocks.ListBlock(page.blocks.Accordion)), ('cta', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(required=False)), ('link', wagtail.blocks.CharBlock(required=False))]))])), ('map', wagtail.blocks.StructBlock([('longitude', wagtail.blocks.DecimalBlock(decimal_places=6, max_digits=9)), ('latitude', wagtail.blocks.DecimalBlock(decimal_places=6, max_digits=9)), ('zoom', wagtail.blocks.IntegerBlock(default=15)), ('link', wagtail.blocks.URLBlock())])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('slider_cards_section', wagtail.blocks.StructBlock([('cards', wagtail.blocks.ListBlock(page.blocks.SimpleTextCard))]))], use_json_field=True),
        ),
    ]
