# Generated by Django 2.2.6 on 2019-11-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190716_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='type',
            field=models.CharField(choices=[('submission', 'Submission'), ('keynote', 'Keynote'), ('custom', 'Custom')], max_length=10, verbose_name='type'),
        ),
    ]
