# Generated by Django 2.2.6 on 2019-11-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191103_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schedule_items', verbose_name='image'),
        ),
    ]
