# Generated by Django 2.2.8 on 2020-01-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_scheduleitem_highlight_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='highlight_color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('yellow', 'yellow'), ('orange', 'orange'), ('cinderella', 'cinderella'), ('violet', 'violet'), ('green', 'green')], max_length=15, verbose_name='highlight color'),
        ),
    ]
