# Generated by Django 2.2.8 on 2020-01-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0017_auto_20191231_1607'),
        ('schedule', '0007_scheduleitem_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleitem',
            unique_together={('slug', 'conference')},
        ),
    ]
