# Generated by Django 2.2.8 on 2020-02-05 01:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0017_auto_20191231_1607'),
        ('schedule', '0009_auto_20200126_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('schedule_configuration', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='conferences.Conference', verbose_name='conference')),
            ],
        ),
    ]
