# Generated by Django 2.2.8 on 2020-02-06 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20200206_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='end',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='start',
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='schedule.Slot'),
        ),
    ]
