# Generated by Django 2.2.8 on 2020-02-09 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20200207_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='size',
        ),
    ]
