# Generated by Django 2.2.8 on 2020-02-11 21:56

import django.db.models.deletion
from django.db import migrations, models


def set_language(apps, schema_editor):
    ScheduleItem = apps.get_model("schedule", "ScheduleItem")
    Language = apps.get_model("languages", "Language")

    it = Language.objects.get(code="it")
    en = Language.objects.get(code="en")

    for item in (
        ScheduleItem.objects.filter(submission__isnull=False)
        .select_related("submission")
        .iterator()
    ):
        if item.submission.languages.all().values_list("code", flat=True) == [it.code]:
            item.language = it
        else:
            item.language = en
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
        ("schedule", "0017_auto_20200211_1003"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="languages",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="languages.Language",
                verbose_name="language",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_language),
    ]
