# Generated by Django 2.2.8 on 2020-02-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20200211_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='type',
            field=models.CharField(choices=[('submission', 'Submission'), ('training', 'Training'), ('keynote', 'Keynote'), ('custom', 'Custom')], max_length=10, verbose_name='type'),
        ),
    ]
