on:
  workflow_call:
    inputs:
      githash:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ${{ format('arm64-fargate-{0}{1}{2}', github.run_id, github.run_number, github.run_attempt) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Run ls
        run: ls
      # - name: Run kaniko
      #   uses: pythonitalia/kaniko-action@v1.0
      #   with:
      #     push: true
      #     tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/pythonit/pycon-backend:arm-${{ inputs.githash }}
      #     cache: true
      #     cache-repository: ghcr.io/${{ github.repository }}/cache
