on:
  workflow_call:
    inputs:
      githash:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ${{ format('arm64-fargate-{0}{1}{2}', github.run_id, github.run_number, github.run_attempt) }}
    steps:
      - run: aws sts get-caller-identity
      - name: Run kaniko
        run: |
          /kaniko/executor \
            --dockerfile=./Dockerfile \
            --context=git://github.com/${{ github.repository }}#${{ github.ref }} \
            --context-sub-path=./backend \
            --cache=true \
            --destination=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/pythonit/pycon-backend:arm-test
