name: Backend checks

on:
  pull_request:
    paths:
      - "backend/**/*"
      - "backend/*"
      - ".github/workflows/backend-checks.yml"

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.5"
      - run: pip install poetry

      - name: Cache Poetry
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}-v2
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}-v2

      - name: Set Poetry config
        run: |
          poetry config virtualenvs.create false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Install python dependencies
        working-directory: backend
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Check missing not pushed migrations
        working-directory: backend
        run: poetry run python manage.py makemigrations --check
        env:
          DJANGO_SETTINGS_MODULE: pycon.settings.dev
