# Generated by Django 2.1.1 on 2018-11-03 17:35

from django.db import migrations, models


def create_languages(apps, schema_editor):
    Language = apps.get_model("languages", "Language")
    from ..languages import LANGUAGES

    for language in LANGUAGES:
        Language.objects.create(name=language["English"], code=language["alpha2"])


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="iso name")),
                (
                    "code",
                    models.CharField(max_length=2, unique=True, verbose_name="code"),
                ),
            ],
            options={"verbose_name": "Language", "verbose_name_plural": "Languages"},
        ),
        migrations.RunPython(create_languages, do_nothing),
    ]
