# Generated by Django 2.2.3 on 2019-07-16 09:54

from django.db import migrations, models


def create_languages(apps, schema_editor):
    from ..languages import LANGUAGES

    Language = apps.get_model('languages', 'Language')

    for language in LANGUAGES:
        Language.objects.create(name=language['English'], code=language['alpha2'])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='iso name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.RunPython(create_languages, migrations.RunPython.noop)
    ]
